"use client";
import {useEffect,useState} from "react";import Link from "next/link";import {useRouter} from "next/navigation";import {ArrowLeft,Heart,Lightbulb,NotebookPen,TriangleAlert} from "lucide-react";
import AppLayout from "@/components/layout/AppLayout";import CompletionModal from "@/components/dashboard/CompletionModal";import {useProgress} from "@/context/ProgressContext";import type {PowerBILesson} from "@/lib/powerBILessons";import {getPowerBILesson} from "@/lib/powerBILessons";import {getDAXLesson} from "@/lib/daxFormulas";import {completePowerBIItem,getPowerBINote,loadPowerBIProgress,POWER_BI_PROGRESS_EVENT,savePowerBINote,togglePowerBIFavorite} from "@/lib/powerBIProgress";import {playClickSound,playNotificationSound,playXPSound} from "@/lib/sounds";import {registerStudyActivity} from "@/lib/studyActivity";
export default function PowerBILessonDetail({lesson}:{lesson:PowerBILesson}){const router=useRouter(),{addXP}=useProgress();const initial=loadPowerBIProgress();const [completed,setCompleted]=useState(()=>[...initial.completedLessonIds,...initial.completedDAXIds].includes(lesson.id));const [favorite,setFavorite]=useState(()=>initial.favoriteIds.includes(lesson.id));const [notes,setNotes]=useState(()=>getPowerBINote(lesson.id));const [saved,setSaved]=useState(true);const [celebrate,setCelebrate]=useState(false);
 useEffect(()=>{const sync=()=>{const s=loadPowerBIProgress();setCompleted([...s.completedLessonIds,...s.completedDAXIds].includes(lesson.id));setFavorite(s.favoriteIds.includes(lesson.id))};window.addEventListener(POWER_BI_PROGRESS_EVENT,sync);return()=>window.removeEventListener(POWER_BI_PROGRESS_EVENT,sync)},[lesson.id]);
 useEffect(()=>{const t=window.setTimeout(()=>setSaved(savePowerBINote(lesson.id,notes)),450);return()=>clearTimeout(t)},[lesson.id,notes]);
 const toggle=()=>{playClickSound();const s=togglePowerBIFavorite(lesson.id),next=s.favoriteIds.includes(lesson.id);setFavorite(next);if(next)playNotificationSound()};const complete=()=>{const result=completePowerBIItem(lesson.id);setCompleted([...result.state.completedLessonIds,...result.state.completedDAXIds].includes(lesson.id));if(result.newlyCompleted){addXP(lesson.xpReward);registerStudyActivity({kind:"lesson",source:`power-bi:${lesson.id}`,minutes:15,xp:lesson.xpReward});playXPSound();setCelebrate(true)}};
 return <AppLayout><div className="space-y-7 text-slate-950"><Link href="/power-bi-studio" onClick={playClickSound} className="inline-flex items-center gap-2 font-bold text-amber-800"><ArrowLeft size={18}/> Back to Power BI Studio</Link><header className="rounded-3xl bg-gradient-to-br from-amber-100 via-pink-100 to-purple-100 p-8 shadow-lg"><div className="flex justify-between gap-5"><div><span className="text-5xl">{lesson.icon}</span><h1 className="mt-4 text-4xl font-black text-amber-900 sm:text-5xl">{lesson.title}</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-slate-700">{lesson.description}</p><div className="mt-5 flex flex-wrap gap-2 text-sm font-bold"><Badge>{lesson.category}</Badge><Badge>{lesson.difficulty}</Badge><Badge>+{lesson.xpReward} XP</Badge>{completed&&<Badge>✓ Learned</Badge>}</div></div><button type="button" onClick={toggle} aria-pressed={favorite} className={`h-fit rounded-2xl px-5 py-3 font-bold ${favorite?"bg-pink-100 text-pink-800":"bg-white text-slate-800"}`}><Heart className="inline" size={19} fill={favorite?"currentColor":"none"}/> {favorite?"Favorited":"Favorite"}</button></div></header>
 <Box title="Simple explanation"><p className="leading-8 text-slate-700">{lesson.explanation}</p></Box><Box title="Step-by-step guide"><ol className="space-y-3">{lesson.steps.map((x,i)=><li key={x} className="rounded-2xl bg-amber-50 p-4"><strong>{i+1}.</strong> {x}</li>)}</ol></Box><div className="grid gap-6 lg:grid-cols-2"><Box title="Practical example"><pre className="whitespace-pre-wrap rounded-2xl bg-slate-950 p-5 text-sm leading-7 text-emerald-200">{lesson.example}</pre></Box><Box title="Memory trick"><p className="flex gap-2 font-semibold leading-8"><Lightbulb className="text-amber-600"/>{lesson.memoryTrick}</p></Box></div><div className="grid gap-6 lg:grid-cols-2"><List title="When to use" items={lesson.whenToUse}/><List title="Common mistakes" items={lesson.commonMistakes} warning/></div><List title="Interview questions" items={lesson.interviewQuestions}/>
 <Box title="Personal Notes"><div className="flex justify-between"><p className="flex gap-2 font-bold"><NotebookPen/> Remember it your way</p><span className="text-sm text-slate-600">{saved?"Saved locally":"Saving…"}</span></div><textarea value={notes} onChange={e=>{setNotes(e.target.value);setSaved(false)}} rows={6} className="mt-4 w-full rounded-2xl border border-amber-200 bg-amber-50/40 p-4" placeholder="Write your own example or reminder…"/></Box>
 {lesson.relatedLessons.length>0&&<section><h2 className="text-2xl font-black">Related lessons</h2><div className="mt-4 flex flex-wrap gap-3">{lesson.relatedLessons.map(id=>{const x=getPowerBILesson(id)??getDAXLesson(id);return x?<Link key={id} href={`/power-bi-studio/${id}`} className="rounded-xl bg-white px-4 py-3 font-bold text-amber-900 shadow">{x.icon} {x.title}</Link>:null})}</div></section>}
 <section className="flex flex-col justify-between gap-5 rounded-3xl bg-white p-7 shadow-lg sm:flex-row sm:items-center"><div><h2 className="text-2xl font-black">Ready to apply it?</h2><p className="mt-2 text-slate-700">Practice the concept and save this lesson as learned.</p></div><div className="flex gap-3"><Link href={`/power-bi-studio/${lesson.id}/practice`} onClick={playClickSound} className="rounded-xl bg-purple-700 px-5 py-3 font-bold text-white">Practice</Link><button type="button" disabled={completed} onClick={complete} className="rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white disabled:bg-emerald-100 disabled:text-emerald-800">{completed?"Learned":`Mark Learned · +${lesson.xpReward} XP`}</button></div></section></div><CompletionModal isOpen={celebrate} projectTitle={`${lesson.title} lesson`} xpEarned={lesson.xpReward} onClose={()=>setCelebrate(false)} onContinue={()=>{setCelebrate(false);router.push(`/power-bi-studio/${lesson.id}/practice`)}}/></AppLayout>}
const Badge=({children}:{children:React.ReactNode})=><span className="rounded-full bg-white/80 px-4 py-2 text-amber-900">{children}</span>;const Box=({title,children}:{title:string;children:React.ReactNode})=><section className="rounded-3xl border border-amber-100 bg-white p-6 shadow-md sm:p-8"><h2 className="mb-4 text-2xl font-black">{title}</h2>{children}</section>;function List({title,items,warning}:{title:string;items:string[];warning?:boolean}){return <Box title={title}><ul className="space-y-3">{items.map(x=><li key={x} className={`rounded-2xl p-4 ${warning?"bg-rose-50":"bg-purple-50"}`}>{warning&&<TriangleAlert className="mr-2 inline text-rose-600" size={18}/>}• {x}</li>)}</ul></Box>}
