export const certificationRoadmapStages = [
  { id: "understand", title: "Understand the certification", guidance: "Read the provider outline and write down the skills and evidence expected." },
  { id: "fundamentals", title: "Learn fundamentals", guidance: "Close foundation gaps before moving to exam-style tasks." },
  { id: "studios", title: "Complete relevant DataBloom Studios", guidance: "Finish the recommended lessons and keep notes on weak topics." },
  { id: "projects", title: "Build practice projects", guidance: "Use the skills in a small, explainable portfolio project." },
  { id: "mock-tests", title: "Take mock tests", guidance: "Practise under realistic constraints and review every mistake." },
  { id: "revision", title: "Final revision", guidance: "Revisit weak areas, formulas, commands, and key workflows." },
  { id: "readiness", title: "Exam readiness", guidance: "Confirm the official requirements and schedule only when your checklist is complete." },
] as const;

export type CertificationDifficulty = "Beginner" | "Intermediate" | "Advanced";

export type CertificationDefinition = {
  id: string;
  name: string;
  provider: string;
  skillArea: string;
  difficulty: CertificationDifficulty;
  preparationLevel: "Light foundation" | "Moderate preparation" | "Deep preparation";
  summary: string;
  whoFor: string;
  prerequisites: string[];
  skills: string[];
  studios: string[];
  studioLinks: Array<{ label: string; href: string }>;
  projects: string[];
  practiceChecklist: string[];
  officialLink: string;
  beginnerFriendly?: boolean;
  freeOption?: boolean;
};

function defineCertification(value: CertificationDefinition) {
  return value;
}

export const certificationCatalog: CertificationDefinition[] = [
  defineCertification({
    id: "microsoft-power-bi-data-analyst",
    name: "Microsoft Power BI Data Analyst",
    provider: "Microsoft",
    skillArea: "Power BI",
    difficulty: "Intermediate",
    preparationLevel: "Moderate preparation",
    summary: "A role-focused credential path for preparing, modelling, visualising, and analysing data with Power BI.",
    whoFor: "Analysts who already understand tabular data and want structured Power BI validation.",
    prerequisites: ["Basic data analysis", "Comfort with tables and relationships", "Introductory Power BI practice"],
    skills: ["Power Query", "Data modelling", "DAX", "Report design", "Analysis and governance"],
    studios: ["Power BI Studio", "Power Query Studio", "Dashboard Studio"],
    studioLinks: [{ label: "Power BI Studio", href: "/power-bi-studio" }, { label: "Power Query Studio", href: "/power-query-studio" }, { label: "Dashboard Studio", href: "/dashboard" }],
    projects: ["Executive KPI dashboard", "Sales model with reusable measures", "Data-cleaning and refresh workflow"],
    practiceChecklist: ["Build a star schema", "Write and explain core DAX measures", "Create an accessible multi-page report"],
    officialLink: "https://learn.microsoft.com/credentials/certifications/power-bi-data-analyst-associate/",
  }),
  defineCertification({
    id: "microsoft-excel-associate",
    name: "Microsoft Excel Associate pathway",
    provider: "Microsoft",
    skillArea: "Excel",
    difficulty: "Beginner",
    preparationLevel: "Moderate preparation",
    summary: "A practical Excel credential pathway centred on worksheets, tables, formulas, charts, and workbook organisation.",
    whoFor: "Learners building dependable spreadsheet skills for analyst and operations roles.",
    prerequisites: ["Everyday spreadsheet navigation", "Basic formulas"],
    skills: ["Workbook management", "Tables", "Formulas", "Charts", "Data presentation"],
    studios: ["Formula Studio", "Dashboard Studio"],
    studioLinks: [{ label: "Formula Studio", href: "/formula-studio" }, { label: "Dashboard Studio", href: "/dashboard" }],
    projects: ["Clean monthly reporting workbook", "Formula-based sales tracker"],
    practiceChecklist: ["Format and organise a workbook", "Use lookup and conditional formulas", "Create a clear chart summary"],
    officialLink: "https://learn.microsoft.com/credentials/",
    beginnerFriendly: true,
  }),
  defineCertification({
    id: "microsoft-excel-expert",
    name: "Microsoft Excel Expert pathway",
    provider: "Microsoft",
    skillArea: "Excel",
    difficulty: "Advanced",
    preparationLevel: "Deep preparation",
    summary: "An advanced Excel pathway for complex workbook logic, analysis, automation, and professional reporting.",
    whoFor: "Experienced Excel users who can solve unfamiliar spreadsheet problems without step-by-step guidance.",
    prerequisites: ["Strong Excel fundamentals", "Confident formula use", "Experience building multi-sheet workbooks"],
    skills: ["Advanced formulas", "Data validation", "Workbook controls", "Advanced charts", "Automation concepts"],
    studios: ["Formula Studio", "Power Query Studio", "Dashboard Studio"],
    studioLinks: [{ label: "Formula Studio", href: "/formula-studio" }, { label: "Power Query Studio", href: "/power-query-studio" }, { label: "Dashboard Studio", href: "/dashboard" }],
    projects: ["Scenario planning workbook", "Automated management report"],
    practiceChecklist: ["Audit a complex workbook", "Build robust error-handled formulas", "Design a reusable reporting model"],
    officialLink: "https://learn.microsoft.com/credentials/",
  }),
  defineCertification({
    id: "microsoft-azure-data-fundamentals",
    name: "Microsoft Azure Data Fundamentals",
    provider: "Microsoft",
    skillArea: "Data fundamentals",
    difficulty: "Beginner",
    preparationLevel: "Light foundation",
    summary: "A foundation-level path covering relational, non-relational, analytics, and cloud data concepts.",
    whoFor: "Beginners who want cloud data vocabulary before choosing a specialist path.",
    prerequisites: ["General interest in data", "No production cloud experience required for preparation"],
    skills: ["Relational data", "Non-relational data", "Analytics workloads", "Cloud data services"],
    studios: ["SQL Studio", "Business Analytics Studio"],
    studioLinks: [{ label: "SQL Studio", href: "/sql-studio" }, { label: "Business Analytics Studio", href: "/business-analytics-studio" }],
    projects: ["Cloud data service comparison", "Simple relational data model"],
    practiceChecklist: ["Explain relational versus non-relational data", "Match workloads to data patterns", "Describe a basic analytics flow"],
    officialLink: "https://learn.microsoft.com/credentials/certifications/azure-data-fundamentals/",
    beginnerFriendly: true,
  }),
  defineCertification({
    id: "google-data-analytics",
    name: "Google Data Analytics",
    provider: "Google",
    skillArea: "Data analytics",
    difficulty: "Beginner",
    preparationLevel: "Moderate preparation",
    summary: "A broad learning pathway covering the analyst workflow from asking questions through cleaning, analysis, visualisation, and communication.",
    whoFor: "Career starters looking for a guided, project-oriented introduction to analytics.",
    prerequisites: ["No specialist background", "Basic computer and spreadsheet comfort"],
    skills: ["Analytical thinking", "Spreadsheets", "SQL", "Data cleaning", "Visualisation", "Case studies"],
    studios: ["Formula Studio", "SQL Studio", "Tableau Studio", "Business Analytics Studio"],
    studioLinks: [{ label: "Formula Studio", href: "/formula-studio" }, { label: "SQL Studio", href: "/sql-studio" }, { label: "Tableau Studio", href: "/tableau-studio" }, { label: "Business Analytics Studio", href: "/business-analytics-studio" }],
    projects: ["End-to-end stakeholder case study", "Clean and analyse a public dataset"],
    practiceChecklist: ["Write a clear business question", "Document a cleaning process", "Present an evidence-based recommendation"],
    officialLink: "https://www.coursera.org/professional-certificates/google-data-analytics",
    beginnerFriendly: true,
  }),
  defineCertification({
    id: "google-advanced-data-analytics",
    name: "Google Advanced Data Analytics",
    provider: "Google",
    skillArea: "Python and statistics",
    difficulty: "Advanced",
    preparationLevel: "Deep preparation",
    summary: "An advanced pathway focused on Python, statistics, regression, machine-learning foundations, and communicating analytical results.",
    whoFor: "Analysts with foundations who want deeper quantitative and Python-based practice.",
    prerequisites: ["Foundational analytics", "Basic spreadsheets and SQL", "Comfort learning Python"],
    skills: ["Python", "Statistics", "Regression", "Machine-learning foundations", "Experimental thinking"],
    studios: ["Python Studio", "Statistics Studio", "Business Analytics Studio"],
    studioLinks: [{ label: "Python Studio", href: "/python-studio" }, { label: "Statistics Studio", href: "/statistics-studio" }, { label: "Business Analytics Studio", href: "/business-analytics-studio" }],
    projects: ["Regression-based business analysis", "Exploratory Python notebook", "Experiment results brief"],
    practiceChecklist: ["Explain model assumptions", "Evaluate model performance", "Translate findings for a non-technical audience"],
    officialLink: "https://www.coursera.org/professional-certificates/google-advanced-data-analytics",
  }),
  defineCertification({
    id: "ibm-data-analyst",
    name: "IBM Data Analyst",
    provider: "IBM",
    skillArea: "Data analytics",
    difficulty: "Beginner",
    preparationLevel: "Moderate preparation",
    summary: "A multi-tool analyst pathway spanning spreadsheets, SQL, Python, visualisation, and portfolio work.",
    whoFor: "Beginners who want guided exposure to several common analyst tools.",
    prerequisites: ["No specialist background", "Willingness to practise across multiple tools"],
    skills: ["Excel", "SQL", "Python", "Data visualisation", "Dashboarding"],
    studios: ["Formula Studio", "SQL Studio", "Python Studio", "Dashboard Studio"],
    studioLinks: [{ label: "Formula Studio", href: "/formula-studio" }, { label: "SQL Studio", href: "/sql-studio" }, { label: "Python Studio", href: "/python-studio" }, { label: "Dashboard Studio", href: "/dashboard" }],
    projects: ["Analyst capstone", "Python exploratory analysis", "Interactive dashboard"],
    practiceChecklist: ["Query a relational dataset", "Create a reproducible analysis", "Present a portfolio-ready result"],
    officialLink: "https://www.coursera.org/professional-certificates/ibm-data-analyst",
    beginnerFriendly: true,
  }),
  defineCertification({
    id: "ibm-data-science",
    name: "IBM Data Science",
    provider: "IBM",
    skillArea: "Data science",
    difficulty: "Intermediate",
    preparationLevel: "Deep preparation",
    summary: "A broad data-science pathway covering Python, SQL, analysis, visualisation, and machine-learning foundations.",
    whoFor: "Learners moving from analyst foundations toward data-science workflows.",
    prerequisites: ["Basic data literacy", "Comfort with sustained Python practice"],
    skills: ["Python", "SQL", "Data analysis", "Visualisation", "Machine learning"],
    studios: ["Python Studio", "SQL Studio", "Statistics Studio"],
    studioLinks: [{ label: "Python Studio", href: "/python-studio" }, { label: "SQL Studio", href: "/sql-studio" }, { label: "Statistics Studio", href: "/statistics-studio" }],
    projects: ["Predictive modelling notebook", "SQL-to-Python analysis pipeline"],
    practiceChecklist: ["Prepare data reproducibly", "Compare baseline models", "Explain limitations and next steps"],
    officialLink: "https://www.coursera.org/professional-certificates/ibm-data-science",
  }),
  defineCertification({
    id: "tableau-desktop-specialist",
    name: "Tableau Desktop Specialist",
    provider: "Tableau",
    skillArea: "Tableau",
    difficulty: "Beginner",
    preparationLevel: "Moderate preparation",
    summary: "A foundational Tableau credential path focused on connecting data, exploring it, and building clear views and dashboards.",
    whoFor: "Analysts who use Tableau and want to validate core desktop workflows.",
    prerequisites: ["Basic data concepts", "Hands-on Tableau practice"],
    skills: ["Data connections", "Calculations", "Charts", "Dashboards", "Analytics features"],
    studios: ["Tableau Studio", "Dashboard Studio"],
    studioLinks: [{ label: "Tableau Studio", href: "/tableau-studio" }, { label: "Dashboard Studio", href: "/dashboard" }],
    projects: ["Interactive sales dashboard", "Exploratory visual story"],
    practiceChecklist: ["Choose appropriate chart types", "Build calculations and filters", "Publish a coherent dashboard flow"],
    officialLink: "https://www.tableau.com/learn/certification",
    beginnerFriendly: true,
  }),
  defineCertification({
    id: "tableau-certified-data-analyst",
    name: "Tableau Certified Data Analyst",
    provider: "Tableau",
    skillArea: "Tableau",
    difficulty: "Intermediate",
    preparationLevel: "Deep preparation",
    summary: "A broader analyst path covering data preparation, exploration, analysis, and delivery in Tableau.",
    whoFor: "Practising Tableau analysts comfortable solving end-to-end analysis tasks.",
    prerequisites: ["Strong Tableau foundations", "Experience building dashboards from imperfect data"],
    skills: ["Data preparation", "Data modelling", "Advanced analysis", "Dashboard design", "Publishing"],
    studios: ["Tableau Studio", "Statistics Studio", "Dashboard Studio"],
    studioLinks: [{ label: "Tableau Studio", href: "/tableau-studio" }, { label: "Statistics Studio", href: "/statistics-studio" }, { label: "Dashboard Studio", href: "/dashboard" }],
    projects: ["Multi-source Tableau dashboard", "Statistical insight story"],
    practiceChecklist: ["Blend or relate multiple tables", "Use table calculations confidently", "Defend dashboard design decisions"],
    officialLink: "https://www.tableau.com/learn/certification",
  }),
  defineCertification({
    id: "aws-cloud-practitioner",
    name: "AWS Certified Cloud Practitioner pathway",
    provider: "AWS",
    skillArea: "Cloud fundamentals",
    difficulty: "Beginner",
    preparationLevel: "Light foundation",
    summary: "A foundation path for cloud concepts, AWS services, security, architecture, and cloud economics vocabulary.",
    whoFor: "Learners who need cloud literacy before specialising in data services.",
    prerequisites: ["General technology awareness"],
    skills: ["Cloud concepts", "Core services", "Security basics", "Architecture vocabulary", "Cloud operations"],
    studios: ["Business Analytics Studio", "SQL Studio"],
    studioLinks: [{ label: "Business Analytics Studio", href: "/business-analytics-studio" }, { label: "SQL Studio", href: "/sql-studio" }],
    projects: ["Cloud service decision matrix", "Simple analytics architecture diagram"],
    practiceChecklist: ["Explain shared responsibility", "Recognise common data services", "Compare basic cloud workload patterns"],
    officialLink: "https://aws.amazon.com/certification/certified-cloud-practitioner/",
    beginnerFriendly: true,
  }),
  defineCertification({
    id: "aws-data-learning-path",
    name: "AWS data analytics learning paths",
    provider: "AWS",
    skillArea: "Cloud data",
    difficulty: "Intermediate",
    preparationLevel: "Deep preparation",
    summary: "Role-based learning paths for building knowledge of storage, processing, analytics, governance, and data workloads on AWS.",
    whoFor: "Analysts and engineers exploring AWS data services before choosing a current certification target.",
    prerequisites: ["Cloud fundamentals", "SQL and data modelling basics"],
    skills: ["Data lakes", "Warehousing", "Processing", "Analytics services", "Governance"],
    studios: ["SQL Studio", "Power Query Studio", "Business Analytics Studio"],
    studioLinks: [{ label: "SQL Studio", href: "/sql-studio" }, { label: "Power Query Studio", href: "/power-query-studio" }, { label: "Business Analytics Studio", href: "/business-analytics-studio" }],
    projects: ["Batch analytics architecture", "Cloud data pipeline design"],
    practiceChecklist: ["Map an analytics workload", "Choose storage and processing patterns", "Explain security and governance needs"],
    officialLink: "https://aws.amazon.com/training/learn-about/data-analytics/",
  }),
  defineCertification({
    id: "databricks-data-analyst",
    name: "Databricks Data Analyst pathway",
    provider: "Databricks",
    skillArea: "Lakehouse analytics",
    difficulty: "Intermediate",
    preparationLevel: "Deep preparation",
    summary: "A preparation path for SQL analytics, lakehouse concepts, dashboards, and working with data on the Databricks platform.",
    whoFor: "SQL-capable analysts moving into lakehouse analytics.",
    prerequisites: ["Confident SQL", "Data warehousing concepts"],
    skills: ["Databricks SQL", "Lakehouse concepts", "Queries", "Dashboards", "Data management"],
    studios: ["SQL Studio", "Dashboard Studio", "Business Analytics Studio"],
    studioLinks: [{ label: "SQL Studio", href: "/sql-studio" }, { label: "Dashboard Studio", href: "/dashboard" }, { label: "Business Analytics Studio", href: "/business-analytics-studio" }],
    projects: ["SQL warehouse analysis", "Lakehouse dashboard prototype"],
    practiceChecklist: ["Write analytical SQL", "Explain lakehouse concepts", "Build and interpret a dashboard"],
    officialLink: "https://www.databricks.com/learn/certification",
  }),
  defineCertification({
    id: "snowflake-certifications",
    name: "Snowflake certification pathways",
    provider: "Snowflake",
    skillArea: "Cloud data platform",
    difficulty: "Intermediate",
    preparationLevel: "Deep preparation",
    summary: "A family of role-based pathways covering Snowflake platform concepts, data workloads, performance, and governance.",
    whoFor: "Data practitioners using or preparing to use Snowflake in analytics workflows.",
    prerequisites: ["SQL fundamentals", "Data warehouse concepts", "Cloud data vocabulary"],
    skills: ["Snowflake architecture", "SQL workloads", "Performance", "Security", "Data sharing"],
    studios: ["SQL Studio", "Power Query Studio", "Business Analytics Studio"],
    studioLinks: [{ label: "SQL Studio", href: "/sql-studio" }, { label: "Power Query Studio", href: "/power-query-studio" }, { label: "Business Analytics Studio", href: "/business-analytics-studio" }],
    projects: ["Warehouse workload design", "Secure analytics sharing plan"],
    practiceChecklist: ["Explain Snowflake architecture", "Optimise an analytical query", "Describe access and sharing controls"],
    officialLink: "https://learn.snowflake.com/en/certifications/",
  }),
  defineCertification({
    id: "oracle-sql-certifications",
    name: "Oracle SQL certification pathways",
    provider: "Oracle",
    skillArea: "SQL and databases",
    difficulty: "Intermediate",
    preparationLevel: "Deep preparation",
    summary: "Database credential pathways focused on SQL querying, relational concepts, and Oracle database skills.",
    whoFor: "Learners targeting roles or organisations that use Oracle database technologies.",
    prerequisites: ["Relational database fundamentals", "Regular SQL practice"],
    skills: ["SQL queries", "Joins", "Functions", "Data definition", "Database concepts"],
    studios: ["SQL Studio", "Practice Lab"],
    studioLinks: [{ label: "SQL Studio", href: "/sql-studio" }, { label: "Practice Lab", href: "/practice-lab" }],
    projects: ["Relational reporting database", "SQL analysis question set"],
    practiceChecklist: ["Write joins without prompts", "Use grouping and subqueries", "Explain data-definition choices"],
    officialLink: "https://education.oracle.com/oracle-certification-path/pFamily_48",
  }),
  defineCertification({
    id: "meta-database-engineer",
    name: "Meta Database Engineer learning path",
    provider: "Meta",
    skillArea: "Databases",
    difficulty: "Intermediate",
    preparationLevel: "Deep preparation",
    summary: "A guided pathway covering databases, SQL, Python, version control, and database-backed application concepts.",
    whoFor: "Learners who want to deepen database skills beyond analyst-only querying.",
    prerequisites: ["Basic programming interest", "SQL foundations"],
    skills: ["SQL", "Database design", "Python", "Version control", "Database applications"],
    studios: ["SQL Studio", "Python Studio"],
    studioLinks: [{ label: "SQL Studio", href: "/sql-studio" }, { label: "Python Studio", href: "/python-studio" }],
    projects: ["Normalised database design", "Python database reporting tool"],
    practiceChecklist: ["Model related entities", "Write reliable CRUD queries", "Connect a Python workflow to structured data"],
    officialLink: "https://www.coursera.org/professional-certificates/meta-database-engineer",
  }),
  defineCertification({
    id: "coursera-data-certificate-pathways",
    name: "Coursera data certificate pathways",
    provider: "Coursera",
    skillArea: "Multi-skill pathways",
    difficulty: "Beginner",
    preparationLevel: "Moderate preparation",
    summary: "A discovery entry for comparing provider-authored data certificates by role, tool, and project emphasis.",
    whoFor: "Learners comparing structured online certificate pathways before committing to one.",
    prerequisites: ["Define a target role", "Compare syllabus and project evidence"],
    skills: ["Pathway comparison", "Role alignment", "Project planning", "Self-paced learning"],
    studios: ["Career Hub", "Smart Notes", "Practice Lab"],
    studioLinks: [{ label: "Career Hub", href: "/career-hub" }, { label: "Smart Notes", href: "/smart-notes" }, { label: "Practice Lab", href: "/practice-lab" }],
    projects: ["Certificate decision matrix", "Role-aligned learning plan"],
    practiceChecklist: ["Compare learning outcomes", "Check project requirements", "Choose one role-aligned pathway"],
    officialLink: "https://www.coursera.org/browse/data-science",
    beginnerFriendly: true,
  }),
  defineCertification({
    id: "edx-data-certificate-pathways",
    name: "edX data certificate pathways",
    provider: "edX",
    skillArea: "Multi-skill pathways",
    difficulty: "Beginner",
    preparationLevel: "Moderate preparation",
    summary: "A discovery entry for university and organisation-backed data programmes covering analytics, statistics, programming, and related fields.",
    whoFor: "Independent learners comparing structured academic and professional pathways.",
    prerequisites: ["Define a learning objective", "Review each programme syllabus"],
    skills: ["Programme comparison", "Analytics foundations", "Statistics", "Programming"],
    studios: ["Statistics Studio", "Python Studio", "Career Hub"],
    studioLinks: [{ label: "Statistics Studio", href: "/statistics-studio" }, { label: "Python Studio", href: "/python-studio" }, { label: "Career Hub", href: "/career-hub" }],
    projects: ["Programme comparison brief", "Personal preparation plan"],
    practiceChecklist: ["Map outcomes to your target role", "Review prerequisites", "Identify portfolio evidence to build"],
    officialLink: "https://www.edx.org/learn/data-analysis",
    beginnerFriendly: true,
  }),
  defineCertification({
    id: "free-beginner-data-pathways",
    name: "Free beginner-friendly data learning options",
    provider: "Multiple providers",
    skillArea: "Foundations",
    difficulty: "Beginner",
    preparationLevel: "Light foundation",
    summary: "A planning entry for free learning and completion-badge options that can build foundations before a paid or exam-based credential.",
    whoFor: "Beginners who want to test a skill path before spending money or choosing an exam.",
    prerequisites: ["No specialist background", "A consistent practice routine"],
    skills: ["Data literacy", "Spreadsheets", "SQL foundations", "Portfolio habits"],
    studios: ["Formula Studio", "SQL Studio", "Practice Lab", "Smart Notes"],
    studioLinks: [{ label: "Formula Studio", href: "/formula-studio" }, { label: "SQL Studio", href: "/sql-studio" }, { label: "Practice Lab", href: "/practice-lab" }, { label: "Smart Notes", href: "/smart-notes" }],
    projects: ["Beginner dataset analysis", "Learning evidence log"],
    practiceChecklist: ["Complete a foundation module", "Build one small project", "Write a skills reflection"],
    officialLink: "https://learn.microsoft.com/training/",
    beginnerFriendly: true,
    freeOption: true,
  }),
];

export const certificationProviders = Array.from(new Set(certificationCatalog.map((item) => item.provider))).sort();
export const certificationSkillAreas = Array.from(new Set(certificationCatalog.map((item) => item.skillArea))).sort();

export function getCertificationDefinition(id: string) {
  return certificationCatalog.find((item) => item.id === id);
}
