export const excelToolkitCategories = [
  "Keyboard Shortcuts",
  "Excel Tricks",
  "Formula Alternatives",
  "Productivity Tips",
  "Analyst Secrets",
] as const;

export const excelToolkitDifficulties = [
  "Beginner",
  "Intermediate",
  "Advanced",
] as const;

export type ExcelToolkitCategory = (typeof excelToolkitCategories)[number];
export type ExcelToolkitDifficulty = (typeof excelToolkitDifficulties)[number];

type ExcelToolkitBase = {
  id: string;
  title: string;
  category: ExcelToolkitCategory;
  difficulty: ExcelToolkitDifficulty;
  definition?: string;
};

export type ExcelShortcutGroup =
  | "Navigation"
  | "Selection"
  | "Editing"
  | "Formatting"
  | "Formulas"
  | "Tables and filters"
  | "Workbook management";

export const excelShortcutGroups: ExcelShortcutGroup[] = [
  "Navigation",
  "Selection",
  "Editing",
  "Formatting",
  "Formulas",
  "Tables and filters",
  "Workbook management",
];

export type ExcelShortcut = ExcelToolkitBase & {
  kind: "shortcut";
  group: ExcelShortcutGroup;
  windows: string;
  mac: string;
  explanation: string;
  example?: string;
};

export type ExcelTrick = ExcelToolkitBase & {
  kind: "trick";
  whatItDoes: string;
  whenToUse: string;
  steps: string[];
  example: string;
  commonMistake: string;
};

export type FormulaAlternative = ExcelToolkitBase & {
  kind: "comparison";
  traditionalMethod: string;
  modernAlternative: string;
  traditionalFormula: string;
  alternativeFormula: string;
  useTraditionalWhen: string;
  useAlternativeWhen: string;
  compatibility: string;
  performance: string;
  commonMistake: string;
};

export type ProductivityTip = ExcelToolkitBase & {
  kind: "productivity";
  summary: string;
  actions: string[];
  example: string;
};

export type AnalystSecret = ExcelToolkitBase & {
  kind: "analyst-secret";
  practice: string;
  whyItMatters: string;
  action: string;
};

export type ExcelToolkitItem =
  | ExcelShortcut
  | ExcelTrick
  | FormulaAlternative
  | ProductivityTip
  | AnalystSecret;

export const excelShortcuts: ExcelShortcut[] = [
  {
    id: "shortcut-jump-data-edge",
    kind: "shortcut",
    title: "Jump to the edge of a data region",
    category: "Keyboard Shortcuts",
    difficulty: "Beginner",
    group: "Navigation",
    windows: "Ctrl + Arrow key",
    mac: "⌘ + Arrow key",
    explanation: "Moves to the next boundary of the current populated region.",
    example: "Jump from the first sales row to the last populated sales row.",
  },
  {
    id: "shortcut-first-cell",
    kind: "shortcut",
    title: "Go to the first cell",
    category: "Keyboard Shortcuts",
    difficulty: "Beginner",
    group: "Navigation",
    windows: "Ctrl + Home",
    mac: "Control + Home (or Control + Fn + ←)",
    explanation: "Moves the active cell to the beginning of the worksheet.",
  },
  {
    id: "shortcut-last-used-cell",
    kind: "shortcut",
    title: "Go to the last used cell",
    category: "Keyboard Shortcuts",
    difficulty: "Intermediate",
    group: "Navigation",
    windows: "Ctrl + End",
    mac: "Control + End (or Control + Fn + →)",
    explanation: "Moves to the worksheet's last used cell.",
    example: "Quickly inspect whether formatting has expanded the used range.",
  },
  {
    id: "shortcut-go-to",
    kind: "shortcut",
    title: "Open Go To",
    category: "Keyboard Shortcuts",
    difficulty: "Beginner",
    group: "Navigation",
    windows: "F5 or Ctrl + G",
    mac: "Control + G",
    explanation: "Opens Go To so you can navigate to a cell, range, or named range.",
  },
  {
    id: "shortcut-extend-data-edge",
    kind: "shortcut",
    title: "Select to the data boundary",
    category: "Keyboard Shortcuts",
    difficulty: "Beginner",
    group: "Selection",
    windows: "Ctrl + Shift + Arrow key",
    mac: "⌘ + Shift + Arrow key",
    explanation: "Extends the selection to the next populated-region boundary.",
  },
  {
    id: "shortcut-select-region",
    kind: "shortcut",
    title: "Select the current region",
    category: "Keyboard Shortcuts",
    difficulty: "Beginner",
    group: "Selection",
    windows: "Ctrl + A",
    mac: "⌘ + A",
    explanation: "Selects the current data region; repeat when needed to select the sheet.",
  },
  {
    id: "shortcut-select-row",
    kind: "shortcut",
    title: "Select the entire row",
    category: "Keyboard Shortcuts",
    difficulty: "Beginner",
    group: "Selection",
    windows: "Shift + Space",
    mac: "Shift + Space",
    explanation: "Selects the whole row containing the active cell.",
  },
  {
    id: "shortcut-select-column",
    kind: "shortcut",
    title: "Select the entire column",
    category: "Keyboard Shortcuts",
    difficulty: "Beginner",
    group: "Selection",
    windows: "Ctrl + Space",
    mac: "Control + Space",
    explanation: "Selects the whole column containing the active cell.",
  },
  {
    id: "shortcut-edit-cell",
    kind: "shortcut",
    title: "Edit the active cell",
    category: "Keyboard Shortcuts",
    difficulty: "Beginner",
    group: "Editing",
    windows: "F2",
    mac: "Control + U",
    explanation: "Places the insertion point in the active cell for editing.",
  },
  {
    id: "shortcut-fill-down",
    kind: "shortcut",
    title: "Fill down",
    category: "Keyboard Shortcuts",
    difficulty: "Beginner",
    group: "Editing",
    windows: "Ctrl + D",
    mac: "⌘ + D",
    explanation: "Copies the top cell of a selection into the cells below.",
  },
  {
    id: "shortcut-fill-right",
    kind: "shortcut",
    title: "Fill right",
    category: "Keyboard Shortcuts",
    difficulty: "Beginner",
    group: "Editing",
    windows: "Ctrl + R",
    mac: "⌘ + R",
    explanation: "Copies the leftmost cell of a selection into cells to the right.",
  },
  {
    id: "shortcut-fill-selection",
    kind: "shortcut",
    title: "Enter into every selected cell",
    category: "Keyboard Shortcuts",
    difficulty: "Intermediate",
    group: "Editing",
    windows: "Ctrl + Enter",
    mac: "Control + Return",
    explanation: "Commits the same value or formula to all selected cells.",
  },
  {
    id: "shortcut-format-cells",
    kind: "shortcut",
    title: "Open Format Cells",
    category: "Keyboard Shortcuts",
    difficulty: "Beginner",
    group: "Formatting",
    windows: "Ctrl + 1",
    mac: "⌘ + 1",
    explanation: "Opens detailed number, alignment, font, border, fill, and protection options.",
  },
  {
    id: "shortcut-bold",
    kind: "shortcut",
    title: "Toggle bold",
    category: "Keyboard Shortcuts",
    difficulty: "Beginner",
    group: "Formatting",
    windows: "Ctrl + B",
    mac: "⌘ + B",
    explanation: "Applies or removes bold formatting.",
  },
  {
    id: "shortcut-currency-format",
    kind: "shortcut",
    title: "Apply currency format",
    category: "Keyboard Shortcuts",
    difficulty: "Intermediate",
    group: "Formatting",
    windows: "Ctrl + Shift + $",
    mac: "Control + Shift + $",
    explanation: "Applies a currency number format using the current locale.",
  },
  {
    id: "shortcut-percent-format",
    kind: "shortcut",
    title: "Apply percentage format",
    category: "Keyboard Shortcuts",
    difficulty: "Intermediate",
    group: "Formatting",
    windows: "Ctrl + Shift + %",
    mac: "Control + Shift + %",
    explanation: "Applies percentage formatting to the selected cells.",
  },
  {
    id: "shortcut-autosum",
    kind: "shortcut",
    title: "Insert AutoSum",
    category: "Keyboard Shortcuts",
    difficulty: "Beginner",
    group: "Formulas",
    windows: "Alt + =",
    mac: "⌘ + Shift + T",
    explanation: "Inserts a SUM formula for the nearest likely numeric range.",
    example: "Create a total beneath a monthly revenue column.",
  },
  {
    id: "shortcut-toggle-reference",
    kind: "shortcut",
    title: "Cycle reference types",
    category: "Keyboard Shortcuts",
    difficulty: "Intermediate",
    group: "Formulas",
    windows: "F4",
    mac: "⌘ + T",
    explanation: "Cycles a selected formula reference through relative, absolute, and mixed forms.",
  },
  {
    id: "shortcut-show-formulas",
    kind: "shortcut",
    title: "Show or hide formulas",
    category: "Keyboard Shortcuts",
    difficulty: "Intermediate",
    group: "Formulas",
    windows: "Ctrl + `",
    mac: "Control + `",
    explanation: "Toggles the worksheet between displayed results and displayed formulas.",
  },
  {
    id: "shortcut-insert-function",
    kind: "shortcut",
    title: "Open Insert Function",
    category: "Keyboard Shortcuts",
    difficulty: "Beginner",
    group: "Formulas",
    windows: "Shift + F3",
    mac: "Shift + F3 (use Fn on some keyboards)",
    explanation: "Opens the Insert Function dialog for guided function selection.",
  },
  {
    id: "shortcut-create-table",
    kind: "shortcut",
    title: "Create an Excel Table",
    category: "Keyboard Shortcuts",
    difficulty: "Beginner",
    group: "Tables and filters",
    windows: "Ctrl + T",
    mac: "Control + T",
    explanation: "Converts the selected data range into an Excel Table.",
  },
  {
    id: "shortcut-toggle-filter",
    kind: "shortcut",
    title: "Toggle filters",
    category: "Keyboard Shortcuts",
    difficulty: "Intermediate",
    group: "Tables and filters",
    windows: "Ctrl + Shift + L",
    mac: "Control + Shift + L",
    explanation: "Adds or removes AutoFilter controls for the current range.",
  },
  {
    id: "shortcut-open-filter",
    kind: "shortcut",
    title: "Open a filter menu",
    category: "Keyboard Shortcuts",
    difficulty: "Intermediate",
    group: "Tables and filters",
    windows: "Alt + Down Arrow",
    mac: "Option + Down Arrow",
    explanation: "Opens the active column's filter or data-validation menu.",
  },
  {
    id: "shortcut-current-date",
    kind: "shortcut",
    title: "Insert the current date",
    category: "Keyboard Shortcuts",
    difficulty: "Beginner",
    group: "Tables and filters",
    windows: "Ctrl + ;",
    mac: "Control + ;",
    explanation: "Inserts today's date as a fixed value rather than a volatile formula.",
  },
  {
    id: "shortcut-save-workbook",
    kind: "shortcut",
    title: "Save the workbook",
    category: "Keyboard Shortcuts",
    difficulty: "Beginner",
    group: "Workbook management",
    windows: "Ctrl + S",
    mac: "⌘ + S",
    explanation: "Saves changes to the active workbook.",
  },
  {
    id: "shortcut-next-sheet",
    kind: "shortcut",
    title: "Move to the next worksheet",
    category: "Keyboard Shortcuts",
    difficulty: "Intermediate",
    group: "Workbook management",
    windows: "Ctrl + Page Down",
    mac: "Option + Right Arrow",
    explanation: "Activates the next worksheet tab.",
  },
  {
    id: "shortcut-previous-sheet",
    kind: "shortcut",
    title: "Move to the previous worksheet",
    category: "Keyboard Shortcuts",
    difficulty: "Intermediate",
    group: "Workbook management",
    windows: "Ctrl + Page Up",
    mac: "Option + Left Arrow",
    explanation: "Activates the previous worksheet tab.",
  },
  {
    id: "shortcut-new-sheet",
    kind: "shortcut",
    title: "Insert a new worksheet",
    category: "Keyboard Shortcuts",
    difficulty: "Beginner",
    group: "Workbook management",
    windows: "Shift + F11",
    mac: "Shift + F11 (use Fn on some keyboards)",
    explanation: "Adds a new worksheet to the active workbook.",
  },
];

export const excelTricks: ExcelTrick[] = [
  {
    id: "trick-flash-fill",
    kind: "trick",
    title: "Flash Fill",
    category: "Excel Tricks",
    difficulty: "Beginner",
    whatItDoes: "Detects a text pattern from examples and fills the remaining rows.",
    whenToUse: "Quick one-off splitting, joining, or reformatting when the pattern is consistent.",
    steps: ["Type the desired result beside the first source value.", "Start the next result.", "Choose Data > Flash Fill or press Ctrl + E on Windows."],
    example: "Turn “Asha Mehta” into “Asha” after supplying one first-name example.",
    commonMistake: "Trusting the pattern without checking exceptions; Flash Fill creates values, not a refreshable transformation.",
  },
  {
    id: "trick-go-to-special",
    kind: "trick",
    title: "Go To Special",
    category: "Excel Tricks",
    difficulty: "Intermediate",
    whatItDoes: "Selects cells by type, including blanks, formulas, constants, or visible cells.",
    whenToUse: "Auditing a large range or applying one edit to a specific cell type.",
    steps: ["Select the relevant range.", "Open Find & Select > Go To Special.", "Choose the required cell type and confirm."],
    example: "Select every blank in an import column before filling a standard value.",
    commonMistake: "Running it on the whole sheet when only one data region should change.",
  },
  {
    id: "trick-paste-values",
    kind: "trick",
    title: "Paste Values Only",
    category: "Excel Tricks",
    difficulty: "Beginner",
    whatItDoes: "Pastes calculated results without the source formulas or formatting.",
    whenToUse: "Freezing a result, sharing outputs, or removing formula dependencies.",
    steps: ["Copy the source cells.", "Select the destination.", "Use Paste Special > Values."],
    example: "Replace temporary lookup formulas with approved static outputs.",
    commonMistake: "Overwriting the only copy of a formula before preserving an auditable source.",
  },
  {
    id: "trick-text-to-columns",
    kind: "trick",
    title: "Text to Columns",
    category: "Excel Tricks",
    difficulty: "Beginner",
    whatItDoes: "Splits one text column using delimiters or fixed positions.",
    whenToUse: "Separating predictable imported fields such as codes, names, or dates.",
    steps: ["Select the source column.", "Choose Data > Text to Columns.", "Select Delimited or Fixed Width, preview, and set the destination."],
    example: "Split “North|Retail|2026” into three columns using the pipe delimiter.",
    commonMistake: "Leaving adjacent destination cells occupied and overwriting their contents.",
  },
  {
    id: "trick-remove-duplicates",
    kind: "trick",
    title: "Remove Duplicates",
    category: "Excel Tricks",
    difficulty: "Beginner",
    whatItDoes: "Permanently removes repeated rows based on selected columns.",
    whenToUse: "Cleaning a copied dataset when one retained occurrence is acceptable.",
    steps: ["Keep a backup or work on a copy.", "Select the table or range.", "Choose Data > Remove Duplicates and select the identifying columns."],
    example: "Keep one row per customer ID in a staging copy.",
    commonMistake: "Selecting too few columns and deleting records that are not true duplicates.",
  },
  {
    id: "trick-freeze-panes",
    kind: "trick",
    title: "Freeze Panes",
    category: "Excel Tricks",
    difficulty: "Beginner",
    whatItDoes: "Keeps chosen rows and columns visible while you scroll.",
    whenToUse: "Reviewing long or wide datasets with headers or identifiers.",
    steps: ["Select the cell below and to the right of what should remain visible.", "Choose View > Freeze Panes.", "Test vertical and horizontal scrolling."],
    example: "Select B2 to keep row 1 and column A visible.",
    commonMistake: "Selecting the header itself instead of the first scrolling cell.",
  },
  {
    id: "trick-quick-analysis",
    kind: "trick",
    title: "Quick Analysis",
    category: "Excel Tricks",
    difficulty: "Beginner",
    whatItDoes: "Offers contextual formatting, chart, total, table, and sparkline options.",
    whenToUse: "Exploring a small clean range before choosing a final presentation.",
    steps: ["Select a populated range.", "Open the Quick Analysis button.", "Preview an option before applying it."],
    example: "Preview a column chart and row totals for a monthly sales table.",
    commonMistake: "Accepting the first suggested chart without checking whether it answers the business question.",
  },
  {
    id: "trick-range-to-table",
    kind: "trick",
    title: "Convert a Range to a Table",
    category: "Excel Tricks",
    difficulty: "Beginner",
    whatItDoes: "Creates a structured, expandable Excel Table with filters and references.",
    whenToUse: "Most repeatable datasets that will grow, filter, calculate, or feed reports.",
    steps: ["Select a cell in the data.", "Press Ctrl + T on Windows or Control + T on Mac.", "Confirm the range and whether headers exist."],
    example: "Turn monthly transactions into a table named SalesData.",
    commonMistake: "Including totals, blank separator rows, or report titles inside the table.",
  },
  {
    id: "trick-fill-handle",
    kind: "trick",
    title: "Fill Handle",
    category: "Excel Tricks",
    difficulty: "Beginner",
    whatItDoes: "Copies formulas or continues recognizable sequences.",
    whenToUse: "Extending consistent formulas, dates, numbers, or labels.",
    steps: ["Select the source cell or pattern.", "Drag or double-click the lower-right fill handle.", "Inspect relative references in the filled cells."],
    example: "Extend a margin formula down a contiguous transaction table.",
    commonMistake: "Copying a reference that should have been absolute or mixed.",
  },
  {
    id: "trick-visible-cells",
    kind: "trick",
    title: "Select Visible Cells Only",
    category: "Excel Tricks",
    difficulty: "Intermediate",
    whatItDoes: "Restricts an edit or copy to cells that remain visible after filtering or hiding.",
    whenToUse: "Copying filtered results or editing only visible records.",
    steps: ["Select the filtered range.", "Use Go To Special > Visible cells only.", "Copy or edit the resulting selection."],
    example: "Copy only the currently filtered region to a review sheet.",
    commonMistake: "Pasting into a differently filtered range and assuming row alignment is preserved.",
  },
  {
    id: "trick-named-ranges",
    kind: "trick",
    title: "Named Ranges",
    category: "Excel Tricks",
    difficulty: "Intermediate",
    whatItDoes: "Assigns a meaningful name to a cell, range, formula, or constant.",
    whenToUse: "Clarifying important assumptions and stable model inputs.",
    steps: ["Select the cell or range.", "Enter a valid name in the Name Box or use Formulas > Define Name.", "Use the name in a formula."],
    example: "=Revenue*(1-TaxRate)",
    commonMistake: "Using unclear names or names that silently refer to the wrong workbook scope.",
  },
  {
    id: "trick-transpose",
    kind: "trick",
    title: "Transpose Rows and Columns",
    category: "Excel Tricks",
    difficulty: "Intermediate",
    whatItDoes: "Rotates copied rows into columns or columns into rows.",
    whenToUse: "Reshaping a small static layout for presentation or analysis.",
    steps: ["Copy the source range.", "Select an empty destination.", "Use Paste Special > Transpose."],
    example: "Turn month headers across columns into a vertical list.",
    commonMistake: "Using paste transpose when a refreshable Power Query unpivot would be more maintainable.",
  },
];

export const formulaAlternatives: FormulaAlternative[] = [
  {
    id: "alternative-vlookup-xlookup",
    kind: "comparison",
    title: "VLOOKUP vs XLOOKUP",
    category: "Formula Alternatives",
    difficulty: "Intermediate",
    traditionalMethod: "VLOOKUP",
    modernAlternative: "XLOOKUP",
    traditionalFormula: '=VLOOKUP(E2,$A$2:$C$100,3,FALSE)',
    alternativeFormula: '=XLOOKUP(E2,$A$2:$A$100,$C$2:$C$100,"Not found")',
    useTraditionalWhen: "The workbook must work in Excel 2016 or 2019, or an established model already uses stable VLOOKUP formulas.",
    useAlternativeWhen: "You need an explicit return range, left lookup, built-in not-found result, or safer column changes.",
    compatibility: "XLOOKUP is available in newer Excel releases, but not Excel 2016 or Excel 2019.",
    performance: "Both can be efficient on bounded ranges. Avoid unnecessary full-column lookups in large models.",
    commonMistake: "Omitting FALSE in VLOOKUP and accidentally accepting an approximate match.",
  },
  {
    id: "alternative-vlookup-index-match",
    kind: "comparison",
    title: "VLOOKUP vs INDEX + MATCH",
    category: "Formula Alternatives",
    difficulty: "Intermediate",
    traditionalMethod: "VLOOKUP",
    modernAlternative: "INDEX + MATCH",
    traditionalFormula: '=VLOOKUP(E2,$A$2:$C$100,3,FALSE)',
    alternativeFormula: '=INDEX($C$2:$C$100,MATCH(E2,$A$2:$A$100,0))',
    useTraditionalWhen: "A simple rightward lookup in a legacy-compatible workbook is easiest to maintain.",
    useAlternativeWhen: "You need left lookups, separate lookup and return ranges, or compatibility without XLOOKUP.",
    compatibility: "Both work in longstanding desktop Excel versions.",
    performance: "On repeated lookups, calculate MATCH once and reuse it when practical.",
    commonMistake: "Using ranges with different starting rows or lengths.",
  },
  {
    id: "alternative-concatenate-textjoin",
    kind: "comparison",
    title: "CONCATENATE vs TEXTJOIN",
    category: "Formula Alternatives",
    difficulty: "Beginner",
    traditionalMethod: "CONCATENATE or &",
    modernAlternative: "TEXTJOIN",
    traditionalFormula: '=CONCATENATE(A2,", ",B2,", ",C2)',
    alternativeFormula: '=TEXTJOIN(", ",TRUE,A2:C2)',
    useTraditionalWhen: "You are joining a few known values or supporting older Excel versions.",
    useAlternativeWhen: "You need one delimiter across a range and want to ignore empty cells.",
    compatibility: "TEXTJOIN is available in modern Excel versions; the & operator has broader legacy compatibility.",
    performance: "For small joins the difference is negligible; TEXTJOIN reduces formula length for ranges.",
    commonMistake: "Setting ignore_empty to FALSE and creating repeated delimiters around blanks.",
  },
  {
    id: "alternative-if-ifs",
    kind: "comparison",
    title: "Nested IF vs IFS",
    category: "Formula Alternatives",
    difficulty: "Intermediate",
    traditionalMethod: "Nested IF",
    modernAlternative: "IFS",
    traditionalFormula: '=IF(B2>=90,"A",IF(B2>=75,"B",IF(B2>=60,"C","D")))',
    alternativeFormula: '=IFS(B2>=90,"A",B2>=75,"B",B2>=60,"C",TRUE,"D")',
    useTraditionalWhen: "You need broad compatibility or only one or two branches.",
    useAlternativeWhen: "Several ordered conditions are easier to read as condition/result pairs.",
    compatibility: "IFS requires a modern Excel version; nested IF works in older versions.",
    performance: "Keep the number of repeated tests reasonable and consider a lookup table for large grading bands.",
    commonMistake: "Putting broad conditions before narrower ones so later tests never run.",
  },
  {
    id: "alternative-if-switch",
    kind: "comparison",
    title: "Nested IF vs SWITCH",
    category: "Formula Alternatives",
    difficulty: "Intermediate",
    traditionalMethod: "Nested IF",
    modernAlternative: "SWITCH",
    traditionalFormula: '=IF(A2="N","North",IF(A2="S","South","Other"))',
    alternativeFormula: '=SWITCH(A2,"N","North","S","South","Other")',
    useTraditionalWhen: "Tests use ranges or different logical expressions rather than one repeated value.",
    useAlternativeWhen: "One expression is compared against several exact values.",
    compatibility: "SWITCH requires a modern Excel version; nested IF has broader legacy support.",
    performance: "Choose clarity first for small mappings; use a lookup table for long maintained code lists.",
    commonMistake: "Using SWITCH for inequalities without designing an appropriate expression.",
  },
  {
    id: "alternative-remove-duplicates-unique",
    kind: "comparison",
    title: "Remove Duplicates vs UNIQUE",
    category: "Formula Alternatives",
    difficulty: "Intermediate",
    traditionalMethod: "Remove Duplicates",
    modernAlternative: "UNIQUE",
    traditionalFormula: "Data > Remove Duplicates",
    alternativeFormula: "=UNIQUE(A2:A100)",
    useTraditionalWhen: "You intentionally want to delete duplicate rows from a controlled copy.",
    useAlternativeWhen: "You want a dynamic, non-destructive list that updates with the source.",
    compatibility: "UNIQUE requires dynamic-array Excel; Remove Duplicates is available in older desktop versions.",
    performance: "Use bounded source ranges or Tables rather than entire columns in large workbooks.",
    commonMistake: "Treating Remove Duplicates as reversible after saving and closing without a backup.",
  },
  {
    id: "alternative-advanced-filter-filter",
    kind: "comparison",
    title: "Advanced Filter vs FILTER",
    category: "Formula Alternatives",
    difficulty: "Advanced",
    traditionalMethod: "Advanced Filter",
    modernAlternative: "FILTER",
    traditionalFormula: "Data > Advanced; criteria range H1:H2",
    alternativeFormula: '=FILTER(A2:D100,D2:D100="Open","No rows")',
    useTraditionalWhen: "A legacy workbook needs a manual filtered copy or complex criteria-range workflow.",
    useAlternativeWhen: "A live spill range should update automatically from formula criteria.",
    compatibility: "FILTER requires dynamic-array Excel; Advanced Filter supports older desktop versions.",
    performance: "Avoid oversized array inputs and repeated identical FILTER calculations.",
    commonMistake: "Blocking the spill area beneath a FILTER formula.",
  },
  {
    id: "alternative-iserror-iferror",
    kind: "comparison",
    title: "IF(ISERROR()) vs IFERROR",
    category: "Formula Alternatives",
    difficulty: "Beginner",
    traditionalMethod: "IF with ISERROR",
    modernAlternative: "IFERROR",
    traditionalFormula: '=IF(ISERROR(A2/B2),"Check input",A2/B2)',
    alternativeFormula: '=IFERROR(A2/B2,"Check input")',
    useTraditionalWhen: "You need older compatibility or different logic around a specific error test.",
    useAlternativeWhen: "The same expression would otherwise be calculated twice.",
    compatibility: "IFERROR is supported by modern and many longstanding Excel desktop versions.",
    performance: "IFERROR avoids repeating a costly expression, but preventing expected errors is often better.",
    commonMistake: "Hiding genuine data-quality problems behind an empty-string error result.",
  },
  {
    id: "alternative-sumproduct-sumifs",
    kind: "comparison",
    title: "SUMPRODUCT vs SUMIFS",
    category: "Formula Alternatives",
    difficulty: "Advanced",
    traditionalMethod: "SUMPRODUCT",
    modernAlternative: "SUMIFS",
    traditionalFormula: '=SUMPRODUCT((A2:A100="East")*(B2:B100="Open")*C2:C100)',
    alternativeFormula: '=SUMIFS(C2:C100,A2:A100,"East",B2:B100,"Open")',
    useTraditionalWhen: "You need array-style conditions or calculations that SUMIFS cannot express directly.",
    useAlternativeWhen: "You are summing a range with straightforward criteria.",
    compatibility: "Both are broadly supported in desktop Excel.",
    performance: "SUMIFS is often more efficient for simple criteria; always keep SUMPRODUCT ranges bounded.",
    commonMistake: "Using full-column arrays in SUMPRODUCT and slowing a large workbook.",
  },
  {
    id: "alternative-offset-index",
    kind: "comparison",
    title: "OFFSET vs INDEX",
    category: "Formula Alternatives",
    difficulty: "Advanced",
    traditionalMethod: "OFFSET",
    modernAlternative: "INDEX-based reference",
    traditionalFormula: "=SUM(OFFSET(B2,0,0,COUNTA(B:B)-1,1))",
    alternativeFormula: "=SUM(B2:INDEX(B:B,COUNTA(B:B)))",
    useTraditionalWhen: "A model genuinely needs a readable shifted reference and recalculation cost is acceptable.",
    useAlternativeWhen: "You need a non-volatile range endpoint for a maintained model.",
    compatibility: "Both are broadly supported in desktop Excel.",
    performance: "OFFSET is volatile and recalculates frequently; INDEX is generally preferable in large calculation chains.",
    commonMistake: "Building a dynamic range that includes headers, blanks, or the formula cell itself.",
  },
  {
    id: "alternative-formulas-power-query",
    kind: "comparison",
    title: "Cleaning Formulas vs Power Query",
    category: "Formula Alternatives",
    difficulty: "Advanced",
    traditionalMethod: "Repeated worksheet cleaning formulas",
    modernAlternative: "Power Query transformation steps",
    traditionalFormula: '=TRIM(CLEAN(SUBSTITUTE(A2,CHAR(160)," ")))',
    alternativeFormula: "Power Query: Clean, Trim, Replace Values, set data type",
    useTraditionalWhen: "The transformation is small, transparent, and needs immediate cell-level feedback.",
    useAlternativeWhen: "The same multi-step import and cleaning process must refresh reliably.",
    compatibility: "Power Query availability and features vary by Excel platform and version; worksheet formulas remain more portable.",
    performance: "Power Query can move repeated preparation out of the calculation grid, but refresh design still matters.",
    commonMistake: "Using Power Query for a tiny one-off edit or formulas for a complex recurring import without documenting either.",
  },
];

export const productivityTips: ProductivityTip[] = [
  {
    id: "productivity-clean-messy-data",
    kind: "productivity",
    title: "Profile messy data before cleaning",
    category: "Productivity Tips",
    difficulty: "Intermediate",
    summary: "Inspect blanks, duplicates, types, and unexpected categories before changing values.",
    actions: ["Preserve a raw copy.", "Turn on filters.", "Check counts, lengths, and distinct values.", "Choose formulas or Power Query based on repeatability."],
    example: "Count blank customer IDs and inspect unique region labels before standardizing them.",
  },
  {
    id: "productivity-select-blanks",
    kind: "productivity",
    title: "Select blanks safely",
    category: "Productivity Tips",
    difficulty: "Beginner",
    summary: "Use Go To Special within a bounded range to work with missing cells.",
    actions: ["Select only the relevant data column.", "Choose Go To Special > Blanks.", "Enter or format carefully.", "Validate whether formulas returning empty text were included."],
    example: "Fill a default status only where imported status cells are genuinely blank.",
  },
  {
    id: "productivity-find-formulas",
    kind: "productivity",
    title: "Find and audit formulas",
    category: "Productivity Tips",
    difficulty: "Intermediate",
    summary: "Locate calculated cells before editing a model or pasting new data.",
    actions: ["Use Go To Special > Formulas.", "Toggle Show Formulas.", "Trace precedents for important outputs.", "Compare formulas across rows."],
    example: "Confirm a margin column uses one consistent formula before refreshing a report.",
  },
  {
    id: "productivity-keyboard-workflow",
    kind: "productivity",
    title: "Build a keyboard-first workflow",
    category: "Productivity Tips",
    difficulty: "Intermediate",
    summary: "Combine navigation, selection, and editing shortcuts to reduce repeated mouse travel.",
    actions: ["Jump with Ctrl/⌘ + Arrow.", "Select with Shift added.", "Edit with F2 or Control + U.", "Commit repeated entries with Ctrl + Enter or Control + Return."],
    example: "Jump to a table edge, select the next block, and fill one validated formula without leaving the keyboard.",
  },
  {
    id: "productivity-quick-chart",
    kind: "productivity",
    title: "Create charts quickly, then refine",
    category: "Productivity Tips",
    difficulty: "Beginner",
    summary: "Start with a clean summary range and use Excel's quick chart entry points.",
    actions: ["Select labels and measures only.", "Use Quick Analysis or Alt + F1 on Windows.", "Choose the chart that matches the comparison.", "Add a decision-focused title."],
    example: "Create a column chart from region and revenue, then sort the source summary descending.",
  },
  {
    id: "productivity-structure-data-reports",
    kind: "productivity",
    title: "Separate data from reports",
    category: "Productivity Tips",
    difficulty: "Beginner",
    summary: "Keep raw records tabular and place summaries or dashboards on separate sheets.",
    actions: ["Use one header row.", "Keep one record per row.", "Avoid totals inside raw data.", "Reference the Table from calculation and report sheets."],
    example: "Store transactions in SalesData and build pivots on a Report sheet.",
  },
  {
    id: "productivity-reduce-repetition",
    kind: "productivity",
    title: "Reduce repetitive work",
    category: "Productivity Tips",
    difficulty: "Intermediate",
    summary: "Replace recurring manual steps with Tables, reusable formulas, Power Query, or carefully governed automation.",
    actions: ["List the repeated steps.", "Standardize the input.", "Choose the lightest repeatable tool.", "Test the refresh on a copy."],
    example: "Replace monthly copy-paste cleaning with a query that imports and standardizes the same folder.",
  },
  {
    id: "productivity-large-files",
    kind: "productivity",
    title: "Work efficiently with large spreadsheets",
    category: "Productivity Tips",
    difficulty: "Advanced",
    summary: "Control calculation cost, range sizes, formats, and unnecessary workbook objects.",
    actions: ["Avoid full-column array calculations.", "Limit volatile functions.", "Remove unused formatting.", "Aggregate before charting.", "Check links and conditional-formatting scope."],
    example: "Change A:A array references to a bounded Table column and reuse one lookup result.",
  },
];

export const analystSecrets: AnalystSecret[] = [
  {
    id: "secret-layer-workbook",
    kind: "analyst-secret",
    title: "Separate raw data, calculations, and reports",
    category: "Analyst Secrets",
    difficulty: "Beginner",
    practice: "Use distinct layers or sheets for source data, transformation/calculation logic, and presentation.",
    whyItMatters: "Reviewers can trace inputs to outputs without report edits damaging the source.",
    action: "Name the layers consistently and document the flow on a Read Me sheet.",
  },
  {
    id: "secret-no-merged-data",
    kind: "analyst-secret",
    title: "Avoid merged cells in datasets",
    category: "Analyst Secrets",
    difficulty: "Beginner",
    practice: "Keep raw and calculation ranges rectangular with one value per field.",
    whyItMatters: "Merged cells interfere with sorting, filtering, importing, and programmatic processing.",
    action: "Use alignment or presentation sheets instead of merging source cells.",
  },
  {
    id: "secret-sheet-names",
    kind: "analyst-secret",
    title: "Use clear sheet names",
    category: "Analyst Secrets",
    difficulty: "Beginner",
    practice: "Name sheets for their role, such as Raw_Sales, Calc_Metrics, and Report_Exec.",
    whyItMatters: "Clear names reduce navigation errors and make formulas easier to review.",
    action: "Replace Sheet1-style names before sharing the workbook.",
  },
  {
    id: "secret-use-tables",
    kind: "analyst-secret",
    title: "Use Excel Tables",
    category: "Analyst Secrets",
    difficulty: "Beginner",
    practice: "Store repeatable datasets in named Tables with unique headers.",
    whyItMatters: "Tables expand, filter, and carry formulas more reliably than loose ranges.",
    action: "Give each Table a meaningful name and keep totals outside source data when appropriate.",
  },
  {
    id: "secret-limit-volatile",
    kind: "analyst-secret",
    title: "Avoid unnecessary volatile formulas",
    category: "Analyst Secrets",
    difficulty: "Advanced",
    practice: "Use volatile functions such as OFFSET and INDIRECT only when their behavior is genuinely needed.",
    whyItMatters: "They recalculate frequently and can slow large dependency chains.",
    action: "Prefer direct references, Tables, INDEX, or other non-volatile designs where they express the same logic.",
  },
  {
    id: "secret-document-assumptions",
    kind: "analyst-secret",
    title: "Document assumptions",
    category: "Analyst Secrets",
    difficulty: "Intermediate",
    practice: "Record definitions, date windows, exclusions, rates, and source limitations.",
    whyItMatters: "A correct formula can still produce a misleading answer when its assumptions are hidden.",
    action: "Create an assumptions block with owner, source, and last-reviewed date.",
  },
  {
    id: "secret-consistent-formulas",
    kind: "analyst-secret",
    title: "Keep formulas consistent",
    category: "Analyst Secrets",
    difficulty: "Intermediate",
    practice: "Use the same formula pattern down a calculated column unless a documented exception exists.",
    whyItMatters: "One-off overrides are difficult to detect and maintain.",
    action: "Compare formulas, use Table calculated columns, and flag intentional exceptions.",
  },
  {
    id: "secret-maintainable-workbooks",
    kind: "analyst-secret",
    title: "Build maintainable workbooks",
    category: "Analyst Secrets",
    difficulty: "Intermediate",
    practice: "Prefer understandable stages, bounded inputs, named objects, and visible checks over clever single-cell formulas.",
    whyItMatters: "Future users need to update and validate the model without reverse-engineering it.",
    action: "Add a short Read Me with purpose, refresh steps, owners, and dependencies.",
  },
  {
    id: "secret-check-totals-errors",
    kind: "analyst-secret",
    title: "Check totals and errors",
    category: "Analyst Secrets",
    difficulty: "Intermediate",
    practice: "Add reconciliation totals, row counts, error counts, and reasonableness checks.",
    whyItMatters: "Visible controls catch incomplete imports and broken logic before a report is shared.",
    action: "Compare key totals to a trusted source and investigate every unexplained variance.",
  },
  {
    id: "secret-optimize-files",
    kind: "analyst-secret",
    title: "Optimize large files deliberately",
    category: "Analyst Secrets",
    difficulty: "Advanced",
    practice: "Measure the cost of formulas, links, formatting, queries, pivots, and charts before optimizing.",
    whyItMatters: "Guessing can remove useful functionality without addressing the true bottleneck.",
    action: "Reduce oversized ranges, duplicate calculations, unused styles, and unnecessary volatile logic first.",
  },
];

const excelToolkitDefinitions: Record<string, string> = {
  "shortcut-jump-data-edge": "A keyboard shortcut that moves to the next edge of a contiguous data region.",
  "shortcut-first-cell": "A shortcut that returns the selection to the first cell of a worksheet.",
  "shortcut-last-used-cell": "A shortcut that jumps to the last cell Excel considers used on a sheet.",
  "shortcut-go-to": "Go To opens a box for navigating directly to a cell, range, or named object.",
  "shortcut-extend-data-edge": "A selection shortcut that extends the current selection to the edge of a data region.",
  "shortcut-select-region": "Select Current Region selects the contiguous block surrounding the active cell.",
  "shortcut-select-row": "A row-selection shortcut selects every cell across the active worksheet row.",
  "shortcut-select-column": "A column-selection shortcut selects every cell down the active worksheet column.",
  "shortcut-edit-cell": "Edit Cell activates the current cell so its existing value or formula can be changed.",
  "shortcut-fill-down": "Fill Down copies the top cell's value or formula into the selected cells below it.",
  "shortcut-fill-right": "Fill Right copies the leftmost selected cell into cells to its right.",
  "shortcut-fill-selection": "Enter into Every Selected Cell writes the same entry to all selected cells at once.",
  "shortcut-format-cells": "Format Cells opens Excel's dialog for number, alignment, border, fill, and protection settings.",
  "shortcut-bold": "The Bold shortcut toggles heavier font formatting on the selected cells.",
  "shortcut-currency-format": "Currency formatting displays numeric values with a currency symbol and monetary decimals.",
  "shortcut-percent-format": "Percentage formatting displays a decimal value as a percentage with a percent sign.",
  "shortcut-autosum": "AutoSum inserts a SUM formula that proposes a nearby range to total.",
  "shortcut-toggle-reference": "Reference toggling cycles a formula reference between relative, absolute, and mixed forms.",
  "shortcut-show-formulas": "Show Formulas switches a worksheet between displayed results and the formulas behind them.",
  "shortcut-insert-function": "Insert Function opens Excel's function browser and argument helper.",
  "shortcut-create-table": "Create Table converts a range into a structured Excel Table with headers and filters.",
  "shortcut-toggle-filter": "Toggle Filters adds or removes filter controls for a tabular range or table.",
  "shortcut-open-filter": "Open Filter Menu opens the selected column's sorting and filtering choices.",
  "shortcut-current-date": "The current-date shortcut inserts today's date as a worksheet value.",
  "shortcut-save-workbook": "The Save shortcut writes the current workbook changes to its file.",
  "shortcut-next-sheet": "Next Sheet moves the active view to the worksheet tab after the current one.",
  "shortcut-previous-sheet": "Previous Sheet moves the active view to the worksheet tab before the current one.",
  "shortcut-new-sheet": "New Sheet inserts another worksheet into the current workbook.",
  "trick-flash-fill": "Flash Fill detects a pattern in examples and fills neighboring values without a formula.",
  "trick-go-to-special": "Go To Special selects cells with a shared property such as blanks, formulas, or constants.",
  "trick-paste-values": "Paste Values Only copies displayed results without bringing formulas or source formatting.",
  "trick-text-to-columns": "Text to Columns splits one column into multiple columns using delimiters or fixed positions.",
  "trick-remove-duplicates": "Remove Duplicates deletes repeated rows according to the columns selected as the comparison key.",
  "trick-freeze-panes": "Freeze Panes keeps chosen rows or columns visible while the worksheet scrolls.",
  "trick-quick-analysis": "Quick Analysis is a contextual tool for applying common totals, formatting, charts, or tables to a selection.",
  "trick-range-to-table": "Convert Range to Table gives a plain cell range structured references, filters, and automatic expansion.",
  "trick-fill-handle": "The fill handle is the small drag control that copies patterns, formulas, or series into adjacent cells.",
  "trick-visible-cells": "Select Visible Cells Only excludes hidden or filtered-out cells from a copied selection.",
  "trick-named-ranges": "A named range assigns a readable name to a cell or range for easier formulas and navigation.",
  "trick-transpose": "Transpose changes a copied range from rows to columns or from columns to rows.",
  "alternative-vlookup-xlookup": "VLOOKUP searches the first column of a table, while XLOOKUP supports flexible lookup and return ranges.",
  "alternative-vlookup-index-match": "VLOOKUP uses a table-column position, while INDEX with MATCH separates the return range from the lookup.",
  "alternative-concatenate-textjoin": "CONCATENATE joins values, while TEXTJOIN joins values with a delimiter and can ignore empty cells.",
  "alternative-if-ifs": "Nested IF tests conditions one level at a time, while IFS expresses an ordered list of condition-result pairs.",
  "alternative-if-switch": "Nested IF evaluates conditions, while SWITCH compares one expression with several exact cases.",
  "alternative-remove-duplicates-unique": "Remove Duplicates changes a range in place, while UNIQUE returns a dynamic array of distinct values.",
  "alternative-advanced-filter-filter": "Advanced Filter extracts criteria-based rows, while FILTER returns a formula-driven dynamic array.",
  "alternative-iserror-iferror": "IF(ISERROR()) tests an expression separately, while IFERROR supplies a fallback around the expression directly.",
  "alternative-sumproduct-sumifs": "SUMPRODUCT combines arrays arithmetically, while SUMIFS adds one range using explicit criteria ranges.",
  "alternative-offset-index": "OFFSET returns a movable reference, while INDEX returns a value or reference without volatile recalculation.",
  "alternative-formulas-power-query": "Cleaning formulas transform cells in place, while Power Query creates repeatable refreshable preparation steps.",
  "productivity-clean-messy-data": "Profiling messy data is the practice of inspecting structure, nulls, types, duplicates, and anomalies before cleaning.",
  "productivity-select-blanks": "Selecting blanks safely isolates empty cells without accidentally overwriting populated or formula-driven cells.",
  "productivity-find-formulas": "Formula auditing locates formulas, constants, references, and errors so workbook logic can be reviewed.",
  "productivity-keyboard-workflow": "A keyboard-first workflow uses consistent shortcuts to reduce mouse movement and repetitive spreadsheet actions.",
  "productivity-quick-chart": "Quick chart creation turns a selected range into an initial visualization that can then be refined.",
  "productivity-structure-data-reports": "Separating data from reports keeps source tables, calculations, and presentation layers maintainable.",
  "productivity-reduce-repetition": "Reducing repetition replaces repeated manual steps with tables, formulas, queries, or reusable workflows.",
  "productivity-large-files": "Large-file efficiency means controlling calculation ranges, formats, links, queries, and objects that slow a workbook.",
  "secret-layer-workbook": "Workbook layering separates raw inputs, calculations, and report outputs into understandable stages.",
  "secret-no-merged-data": "Avoiding merged cells in datasets preserves a rectangular structure that filters, formulas, and imports can use.",
  "secret-sheet-names": "Clear sheet names describe a worksheet's role so formulas, navigation, and handoffs are easier to understand.",
  "secret-use-tables": "An Excel Table is a structured, expanding data range with headers, filters, and structured references.",
  "secret-limit-volatile": "Limiting volatile formulas reduces unnecessary recalculation whenever any workbook value changes.",
  "secret-document-assumptions": "Documenting assumptions records definitions, exclusions, rates, time windows, sources, and ownership behind a model.",
  "secret-consistent-formulas": "Consistent formulas apply the same logic across a calculated region unless a documented exception is intentional.",
  "secret-maintainable-workbooks": "A maintainable workbook uses understandable stages, bounded inputs, named objects, visible checks, and documented dependencies.",
  "secret-check-totals-errors": "Reconciliation checks compare totals, row counts, errors, and reasonableness against a trusted expectation.",
  "secret-optimize-files": "Deliberate file optimization measures the real bottleneck before reducing formulas, ranges, links, styles, or queries.",
};

export const excelProToolkitItems: ExcelToolkitItem[] = [
  ...excelShortcuts,
  ...excelTricks,
  ...formulaAlternatives,
  ...productivityTips,
  ...analystSecrets,
].map((item) => ({ ...item, definition: excelToolkitDefinitions[item.id] }));

export function getExcelToolkitSearchValues(item: ExcelToolkitItem) {
  const common = [item.title, item.category, item.difficulty];
  switch (item.kind) {
    case "shortcut":
      return [
        ...common,
        item.group,
        item.windows,
        item.mac,
        item.explanation,
        item.example ?? "",
      ];
    case "trick":
      return [
        ...common,
        item.whatItDoes,
        item.whenToUse,
        item.example,
        item.commonMistake,
        ...item.steps,
      ];
    case "comparison":
      return [
        ...common,
        item.traditionalMethod,
        item.modernAlternative,
        item.traditionalFormula,
        item.alternativeFormula,
        item.useTraditionalWhen,
        item.useAlternativeWhen,
        item.compatibility,
        item.performance,
        item.commonMistake,
      ];
    case "productivity":
      return [...common, item.summary, item.example, ...item.actions];
    case "analyst-secret":
      return [
        ...common,
        item.practice,
        item.whyItMatters,
        item.action,
      ];
  }
}
