import { getDatasetLibraryItem } from "@/lib/datasetLibrary";

export const portfolioProjectCategories = [
  "Beginner",
  "Intermediate",
  "Advanced",
  "Real World",
] as const;

export const portfolioProjectDifficulties = [
  "Beginner",
  "Intermediate",
  "Advanced",
] as const;

export type PortfolioProjectCategory =
  (typeof portfolioProjectCategories)[number];
export type PortfolioProjectDifficulty =
  (typeof portfolioProjectDifficulties)[number];

export type PortfolioProjectBadge = {
  icon: string;
  title: string;
};

export type PortfolioProjectDataset = {
  libraryId: string;
  usage: string;
  focusFields: string[];
};

export type PortfolioProject = {
  id: string;
  title: string;
  icon: string;
  category: PortfolioProjectCategory;
  difficulty: PortfolioProjectDifficulty;
  estimatedTime: string;
  businessScenario: string;
  backgroundStory: string;
  learningObjectives: string[];
  skillsRequired: string[];
  dataset: PortfolioProjectDataset;
  guidedHints?: string[];
  solutionWalkthrough: string[];
  reflectionQuestions: string[];
  xpReward: number;
  achievementBadge: PortfolioProjectBadge;
  portfolioDescription: string;
  resumeBullet: string;
  interviewQuestions: string[];
};

type PortfolioProjectSeed = Omit<
  PortfolioProject,
  | "learningObjectives"
  | "guidedHints"
  | "solutionWalkthrough"
  | "reflectionQuestions"
  | "interviewQuestions"
> & {
  audience: string;
  metricFocus: string[];
  deliverable: string;
  decision: string;
  risk: string;
  extraHint?: string;
};

function createProject(seed: PortfolioProjectSeed): PortfolioProject {
  const dataset = getDatasetLibraryItem(seed.dataset.libraryId);
  const datasetName = dataset?.name ?? "the linked practice dataset";
  const metrics = seed.metricFocus.join(", ");

  return {
    id: seed.id,
    title: seed.title,
    icon: seed.icon,
    category: seed.category,
    difficulty: seed.difficulty,
    estimatedTime: seed.estimatedTime,
    businessScenario: seed.businessScenario,
    backgroundStory: seed.backgroundStory,
    skillsRequired: seed.skillsRequired,
    dataset: seed.dataset,
    xpReward: seed.xpReward,
    achievementBadge: seed.achievementBadge,
    portfolioDescription: seed.portfolioDescription,
    resumeBullet: seed.resumeBullet,
    learningObjectives: [
      `Validate ${datasetName} before analysis and document material data-quality decisions.`,
      `Calculate and explain ${metrics} with reproducible logic.`,
      `Build ${seed.deliverable} for ${seed.audience} and connect every visual to a decision.`,
      `Communicate a recommendation while acknowledging ${seed.risk}.`,
    ],
    guidedHints: [
      `Start with row counts, duplicates, blanks, data types, and the ${seed.dataset.focusFields.join(", ")} fields.`,
      `Define ${metrics} before building visuals so labels and totals remain consistent.`,
      `Use one overview, one diagnostic comparison, and one exception view before adding detail.`,
      ...(seed.extraHint ? [seed.extraHint] : []),
    ],
    solutionWalkthrough: [
      `Open ${datasetName} from the Dataset Library and preserve an unchanged source copy.`,
      `Profile ${seed.dataset.focusFields.join(", ")} and record any cleaning or exclusion rules.`,
      `Create clearly named calculations for ${metrics}.`,
      `Compare results by the dimensions most relevant to ${seed.decision}.`,
      `Build ${seed.deliverable} with a headline summary, diagnostic view, and detailed evidence.`,
      `Reconcile totals to the cleaned source and test filters, edge cases, and missing values.`,
      `Write a short recommendation for ${seed.audience}, including the next action and a guardrail.`,
    ],
    reflectionQuestions: [
      `Which assumption had the greatest influence on your conclusion, and how did you validate it?`,
      `How did ${seed.risk} affect the analysis or the way you communicated results?`,
      `What would you change if the dataset were larger, refreshed regularly, or used for a live decision?`,
    ],
    interviewQuestions: [
      `Walk me through the business problem, your analytical approach, and the final recommendation in ${seed.title}.`,
      `Why did you choose ${metrics}, and what alternative metrics did you reject?`,
      `How did you validate the result and manage ${seed.risk}?`,
    ],
  };
}

const projectSeeds: PortfolioProjectSeed[] = [
  {
    id: "personal-finance-tracker",
    title: "Personal Finance Tracker",
    icon: "💰",
    category: "Beginner",
    difficulty: "Beginner",
    estimatedTime: "2–3 hours",
    businessScenario: "A young professional needs a monthly view of income, spending, savings, and categories that exceed plan.",
    backgroundStory: "Transactions arrive in a simple worksheet, but inconsistent categories make it difficult to understand where money goes.",
    skillsRequired: ["Excel Tables", "SUMIFS", "Data validation", "Basic charts"],
    dataset: {
      libraryId: "budget-variance",
      usage: "Adapt the finance records into a personal income and expense ledger.",
      focusFields: ["Date", "Product", "Amount", "Status"],
    },
    audience: "an individual budget owner",
    metricFocus: ["income", "expenses", "savings rate", "category variance"],
    deliverable: "a monthly finance tracker with category controls and trend charts",
    decision: "where spending should be adjusted next month",
    risk: "misclassified transactions and one-off expenses",
    xpReward: 75,
    achievementBadge: { icon: "🌱", title: "Finance Foundation" },
    portfolioDescription: "An Excel finance tracker that cleans transaction categories, compares actual spending with plan, and highlights monthly savings trends.",
    resumeBullet: "Built an Excel personal-finance tracker using Tables, SUMIFS, validation controls, and monthly variance charts to identify overspending categories.",
  },
  {
    id: "student-grade-manager",
    title: "Student Grade Manager",
    icon: "🎓",
    category: "Beginner",
    difficulty: "Beginner",
    estimatedTime: "2–3 hours",
    businessScenario: "A tutor needs one workbook to calculate weighted grades and identify students who may need support.",
    backgroundStory: "Assessment results are stored by course and term, but there is no consistent summary or quality check.",
    skillsRequired: ["IF", "AVERAGEIFS", "Weighted averages", "Conditional formatting"],
    dataset: {
      libraryId: "student-performance",
      usage: "Use anonymized education outcomes to create a weighted grade-management model.",
      focusFields: ["StudentID", "Course", "AssessmentScore", "FinalScore", "Outcome"],
    },
    audience: "an academic support tutor",
    metricFocus: ["weighted grade", "pass rate", "assessment gap", "support flag"],
    deliverable: "a protected grade manager with course and student summaries",
    decision: "which learners need timely academic support",
    risk: "treating a score as a complete explanation of student potential",
    xpReward: 75,
    achievementBadge: { icon: "📘", title: "Grade Guardian" },
    portfolioDescription: "A structured Excel grade manager with weighted calculations, validation checks, course summaries, and responsible support flags.",
    resumeBullet: "Created a weighted student-grade manager in Excel with automated pass logic, data validation, and course-level performance summaries.",
  },
  {
    id: "attendance-tracker",
    title: "Attendance Tracker",
    icon: "🗓️",
    category: "Beginner",
    difficulty: "Beginner",
    estimatedTime: "2 hours",
    businessScenario: "A program coordinator needs to monitor attendance and follow up before learners fall below an agreed threshold.",
    backgroundStory: "Attendance is recorded inconsistently and current reporting only shows a final percentage.",
    skillsRequired: ["COUNTIFS", "Dates", "Data validation", "Conditional formatting"],
    dataset: {
      libraryId: "student-performance",
      usage: "Use the attendance percentage and student dimensions to model a maintainable tracker.",
      focusFields: ["StudentID", "Course", "Term", "AttendancePct"],
    },
    audience: "a program coordinator",
    metricFocus: ["attendance rate", "missed sessions", "threshold status", "course trend"],
    deliverable: "an attendance tracker with clear follow-up flags",
    decision: "where supportive attendance outreach should begin",
    risk: "using attendance alone to label learners",
    xpReward: 70,
    achievementBadge: { icon: "✅", title: "Attendance Organizer" },
    portfolioDescription: "An Excel attendance tracker that calculates course-level attendance, highlights threshold exceptions, and supports timely follow-up.",
    resumeBullet: "Developed an Excel attendance tracker using COUNTIFS, date logic, and conditional formatting to flag students needing proactive support.",
  },
  {
    id: "expense-dashboard",
    title: "Expense Dashboard",
    icon: "📊",
    category: "Beginner",
    difficulty: "Beginner",
    estimatedTime: "3 hours",
    businessScenario: "A small team needs a simple dashboard showing monthly expense movement and categories driving variance.",
    backgroundStory: "Expense records exist, but leadership receives totals without context, trends, or owners.",
    skillsRequired: ["PivotTables", "SUMIFS", "Slicers", "Chart selection"],
    dataset: {
      libraryId: "budget-variance",
      usage: "Treat financial records as departmental expenses and plan-versus-actual observations.",
      focusFields: ["Date", "Customer", "Product", "Amount", "Status"],
    },
    audience: "a small-team manager",
    metricFocus: ["total expense", "monthly variance", "category share", "exception count"],
    deliverable: "an interactive expense dashboard with monthly and category views",
    decision: "which cost categories require review",
    risk: "comparing incomplete periods or inconsistent categories",
    xpReward: 80,
    achievementBadge: { icon: "📉", title: "Expense Explorer" },
    portfolioDescription: "An interactive Excel expense dashboard with PivotTables, slicers, variance logic, and exception-focused reporting.",
    resumeBullet: "Designed an Excel expense dashboard with PivotTables, slicers, and variance analysis to surface monthly cost drivers and exceptions.",
  },
  {
    id: "monthly-budget-planner",
    title: "Monthly Budget Planner",
    icon: "📒",
    category: "Beginner",
    difficulty: "Beginner",
    estimatedTime: "2–3 hours",
    businessScenario: "A household wants to plan spending limits and understand how actual results affect future savings goals.",
    backgroundStory: "The existing budget is a static list with no rollover, scenario, or variance logic.",
    skillsRequired: ["Excel Tables", "SUMIFS", "Absolute references", "Scenario inputs"],
    dataset: {
      libraryId: "budget-variance",
      usage: "Use the finance dataset as historical evidence for planning realistic monthly limits.",
      focusFields: ["Date", "Product", "Amount", "Rate", "Status"],
    },
    audience: "a household budget owner",
    metricFocus: ["planned spend", "actual spend", "variance", "projected savings"],
    deliverable: "a reusable budget planner with assumptions and monthly roll-forward",
    decision: "how to rebalance the next monthly plan",
    risk: "overconfident projections based on limited history",
    xpReward: 80,
    achievementBadge: { icon: "🧭", title: "Budget Planner" },
    portfolioDescription: "A reusable monthly budget planner with assumption controls, variance tracking, and savings projections.",
    resumeBullet: "Built a reusable Excel budget-planning model with scenario inputs, SUMIFS-based tracking, and monthly savings projections.",
  },
  {
    id: "retail-sales-analysis",
    title: "Retail Sales Analysis",
    icon: "🛍️",
    category: "Intermediate",
    difficulty: "Intermediate",
    estimatedTime: "5–7 hours",
    businessScenario: "A retail director needs to identify sales, margin, and fulfillment patterns before resetting territory targets.",
    backgroundStory: "Revenue is growing overall, but leaders do not know whether the growth is profitable or evenly distributed.",
    skillsRequired: ["Power Query", "PivotTables", "Profit margin", "Dashboard design"],
    dataset: {
      libraryId: "superstore-sales",
      usage: "Use the complete retail order dataset as the analytical source.",
      focusFields: ["OrderDate", "Region", "Category", "Revenue", "Cost", "Status"],
    },
    audience: "a retail director",
    metricFocus: ["revenue", "gross margin", "order count", "fulfillment rate"],
    deliverable: "a retail performance dashboard with region and category diagnostics",
    decision: "where to adjust territory and category priorities",
    risk: "confusing high revenue with profitable growth",
    xpReward: 120,
    achievementBadge: { icon: "🏬", title: "Retail Analyst" },
    portfolioDescription: "A retail performance case study linking revenue, margin, product mix, and fulfillment outcomes to territory decisions.",
    resumeBullet: "Analyzed retail sales and margin by region and category, building an interactive dashboard that identified growth and fulfillment priorities.",
  },
  {
    id: "restaurant-analytics",
    title: "Restaurant Analytics",
    icon: "🍽️",
    category: "Intermediate",
    difficulty: "Intermediate",
    estimatedTime: "5–6 hours",
    businessScenario: "A restaurant group wants to improve menu profitability without damaging customer choice or service quality.",
    backgroundStory: "Weekly sales reports list revenue, but menu mix, margin, and service outcomes are not connected.",
    skillsRequired: ["SUMIFS", "Pivot charts", "Menu engineering", "Business storytelling"],
    dataset: {
      libraryId: "restaurant-sales",
      usage: "Use restaurant orders to compare menu mix, margin, and service status.",
      focusFields: ["OrderDate", "Region", "Category", "Revenue", "Cost", "Status"],
    },
    audience: "a restaurant operations manager",
    metricFocus: ["revenue", "contribution margin", "menu mix", "service completion"],
    deliverable: "a menu and service analytics dashboard",
    decision: "which menu items and locations need pricing or operational review",
    risk: "recommending removals based on sales volume alone",
    xpReward: 115,
    achievementBadge: { icon: "👩‍🍳", title: "Menu Strategist" },
    portfolioDescription: "A restaurant analytics workbook connecting menu mix, contribution margin, location performance, and service outcomes.",
    resumeBullet: "Built a restaurant analytics dashboard to compare menu mix, contribution margin, and location performance for operational decisions.",
  },
  {
    id: "hr-analytics",
    title: "HR Analytics",
    icon: "👥",
    category: "Intermediate",
    difficulty: "Intermediate",
    estimatedTime: "6–8 hours",
    businessScenario: "People leaders need to understand attrition and engagement patterns while avoiding unfair causal claims.",
    backgroundStory: "Workforce metrics are available, but small groups, privacy, and correlation risks are not handled consistently.",
    skillsRequired: ["Power BI", "DAX", "Cohort comparison", "Ethical analysis"],
    dataset: {
      libraryId: "hr-attrition",
      usage: "Use anonymized employee records with privacy-aware aggregation.",
      focusFields: ["Department", "Role", "TenureYears", "EngagementScore", "Outcome"],
    },
    audience: "an HR leadership team",
    metricFocus: ["attrition rate", "engagement", "tenure mix", "cohort size"],
    deliverable: "a privacy-aware workforce dashboard with cohort guardrails",
    decision: "where leaders should investigate retention conditions",
    risk: "small-group disclosure and confusing correlation with causation",
    extraHint: "Suppress or combine groups that are too small for responsible interpretation.",
    xpReward: 130,
    achievementBadge: { icon: "🌿", title: "People Analytics Practitioner" },
    portfolioDescription: "A privacy-aware HR analytics case study examining attrition, engagement, tenure, and department patterns without causal overclaiming.",
    resumeBullet: "Developed a privacy-aware HR dashboard using DAX and cohort analysis to identify attrition patterns and responsible follow-up areas.",
  },
  {
    id: "customer-analytics",
    title: "Customer Analytics",
    icon: "🧩",
    category: "Intermediate",
    difficulty: "Intermediate",
    estimatedTime: "6–8 hours",
    businessScenario: "A subscription business needs actionable customer segments for retention and service planning.",
    backgroundStory: "Customers are grouped only by plan, masking differences in value, engagement, support use, and lifecycle outcome.",
    skillsRequired: ["Segmentation", "Churn metrics", "Cohort analysis", "Dashboard design"],
    dataset: {
      libraryId: "customer-churn",
      usage: "Use customer-level subscription behavior and lifecycle outcomes.",
      focusFields: ["Segment", "TenureMonths", "MonthlyValue", "EngagementScore", "Outcome"],
    },
    audience: "a customer-success leader",
    metricFocus: ["churn rate", "customer value", "engagement", "support intensity"],
    deliverable: "a customer segmentation and retention dashboard",
    decision: "which customer groups need different retention actions",
    risk: "turning descriptive segments into unsupported individual predictions",
    xpReward: 125,
    achievementBadge: { icon: "🤝", title: "Customer Insight Builder" },
    portfolioDescription: "A customer analytics project segmenting subscribers by value, engagement, support usage, and churn outcome.",
    resumeBullet: "Segmented subscription customers by value and engagement, creating a retention dashboard that prioritized customer-success actions.",
  },
  {
    id: "inventory-management",
    title: "Inventory Management",
    icon: "📦",
    category: "Intermediate",
    difficulty: "Intermediate",
    estimatedTime: "6–8 hours",
    businessScenario: "A retail planner must reduce stockouts while controlling excess inventory and working capital.",
    backgroundStory: "Stock levels are reviewed manually, and reorder decisions do not consistently reflect demand or unit cost.",
    skillsRequired: ["Power Query", "Inventory KPIs", "Conditional logic", "Exception reporting"],
    dataset: {
      libraryId: "retail-inventory",
      usage: "Use store-level inventory, demand, cost, and reorder thresholds.",
      focusFields: ["SKU", "Location", "OnHand", "ReorderPoint", "UnitCost", "MonthlyDemand"],
    },
    audience: "a retail inventory planner",
    metricFocus: ["stockout risk", "excess units", "inventory value", "reorder priority"],
    deliverable: "an exception-led inventory management dashboard",
    decision: "which SKUs and locations should be replenished or reduced",
    risk: "using average demand without accounting for seasonality or lead time",
    xpReward: 130,
    achievementBadge: { icon: "🏷️", title: "Inventory Controller" },
    portfolioDescription: "An inventory management dashboard prioritizing stockout risk, excess units, inventory value, and reorder actions.",
    resumeBullet: "Created an inventory exception dashboard that ranked SKU-location stockout risk and excess working capital using demand and reorder thresholds.",
  },
  {
    id: "executive-dashboard",
    title: "Executive Dashboard",
    icon: "🏢",
    category: "Advanced",
    difficulty: "Advanced",
    estimatedTime: "10–14 hours",
    businessScenario: "A SaaS executive team needs one concise view of growth, retention, customer value, and operational risk.",
    backgroundStory: "Each team reports different definitions, making leadership discussions slow and inconsistent.",
    skillsRequired: ["KPI governance", "Power BI or Tableau", "Executive storytelling", "Metric definitions"],
    dataset: {
      libraryId: "saas-metrics",
      usage: "Use subscription account behavior as the source for an executive operating view.",
      focusFields: ["Segment", "TenureMonths", "MonthlyValue", "EngagementScore", "Outcome"],
    },
    audience: "a SaaS executive team",
    metricFocus: ["recurring value", "retention", "engagement", "customer concentration"],
    deliverable: "an executive dashboard with governed KPI definitions and drill-down",
    decision: "where leadership should focus growth and retention resources",
    risk: "compressing complex business health into misleading headline KPIs",
    xpReward: 180,
    achievementBadge: { icon: "👑", title: "Executive Storyteller" },
    portfolioDescription: "An executive SaaS dashboard with governed KPI definitions, retention diagnostics, and decision-focused narrative.",
    resumeBullet: "Designed an executive SaaS dashboard integrating recurring value, retention, and engagement KPIs with governed definitions and drill-down analysis.",
  },
  {
    id: "financial-kpi-dashboard",
    title: "Financial KPI Dashboard",
    icon: "📈",
    category: "Advanced",
    difficulty: "Advanced",
    estimatedTime: "9–12 hours",
    businessScenario: "Finance and customer success need a shared view of recurring revenue, renewal risk, and forecast movement.",
    backgroundStory: "The financial plan and customer status are reviewed separately, hiding the drivers behind revenue changes.",
    skillsRequired: ["Financial modeling", "Cohorts", "Forecasting", "Variance analysis"],
    dataset: {
      libraryId: "subscription-revenue",
      usage: "Use subscription customer value, tenure, engagement, and renewal outcomes.",
      focusFields: ["Segment", "TenureMonths", "MonthlyValue", "EngagementScore", "Outcome"],
    },
    audience: "a finance leadership team",
    metricFocus: ["monthly recurring value", "renewal rate", "revenue at risk", "forecast variance"],
    deliverable: "a financial KPI dashboard with cohort and risk views",
    decision: "how to update the forecast and prioritize renewal interventions",
    risk: "presenting a deterministic forecast without uncertainty or assumptions",
    xpReward: 175,
    achievementBadge: { icon: "💹", title: "Financial KPI Architect" },
    portfolioDescription: "A financial KPI dashboard connecting recurring revenue, renewal cohorts, customer engagement, and forecast risk.",
    resumeBullet: "Built a financial KPI dashboard linking recurring revenue, renewal cohorts, and customer engagement to quantify forecast risk.",
  },
  {
    id: "marketing-analytics",
    title: "Marketing Analytics",
    icon: "📣",
    category: "Advanced",
    difficulty: "Advanced",
    estimatedTime: "9–12 hours",
    businessScenario: "A marketing leader must reallocate campaign budget toward efficient growth without overstating attribution.",
    backgroundStory: "Channel reports disagree on conversion, revenue, and return definitions.",
    skillsRequired: ["Funnel analysis", "ROAS", "Attribution caveats", "Scenario analysis"],
    dataset: {
      libraryId: "marketing-campaign",
      usage: "Use cross-channel spend, reach, clicks, conversions, and attributed revenue.",
      focusFields: ["Campaign", "Channel", "Spend", "Clicks", "Conversions", "Revenue"],
    },
    audience: "a marketing leadership team",
    metricFocus: ["conversion rate", "cost per conversion", "ROAS", "incremental scenario"],
    deliverable: "a campaign performance dashboard with budget scenarios",
    decision: "how to rebalance the next campaign budget",
    risk: "treating attributed revenue as proven incrementality",
    xpReward: 175,
    achievementBadge: { icon: "🎯", title: "Campaign Strategist" },
    portfolioDescription: "A marketing analytics case study comparing campaign funnels, efficiency, attributed revenue, and budget scenarios.",
    resumeBullet: "Analyzed cross-channel marketing performance and built budget scenarios using conversion, acquisition-cost, and ROAS metrics with attribution caveats.",
  },
  {
    id: "healthcare-analytics",
    title: "Healthcare Analytics",
    icon: "🏥",
    category: "Advanced",
    difficulty: "Advanced",
    estimatedTime: "10–14 hours",
    businessScenario: "Hospital operations needs to compare service demand, cost, and outcomes while protecting patient privacy.",
    backgroundStory: "Leaders need operational insight, but small cohorts and clinical context make careless comparisons risky.",
    skillsRequired: ["Cohort analysis", "Healthcare KPIs", "Privacy safeguards", "Operational dashboards"],
    dataset: {
      libraryId: "hospital-patients",
      usage: "Use anonymized encounter-level service, cost, department, and outcome data.",
      focusFields: ["Facility", "Department", "PatientGroup", "Service", "Cost", "Outcome"],
    },
    audience: "a hospital operations team",
    metricFocus: ["service volume", "cost per encounter", "outcome mix", "capacity pressure"],
    deliverable: "a privacy-aware healthcare operations dashboard",
    decision: "where operational capacity and process investigation are needed",
    risk: "privacy disclosure and case-mix differences between cohorts",
    extraHint: "Use minimum cohort-size rules and avoid presenting operational patterns as clinical conclusions.",
    xpReward: 190,
    achievementBadge: { icon: "🩺", title: "Healthcare Insight Analyst" },
    portfolioDescription: "A privacy-aware healthcare operations dashboard comparing service demand, cost, outcomes, and capacity indicators.",
    resumeBullet: "Created a privacy-aware healthcare operations dashboard using cohort safeguards to compare service demand, cost, and outcome patterns.",
  },
  {
    id: "supply-chain-analytics",
    title: "Supply Chain Analytics",
    icon: "🚚",
    category: "Advanced",
    difficulty: "Advanced",
    estimatedTime: "10–14 hours",
    businessScenario: "Distribution leadership needs to improve throughput and quality without shifting cost or delay elsewhere.",
    backgroundStory: "Warehouses report output, defects, cycle time, and cost separately, preventing balanced comparisons.",
    skillsRequired: ["Power Query", "Operational KPIs", "Pareto analysis", "Exception diagnostics"],
    dataset: {
      libraryId: "warehouse-operations",
      usage: "Use warehouse production, quality, cycle-time, and cost observations.",
      focusFields: ["Date", "Site", "Process", "Units", "Defects", "CycleMinutes", "Cost"],
    },
    audience: "a distribution leadership team",
    metricFocus: ["throughput", "defect rate", "cycle time", "cost per unit"],
    deliverable: "a supply-chain performance and exception dashboard",
    decision: "which site and process improvements should be prioritized",
    risk: "optimizing one KPI while worsening another part of the process",
    xpReward: 185,
    achievementBadge: { icon: "⚙️", title: "Operations Optimizer" },
    portfolioDescription: "A supply-chain analytics dashboard balancing throughput, quality, cycle time, and cost across warehouses.",
    resumeBullet: "Built a warehouse performance dashboard that prioritized process improvements using throughput, defect, cycle-time, and unit-cost analysis.",
  },
  {
    id: "government-data-analysis",
    title: "Government Dataset Analysis",
    icon: "🏛️",
    category: "Real World",
    difficulty: "Advanced",
    estimatedTime: "12–16 hours",
    businessScenario: "A policy team needs an accessible evidence brief that explains a public trend, regional difference, and actionable limitation.",
    backgroundStory: "The source is public, but definitions, revisions, geographic coverage, and missing values require careful documentation.",
    skillsRequired: ["Data documentation", "Trend analysis", "Public-interest storytelling", "Accessibility"],
    dataset: {
      libraryId: "energy-consumption",
      usage: "Use the energy time-series dataset as a safe stand-in for an official open-data workflow.",
      focusFields: ["Date", "Symbol", "Open", "High", "Low", "Close", "ChangePct"],
    },
    audience: "a public policy team",
    metricFocus: ["trend", "regional or series difference", "change rate", "exception period"],
    deliverable: "an accessible public-data briefing dashboard",
    decision: "where further policy investigation or resource planning is justified",
    risk: "source revisions, incomplete coverage, and political overinterpretation",
    xpReward: 210,
    achievementBadge: { icon: "🗺️", title: "Civic Data Storyteller" },
    portfolioDescription: "A documented public-data analysis translating time-series evidence into an accessible policy briefing with limitations.",
    resumeBullet: "Produced an accessible public-data briefing with documented definitions, trend analysis, validation checks, and policy-relevant limitations.",
  },
  {
    id: "public-dataset-story",
    title: "Public Dataset Story",
    icon: "🌍",
    category: "Real World",
    difficulty: "Intermediate",
    estimatedTime: "8–12 hours",
    businessScenario: "A community publication wants a transparent visual story built from a public dataset.",
    backgroundStory: "Readers need context and reproducibility, not only an attractive chart.",
    skillsRequired: ["Data sourcing", "Exploratory analysis", "Visualization", "Source notes"],
    dataset: {
      libraryId: "airline-performance",
      usage: "Use flight route, delay, status, and revenue observations for a public-interest data story.",
      focusFields: ["Date", "Origin", "Destination", "DelayMinutes", "Status", "Revenue"],
    },
    audience: "a general public audience",
    metricFocus: ["delay rate", "route comparison", "status mix", "change over time"],
    deliverable: "a transparent visual data story with source and method notes",
    decision: "which travel patterns deserve public attention or deeper reporting",
    risk: "cherry-picking a dramatic period or route",
    xpReward: 170,
    achievementBadge: { icon: "📰", title: "Open Data Communicator" },
    portfolioDescription: "A reproducible public-data story explaining airline delay patterns with transparent methods and contextual limitations.",
    resumeBullet: "Created a reproducible public-data story analyzing airline delays by route and period with transparent sourcing and validation notes.",
  },
  {
    id: "startup-case-study",
    title: "Startup Case Study",
    icon: "🚀",
    category: "Real World",
    difficulty: "Advanced",
    estimatedTime: "12–16 hours",
    businessScenario: "A startup leadership team must decide whether to prioritize activation, retention, or expansion.",
    backgroundStory: "Growth metrics are moving in different directions and limited resources allow only one primary initiative.",
    skillsRequired: ["SaaS metrics", "Cohort analysis", "Prioritization", "Executive recommendation"],
    dataset: {
      libraryId: "saas-metrics",
      usage: "Use subscription accounts as a startup growth and retention case.",
      focusFields: ["Segment", "TenureMonths", "MonthlyValue", "EngagementScore", "Outcome"],
    },
    audience: "startup founders and product leadership",
    metricFocus: ["activation proxy", "retention", "expansion value", "customer concentration"],
    deliverable: "a startup growth case study with one prioritized recommendation",
    decision: "which growth lever should receive the next quarter's resources",
    risk: "drawing strong causal conclusions from observational behavior",
    xpReward: 220,
    achievementBadge: { icon: "💡", title: "Startup Strategy Analyst" },
    portfolioDescription: "A startup analytics case study balancing activation, retention, expansion, and customer concentration to prioritize one growth lever.",
    resumeBullet: "Built a SaaS startup case study using cohort and value analysis to prioritize a growth initiative and define measurable guardrails.",
  },
  {
    id: "ngo-program-analytics",
    title: "NGO Analytics",
    icon: "🤲",
    category: "Real World",
    difficulty: "Advanced",
    estimatedTime: "10–14 hours",
    businessScenario: "An NGO needs to allocate limited program support using transparent, non-stigmatizing evidence.",
    backgroundStory: "Program outcomes differ across groups, but missing context and small samples could lead to unfair comparisons.",
    skillsRequired: ["Program metrics", "Cohort safeguards", "Outcome analysis", "Ethical storytelling"],
    dataset: {
      libraryId: "student-performance",
      usage: "Use anonymized education outcomes as a proxy for a learning-support program.",
      focusFields: ["Course", "Term", "StudyHours", "AttendancePct", "FinalScore", "Outcome"],
    },
    audience: "an NGO program leadership team",
    metricFocus: ["participation", "support reach", "outcome rate", "cohort difference"],
    deliverable: "an ethical program-monitoring dashboard and action brief",
    decision: "where program support should be investigated or expanded",
    risk: "stigmatizing participants or overreading small cohort differences",
    extraHint: "Frame findings around program conditions and support opportunities, not individual blame.",
    xpReward: 200,
    achievementBadge: { icon: "🌱", title: "Impact Analytics Advocate" },
    portfolioDescription: "An ethical NGO program-monitoring case study using cohort safeguards and transparent outcome definitions.",
    resumeBullet: "Developed an NGO program dashboard with cohort safeguards, participation metrics, and evidence-led recommendations for support allocation.",
  },
  {
    id: "education-analytics",
    title: "Education Analytics",
    icon: "🏫",
    category: "Real World",
    difficulty: "Advanced",
    estimatedTime: "10–14 hours",
    businessScenario: "An academic support team wants to identify early support signals without labeling students unfairly.",
    backgroundStory: "Attendance, study time, assessments, and outcomes are available, but intervention decisions need context and safeguards.",
    skillsRequired: ["Statistics", "Correlation", "Regression basics", "Responsible analysis"],
    dataset: {
      libraryId: "student-performance",
      usage: "Use anonymized student performance measures for responsible support analysis.",
      focusFields: ["StudyHours", "AttendancePct", "AssessmentScore", "FinalScore", "Outcome"],
    },
    audience: "an academic support team",
    metricFocus: ["attendance", "assessment gap", "outcome rate", "support signal"],
    deliverable: "a responsible education analytics report with support-focused recommendations",
    decision: "which program conditions deserve further support investigation",
    risk: "confusing association with causation or creating harmful student labels",
    extraHint: "Report uncertainty and avoid turning group patterns into automatic individual decisions.",
    xpReward: 205,
    achievementBadge: { icon: "📚", title: "Education Insight Steward" },
    portfolioDescription: "A responsible education analytics project examining attendance, study patterns, assessments, and outcomes with clear safeguards.",
    resumeBullet: "Analyzed anonymized education outcomes using descriptive statistics and responsible cohort comparisons to identify support opportunities.",
  },
];

export const portfolioProjects = projectSeeds.map(createProject);

export function getPortfolioProject(id: string) {
  return portfolioProjects.find((project) => project.id === id);
}
