const KEY = "databloom-power-bi-progress-v1";
export const POWER_BI_PROGRESS_EVENT = "databloom:power-bi-progress-updated";
export type PowerBIProgressState = { completedLessonIds:string[]; completedDAXIds:string[]; favoriteIds:string[]; completedPracticeIds:string[]; notes:Record<string,string> };
const EMPTY:PowerBIProgressState = {completedLessonIds:[],completedDAXIds:[],favoriteIds:[],completedPracticeIds:[],notes:{}};
const usable=()=>typeof window!=="undefined"&&"localStorage" in window;
const strings=(v:unknown)=>Array.isArray(v)?Array.from(new Set(v.filter((x):x is string=>typeof x==="string"))):[];
function normalize(v:unknown):PowerBIProgressState { const x=(v&&typeof v==="object"?v:{}) as Partial<PowerBIProgressState>; const notes=x.notes&&typeof x.notes==="object"&&!Array.isArray(x.notes)?Object.fromEntries(Object.entries(x.notes).filter((e):e is [string,string]=>typeof e[1]==="string")):{}; return {completedLessonIds:strings(x.completedLessonIds),completedDAXIds:strings(x.completedDAXIds),favoriteIds:strings(x.favoriteIds),completedPracticeIds:strings(x.completedPracticeIds),notes}; }
export function loadPowerBIProgress(){if(!usable())return {...EMPTY,notes:{}};try{const raw=localStorage.getItem(KEY);return raw?normalize(JSON.parse(raw)):{...EMPTY,notes:{}}}catch{return {...EMPTY,notes:{}}}}
function save(state:PowerBIProgressState,id:string){if(!usable())return false;try{localStorage.setItem(KEY,JSON.stringify(state));window.dispatchEvent(new CustomEvent(POWER_BI_PROGRESS_EVENT,{detail:{id,state}}));return true}catch{return false}}
export function completePowerBIItem(id:string){const state=loadPowerBIProgress();const dax=id.startsWith("dax-");const key=dax?"completedDAXIds":"completedLessonIds" as const;if(!id||state[key].includes(id))return{newlyCompleted:false,state};const next={...state,[key]:[...state[key],id]};return save(next,id)?{newlyCompleted:true,state:next}:{newlyCompleted:false,state};}
export function completePowerBIPractice(id:string){const state=loadPowerBIProgress();if(!id||state.completedPracticeIds.includes(id))return{newlyCompleted:false,state};const next={...state,completedPracticeIds:[...state.completedPracticeIds,id]};return save(next,id)?{newlyCompleted:true,state:next}:{newlyCompleted:false,state};}
export function togglePowerBIFavorite(id:string){const state=loadPowerBIProgress();if(!id)return state;const favoriteIds=state.favoriteIds.includes(id)?state.favoriteIds.filter(x=>x!==id):[...state.favoriteIds,id];const next={...state,favoriteIds};return save(next,id)?next:state;}
export const getPowerBINote=(id:string)=>loadPowerBIProgress().notes[id]??"";
export function savePowerBINote(id:string,note:string){if(!id)return false;const state=loadPowerBIProgress();const notes={...state.notes};if(note.trim())notes[id]=note;else delete notes[id];return save({...state,notes},id);}
export const calculatePowerBIProgress=(completed:number,total:number)=>total?Math.min(100,Math.round(completed/total*100)):0;
export function isAcceptedPowerBIAnswer(answer:string,accepted:string[]){const value=answer.trim().replace(/\s+/g," ").toLowerCase();return accepted.some(x=>{const expected=x.trim().replace(/\s+/g," ").toLowerCase();return value===expected||value.includes(expected)||expected.includes(value)});}
