export type SQLDifficulty = "Beginner" | "Intermediate" | "Advanced";

export type SQLLesson = {
  id: string;
  title: string;
  icon: string;
  category: string;
  difficulty: SQLDifficulty;
  description: string;
  explanation: string;
  syntax: string;
  example: string;
  memoryTrick: string;
  whenToUse: string[];
  commonMistakes: string[];
  interviewQuestions: string[];
  practiceTask: string;
  expectedAnswer: string;
  acceptedAnswers: string[];
  hint: string;
  xpReward: number;
  relatedLessons: string[];
};

type SQLLessonSeed = Pick<
  SQLLesson,
  | "id"
  | "title"
  | "icon"
  | "category"
  | "difficulty"
  | "description"
  | "syntax"
  | "example"
  | "practiceTask"
  | "expectedAnswer"
  | "hint"
> &
  Partial<
    Pick<
      SQLLesson,
      | "explanation"
      | "memoryTrick"
      | "whenToUse"
      | "commonMistakes"
      | "interviewQuestions"
      | "acceptedAnswers"
      | "xpReward"
      | "relatedLessons"
    >
  >;

function makeLesson(seed: SQLLessonSeed): SQLLesson {
  const reward =
    seed.difficulty === "Beginner" ? 20 : seed.difficulty === "Intermediate" ? 30 : 40;

  return {
    ...seed,
    explanation:
      seed.explanation ??
      `${seed.description} Think of it as one clear instruction in the question you are asking the database.`,
    memoryTrick:
      seed.memoryTrick ?? `${seed.title} tells SQL exactly what part of the answer you need.`,
    whenToUse: seed.whenToUse ?? [
      "When answering a focused business question from structured data.",
      "When building a repeatable analyst query instead of checking rows manually.",
    ],
    commonMistakes: seed.commonMistakes ?? [
      `Putting ${seed.title} in the wrong part of the query.`,
      "Using a column or table name that does not exist.",
    ],
    interviewQuestions: seed.interviewQuestions ?? [
      `What problem does ${seed.title} solve?`,
      `Where does ${seed.title} appear in a SQL query?`,
    ],
    acceptedAnswers: Array.from(
      new Set([seed.expectedAnswer, ...(seed.acceptedAnswers ?? [])]),
    ),
    xpReward: seed.xpReward ?? reward,
    relatedLessons: seed.relatedLessons ?? [],
  };
}

const seeds: SQLLessonSeed[] = [
  {
    id: "select",
    title: "SELECT",
    icon: "🎯",
    category: "Query Basics",
    difficulty: "Beginner",
    description: "Choose the columns you want to see in the result.",
    syntax: "SELECT column_name FROM table_name;",
    example: "SELECT CustomerName, Sales FROM sales;",
    practiceTask: "Return CustomerName and Sales from the sales table.",
    expectedAnswer: "SELECT CustomerName, Sales FROM sales",
    acceptedAnswers: ["SELECT Sales, CustomerName FROM sales"],
    hint: "Start with SELECT, list two columns, then name the table.",
    memoryTrick: "SELECT = select what appears on your report.",
    relatedLessons: ["from", "distinct"],
  },
  {
    id: "from",
    title: "FROM",
    icon: "🗂️",
    category: "Query Basics",
    difficulty: "Beginner",
    description: "Tell SQL which table contains the data.",
    syntax: "SELECT * FROM table_name;",
    example: "SELECT * FROM sales;",
    practiceTask: "Return every column from the sales table.",
    expectedAnswer: "SELECT * FROM sales",
    hint: "Use the star to mean every column.",
    memoryTrick: "FROM = where the data comes from.",
    relatedLessons: ["select", "where"],
  },
  {
    id: "where",
    title: "WHERE",
    icon: "🔎",
    category: "Filtering",
    difficulty: "Beginner",
    description: "Keep only rows that match a condition.",
    syntax: "SELECT * FROM table_name WHERE condition;",
    example: "SELECT * FROM sales WHERE Region = 'North';",
    practiceTask: "Return all sales rows from the North region.",
    expectedAnswer: "SELECT * FROM sales WHERE Region = 'North'",
    acceptedAnswers: ["SELECT * FROM sales WHERE Region='North'"],
    hint: "Filter Region so it equals the text North.",
    memoryTrick: "WHERE = where is the row I need?",
    relatedLessons: ["and", "or", "in"],
  },
  {
    id: "distinct",
    title: "DISTINCT",
    icon: "✨",
    category: "Query Basics",
    difficulty: "Beginner",
    description: "Remove repeated values from a result.",
    syntax: "SELECT DISTINCT column_name FROM table_name;",
    example: "SELECT DISTINCT Region FROM sales;",
    practiceTask: "Return each Region only once from sales.",
    expectedAnswer: "SELECT DISTINCT Region FROM sales",
    hint: "Place DISTINCT immediately after SELECT.",
    relatedLessons: ["select", "group-by"],
  },
  {
    id: "order-by",
    title: "ORDER BY",
    icon: "↕️",
    category: "Query Basics",
    difficulty: "Beginner",
    description: "Sort results in ascending or descending order.",
    syntax: "SELECT * FROM table_name ORDER BY column_name DESC;",
    example: "SELECT * FROM sales ORDER BY Sales DESC;",
    practiceTask: "Return all sales rows from highest Sales to lowest.",
    expectedAnswer: "SELECT * FROM sales ORDER BY Sales DESC",
    hint: "DESC means the largest value appears first.",
    relatedLessons: ["limit", "select"],
  },
  {
    id: "limit",
    title: "LIMIT",
    icon: "🛑",
    category: "Query Basics",
    difficulty: "Beginner",
    description: "Return only a chosen number of rows.",
    syntax: "SELECT * FROM table_name LIMIT number;",
    example: "SELECT * FROM sales LIMIT 5;",
    practiceTask: "Return only the first 3 rows from sales.",
    expectedAnswer: "SELECT * FROM sales LIMIT 3",
    hint: "Add LIMIT and the number at the end.",
    relatedLessons: ["order-by", "select"],
  },
  {
    id: "aliases",
    title: "AS aliases",
    icon: "🏷️",
    category: "Query Basics",
    difficulty: "Beginner",
    description: "Give a column or table a clearer temporary name.",
    syntax: "SELECT column_name AS alias_name FROM table_name;",
    example: "SELECT Sales AS Revenue FROM sales;",
    practiceTask: "Return Sales with the display name Revenue.",
    expectedAnswer: "SELECT Sales AS Revenue FROM sales",
    acceptedAnswers: ["SELECT Sales Revenue FROM sales"],
    hint: "Write AS Revenue immediately after Sales.",
    relatedLessons: ["select", "case-when"],
  },
  {
    id: "and",
    title: "AND",
    icon: "➕",
    category: "Filtering",
    difficulty: "Beginner",
    description: "Require two or more conditions to be true.",
    syntax: "WHERE condition_one AND condition_two",
    example: "SELECT * FROM sales WHERE Region = 'North' AND Sales > 500;",
    practiceTask: "Return North region rows where Sales is greater than 500.",
    expectedAnswer: "SELECT * FROM sales WHERE Region = 'North' AND Sales > 500",
    acceptedAnswers: ["SELECT * FROM sales WHERE Sales > 500 AND Region = 'North'"],
    hint: "Put AND between the Region and Sales conditions.",
    relatedLessons: ["where", "or", "not"],
  },
  {
    id: "or",
    title: "OR",
    icon: "🔀",
    category: "Filtering",
    difficulty: "Beginner",
    description: "Keep a row when either condition is true.",
    syntax: "WHERE condition_one OR condition_two",
    example: "SELECT * FROM sales WHERE Region = 'North' OR Region = 'West';",
    practiceTask: "Return rows from either North or West.",
    expectedAnswer: "SELECT * FROM sales WHERE Region = 'North' OR Region = 'West'",
    acceptedAnswers: ["SELECT * FROM sales WHERE Region = 'West' OR Region = 'North'"],
    hint: "Use two Region comparisons joined with OR.",
    relatedLessons: ["where", "and", "in"],
  },
  {
    id: "not",
    title: "NOT",
    icon: "🚫",
    category: "Filtering",
    difficulty: "Beginner",
    description: "Reverse a condition so matching values are excluded.",
    syntax: "WHERE NOT condition",
    example: "SELECT * FROM sales WHERE NOT Region = 'North';",
    practiceTask: "Return rows that are not from North.",
    expectedAnswer: "SELECT * FROM sales WHERE NOT Region = 'North'",
    acceptedAnswers: ["SELECT * FROM sales WHERE Region <> 'North'", "SELECT * FROM sales WHERE Region != 'North'"],
    hint: "Place NOT before the Region condition, or use a not-equal operator.",
    relatedLessons: ["where", "and", "is-null"],
  },
  {
    id: "in",
    title: "IN",
    icon: "📦",
    category: "Filtering",
    difficulty: "Beginner",
    description: "Match a value against a short list of options.",
    syntax: "WHERE column_name IN (value_one, value_two)",
    example: "SELECT * FROM sales WHERE Region IN ('North', 'West');",
    practiceTask: "Return rows from North or West using IN.",
    expectedAnswer: "SELECT * FROM sales WHERE Region IN ('North', 'West')",
    acceptedAnswers: ["SELECT * FROM sales WHERE Region IN ('West', 'North')"],
    hint: "Put the two region names inside parentheses.",
    relatedLessons: ["where", "or", "between"],
  },
  {
    id: "between",
    title: "BETWEEN",
    icon: "↔️",
    category: "Filtering",
    difficulty: "Beginner",
    description: "Filter values inside an inclusive range.",
    syntax: "WHERE column_name BETWEEN low_value AND high_value",
    example: "SELECT * FROM sales WHERE Sales BETWEEN 500 AND 1000;",
    practiceTask: "Return rows with Sales from 500 through 1000.",
    expectedAnswer: "SELECT * FROM sales WHERE Sales BETWEEN 500 AND 1000",
    hint: "BETWEEN includes both boundary values.",
    relatedLessons: ["where", "in", "and"],
  },
  {
    id: "like",
    title: "LIKE",
    icon: "🧩",
    category: "Filtering",
    difficulty: "Beginner",
    description: "Find text that follows a pattern.",
    syntax: "WHERE column_name LIKE 'pattern%'",
    example: "SELECT * FROM sales WHERE CustomerName LIKE 'A%';",
    practiceTask: "Return customers whose names begin with A.",
    expectedAnswer: "SELECT * FROM sales WHERE CustomerName LIKE 'A%'",
    hint: "The percent sign represents any text after A.",
    relatedLessons: ["where", "not"],
  },
  {
    id: "is-null",
    title: "IS NULL",
    icon: "🕳️",
    category: "Filtering",
    difficulty: "Beginner",
    description: "Find rows where a value is missing.",
    syntax: "WHERE column_name IS NULL",
    example: "SELECT * FROM sales WHERE Product IS NULL;",
    practiceTask: "Return rows where Product is missing.",
    expectedAnswer: "SELECT * FROM sales WHERE Product IS NULL",
    hint: "NULL is checked with IS NULL, not equals.",
    relatedLessons: ["where", "not"],
  },
  {
    id: "count",
    title: "COUNT",
    icon: "🔢",
    category: "Aggregations",
    difficulty: "Intermediate",
    description: "Count rows or non-null values.",
    syntax: "SELECT COUNT(*) FROM table_name;",
    example: "SELECT COUNT(*) AS OrderCount FROM sales;",
    practiceTask: "Count every order in sales.",
    expectedAnswer: "SELECT COUNT(*) FROM sales",
    acceptedAnswers: ["SELECT COUNT(*) AS OrderCount FROM sales"],
    hint: "COUNT(*) counts rows.",
    relatedLessons: ["group-by", "having"],
  },
  {
    id: "sum",
    title: "SUM",
    icon: "➗",
    category: "Aggregations",
    difficulty: "Intermediate",
    description: "Add all numeric values in a column.",
    syntax: "SELECT SUM(column_name) FROM table_name;",
    example: "SELECT SUM(Sales) AS TotalSales FROM sales;",
    practiceTask: "Calculate total Sales from the sales table.",
    expectedAnswer: "SELECT SUM(Sales) FROM sales",
    acceptedAnswers: ["SELECT SUM(Sales) AS TotalSales FROM sales"],
    hint: "Wrap Sales inside SUM parentheses.",
    relatedLessons: ["avg", "group-by"],
  },
  {
    id: "avg",
    title: "AVG",
    icon: "⚖️",
    category: "Aggregations",
    difficulty: "Intermediate",
    description: "Calculate the arithmetic average of numeric values.",
    syntax: "SELECT AVG(column_name) FROM table_name;",
    example: "SELECT AVG(Sales) AS AverageSale FROM sales;",
    practiceTask: "Calculate the average Sales value.",
    expectedAnswer: "SELECT AVG(Sales) FROM sales",
    acceptedAnswers: ["SELECT AVG(Sales) AS AverageSale FROM sales"],
    hint: "AVG works like SUM but divides by the number of values.",
    relatedLessons: ["sum", "min", "max"],
  },
  {
    id: "min",
    title: "MIN",
    icon: "📉",
    category: "Aggregations",
    difficulty: "Intermediate",
    description: "Find the smallest value in a column.",
    syntax: "SELECT MIN(column_name) FROM table_name;",
    example: "SELECT MIN(Sales) FROM sales;",
    practiceTask: "Find the smallest Sales value.",
    expectedAnswer: "SELECT MIN(Sales) FROM sales",
    hint: "Wrap Sales inside MIN parentheses.",
    relatedLessons: ["max", "avg"],
  },
  {
    id: "max",
    title: "MAX",
    icon: "📈",
    category: "Aggregations",
    difficulty: "Intermediate",
    description: "Find the largest value in a column.",
    syntax: "SELECT MAX(column_name) FROM table_name;",
    example: "SELECT MAX(Sales) FROM sales;",
    practiceTask: "Find the largest Sales value.",
    expectedAnswer: "SELECT MAX(Sales) FROM sales",
    hint: "Wrap Sales inside MAX parentheses.",
    relatedLessons: ["min", "order-by"],
  },
  {
    id: "group-by",
    title: "GROUP BY",
    icon: "🧺",
    category: "Aggregations",
    difficulty: "Intermediate",
    description: "Create one summary result for each group.",
    syntax: "SELECT group_column, SUM(value) FROM table GROUP BY group_column;",
    example: "SELECT Region, SUM(Sales) FROM sales GROUP BY Region;",
    practiceTask: "Calculate total Sales for each Region.",
    expectedAnswer: "SELECT Region, SUM(Sales) FROM sales GROUP BY Region",
    acceptedAnswers: ["SELECT Region, SUM(Sales) AS TotalSales FROM sales GROUP BY Region"],
    hint: "Select Region and the aggregation, then group by Region.",
    relatedLessons: ["having", "count", "sum"],
  },
  {
    id: "having",
    title: "HAVING",
    icon: "🧹",
    category: "Aggregations",
    difficulty: "Intermediate",
    description: "Filter groups after an aggregation is calculated.",
    syntax: "GROUP BY column_name HAVING aggregate_condition",
    example: "SELECT Region, SUM(Sales) FROM sales GROUP BY Region HAVING SUM(Sales) > 1000;",
    practiceTask: "Show regions whose total Sales is greater than 1000.",
    expectedAnswer: "SELECT Region, SUM(Sales) FROM sales GROUP BY Region HAVING SUM(Sales) > 1000",
    hint: "WHERE filters rows; HAVING filters grouped totals.",
    relatedLessons: ["group-by", "where"],
  },
  {
    id: "inner-join",
    title: "INNER JOIN",
    icon: "🤝",
    category: "Joins",
    difficulty: "Intermediate",
    description: "Return rows that match in both tables.",
    syntax: "FROM table_a INNER JOIN table_b ON table_a.key = table_b.key",
    example: "SELECT * FROM sales INNER JOIN customers ON sales.CustomerName = customers.CustomerName;",
    practiceTask: "Join sales to customers where CustomerName matches.",
    expectedAnswer: "SELECT * FROM sales INNER JOIN customers ON sales.CustomerName = customers.CustomerName",
    acceptedAnswers: ["SELECT * FROM sales JOIN customers ON sales.CustomerName = customers.CustomerName"],
    hint: "The ON clause explains how the two tables match.",
    relatedLessons: ["left-join", "right-join"],
  },
  {
    id: "left-join",
    title: "LEFT JOIN",
    icon: "⬅️",
    category: "Joins",
    difficulty: "Intermediate",
    description: "Keep every left-table row and any matching right-table data.",
    syntax: "FROM table_a LEFT JOIN table_b ON table_a.key = table_b.key",
    example: "SELECT * FROM customers LEFT JOIN sales ON customers.CustomerName = sales.CustomerName;",
    practiceTask: "Keep every customer while matching their sales when available.",
    expectedAnswer: "SELECT * FROM customers LEFT JOIN sales ON customers.CustomerName = sales.CustomerName",
    acceptedAnswers: ["SELECT * FROM customers LEFT OUTER JOIN sales ON customers.CustomerName = sales.CustomerName"],
    hint: "Place customers on the left side of LEFT JOIN.",
    relatedLessons: ["inner-join", "right-join", "full-outer-join"],
  },
  {
    id: "right-join",
    title: "RIGHT JOIN",
    icon: "➡️",
    category: "Joins",
    difficulty: "Intermediate",
    description: "Keep every right-table row and matching left-table data.",
    syntax: "FROM table_a RIGHT JOIN table_b ON table_a.key = table_b.key",
    example: "SELECT * FROM sales RIGHT JOIN customers ON sales.CustomerName = customers.CustomerName;",
    practiceTask: "Keep every customer using customers as the right table.",
    expectedAnswer: "SELECT * FROM sales RIGHT JOIN customers ON sales.CustomerName = customers.CustomerName",
    acceptedAnswers: ["SELECT * FROM sales RIGHT OUTER JOIN customers ON sales.CustomerName = customers.CustomerName"],
    hint: "The table after RIGHT JOIN is fully preserved.",
    relatedLessons: ["left-join", "full-outer-join"],
  },
  {
    id: "full-outer-join",
    title: "FULL OUTER JOIN",
    icon: "🔄",
    category: "Joins",
    difficulty: "Intermediate",
    description: "Keep matched and unmatched rows from both tables.",
    syntax: "FROM table_a FULL OUTER JOIN table_b ON table_a.key = table_b.key",
    example: "SELECT * FROM sales FULL OUTER JOIN customers ON sales.CustomerName = customers.CustomerName;",
    practiceTask: "Return all sales and all customers, matching names where possible.",
    expectedAnswer: "SELECT * FROM sales FULL OUTER JOIN customers ON sales.CustomerName = customers.CustomerName",
    acceptedAnswers: ["SELECT * FROM sales FULL JOIN customers ON sales.CustomerName = customers.CustomerName"],
    hint: "FULL OUTER JOIN preserves both sides.",
    relatedLessons: ["left-join", "right-join"],
  },
  {
    id: "union",
    title: "UNION",
    icon: "🪢",
    category: "Set Operations",
    difficulty: "Intermediate",
    description: "Stack compatible query results and remove duplicates.",
    syntax: "SELECT column FROM table_a UNION SELECT column FROM table_b;",
    example: "SELECT Region FROM sales_2025 UNION SELECT Region FROM sales_2026;",
    practiceTask: "Combine unique Region values from sales_2025 and sales_2026.",
    expectedAnswer: "SELECT Region FROM sales_2025 UNION SELECT Region FROM sales_2026",
    acceptedAnswers: ["SELECT Region FROM sales_2026 UNION SELECT Region FROM sales_2025"],
    hint: "Both SELECT statements need compatible columns.",
    relatedLessons: ["union-all", "distinct"],
  },
  {
    id: "union-all",
    title: "UNION ALL",
    icon: "📚",
    category: "Set Operations",
    difficulty: "Intermediate",
    description: "Stack compatible query results and keep duplicates.",
    syntax: "SELECT column FROM table_a UNION ALL SELECT column FROM table_b;",
    example: "SELECT Region FROM sales_2025 UNION ALL SELECT Region FROM sales_2026;",
    practiceTask: "Combine every Region row from sales_2025 and sales_2026.",
    expectedAnswer: "SELECT Region FROM sales_2025 UNION ALL SELECT Region FROM sales_2026",
    acceptedAnswers: ["SELECT Region FROM sales_2026 UNION ALL SELECT Region FROM sales_2025"],
    hint: "Add ALL when duplicate rows must remain.",
    relatedLessons: ["union", "distinct"],
  },
  {
    id: "case-when",
    title: "CASE WHEN",
    icon: "🚦",
    category: "Conditional Logic",
    difficulty: "Intermediate",
    description: "Create a new value using if-then logic.",
    syntax: "CASE WHEN condition THEN value ELSE value END",
    example: "SELECT Sales, CASE WHEN Sales >= 1000 THEN 'High' ELSE 'Standard' END AS SaleBand FROM sales;",
    practiceTask: "Label Sales of 1000 or more as High, otherwise Standard, using SaleBand as the alias.",
    expectedAnswer: "SELECT Sales, CASE WHEN Sales >= 1000 THEN 'High' ELSE 'Standard' END AS SaleBand FROM sales",
    hint: "CASE starts the logic and END closes it.",
    relatedLessons: ["aliases", "where"],
  },
  {
    id: "subqueries",
    title: "Subqueries",
    icon: "🪆",
    category: "Advanced Queries",
    difficulty: "Intermediate",
    description: "Use one query inside another query.",
    syntax: "SELECT * FROM table WHERE value > (SELECT AVG(value) FROM table);",
    example: "SELECT * FROM sales WHERE Sales > (SELECT AVG(Sales) FROM sales);",
    practiceTask: "Return sales rows above the average Sales value.",
    expectedAnswer: "SELECT * FROM sales WHERE Sales > (SELECT AVG(Sales) FROM sales)",
    hint: "The inner query calculates the average first.",
    relatedLessons: ["common-table-expressions", "avg"],
  },
  {
    id: "common-table-expressions",
    title: "Common Table Expressions",
    icon: "🧱",
    category: "Advanced Queries",
    difficulty: "Advanced",
    description: "Name a temporary query result so a complex query reads clearly.",
    syntax: "WITH name AS (query) SELECT * FROM name;",
    example: "WITH NorthSales AS (SELECT * FROM sales WHERE Region = 'North') SELECT * FROM NorthSales;",
    practiceTask: "Create NorthSales for North rows, then select every column from it.",
    expectedAnswer: "WITH NorthSales AS (SELECT * FROM sales WHERE Region = 'North') SELECT * FROM NorthSales",
    hint: "Define the CTE after WITH, then query its name.",
    memoryTrick: "A CTE is a labeled sticky note for a temporary result.",
    relatedLessons: ["subqueries", "views"],
  },
  {
    id: "row-number",
    title: "ROW_NUMBER",
    icon: "#️⃣",
    category: "Window Functions",
    difficulty: "Advanced",
    description: "Give every row a unique sequential number.",
    syntax: "ROW_NUMBER() OVER (ORDER BY column_name)",
    example: "SELECT OrderID, ROW_NUMBER() OVER (ORDER BY Sales DESC) AS RowNum FROM sales;",
    practiceTask: "Number orders from highest Sales to lowest using RowNum.",
    expectedAnswer: "SELECT OrderID, ROW_NUMBER() OVER (ORDER BY Sales DESC) AS RowNum FROM sales",
    hint: "ROW_NUMBER needs an OVER clause with an ordering rule.",
    relatedLessons: ["rank", "dense-rank", "partition-by"],
  },
  {
    id: "rank",
    title: "RANK",
    icon: "🏅",
    category: "Window Functions",
    difficulty: "Advanced",
    description: "Rank rows while leaving gaps after tied values.",
    syntax: "RANK() OVER (ORDER BY column_name DESC)",
    example: "SELECT OrderID, RANK() OVER (ORDER BY Sales DESC) AS SalesRank FROM sales;",
    practiceTask: "Rank orders by Sales descending using SalesRank.",
    expectedAnswer: "SELECT OrderID, RANK() OVER (ORDER BY Sales DESC) AS SalesRank FROM sales",
    hint: "Use RANK followed by OVER and ORDER BY.",
    relatedLessons: ["row-number", "dense-rank"],
  },
  {
    id: "dense-rank",
    title: "DENSE_RANK",
    icon: "🥇",
    category: "Window Functions",
    difficulty: "Advanced",
    description: "Rank rows without gaps after tied values.",
    syntax: "DENSE_RANK() OVER (ORDER BY column_name DESC)",
    example: "SELECT OrderID, DENSE_RANK() OVER (ORDER BY Sales DESC) AS SalesRank FROM sales;",
    practiceTask: "Dense-rank orders by Sales descending using SalesRank.",
    expectedAnswer: "SELECT OrderID, DENSE_RANK() OVER (ORDER BY Sales DESC) AS SalesRank FROM sales",
    hint: "DENSE_RANK looks like RANK but does not skip the next number after a tie.",
    relatedLessons: ["rank", "row-number"],
  },
  {
    id: "lag",
    title: "LAG",
    icon: "⏮️",
    category: "Window Functions",
    difficulty: "Advanced",
    description: "Read a value from a previous row without a self-join.",
    syntax: "LAG(column_name) OVER (ORDER BY sort_column)",
    example: "SELECT OrderDate, Sales, LAG(Sales) OVER (ORDER BY OrderDate) AS PreviousSales FROM sales;",
    practiceTask: "Show each Sale with the previous Sales value ordered by OrderDate.",
    expectedAnswer: "SELECT OrderDate, Sales, LAG(Sales) OVER (ORDER BY OrderDate) AS PreviousSales FROM sales",
    hint: "LAG looks backward in the window order.",
    relatedLessons: ["lead", "partition-by"],
  },
  {
    id: "lead",
    title: "LEAD",
    icon: "⏭️",
    category: "Window Functions",
    difficulty: "Advanced",
    description: "Read a value from a following row without a self-join.",
    syntax: "LEAD(column_name) OVER (ORDER BY sort_column)",
    example: "SELECT OrderDate, Sales, LEAD(Sales) OVER (ORDER BY OrderDate) AS NextSales FROM sales;",
    practiceTask: "Show each Sale with the next Sales value ordered by OrderDate.",
    expectedAnswer: "SELECT OrderDate, Sales, LEAD(Sales) OVER (ORDER BY OrderDate) AS NextSales FROM sales",
    hint: "LEAD looks forward in the window order.",
    relatedLessons: ["lag", "partition-by"],
  },
  {
    id: "partition-by",
    title: "PARTITION BY",
    icon: "🧩",
    category: "Window Functions",
    difficulty: "Advanced",
    description: "Restart a window calculation inside each group.",
    syntax: "function() OVER (PARTITION BY group_column ORDER BY sort_column)",
    example: "SELECT Region, Sales, RANK() OVER (PARTITION BY Region ORDER BY Sales DESC) AS RegionRank FROM sales;",
    practiceTask: "Rank Sales inside each Region using RegionRank.",
    expectedAnswer: "SELECT Region, Sales, RANK() OVER (PARTITION BY Region ORDER BY Sales DESC) AS RegionRank FROM sales",
    hint: "PARTITION BY creates a separate ranking group for every Region.",
    relatedLessons: ["rank", "row-number", "lag"],
  },
  {
    id: "views",
    title: "Views",
    icon: "🪟",
    category: "Database Objects",
    difficulty: "Advanced",
    description: "Save a query as a reusable virtual table.",
    syntax: "CREATE VIEW view_name AS SELECT ...;",
    example: "CREATE VIEW NorthSales AS SELECT * FROM sales WHERE Region = 'North';",
    practiceTask: "Create a NorthSales view containing North region rows.",
    expectedAnswer: "CREATE VIEW NorthSales AS SELECT * FROM sales WHERE Region = 'North'",
    hint: "CREATE VIEW names the saved query before AS.",
    relatedLessons: ["common-table-expressions", "stored-procedures"],
  },
  {
    id: "stored-procedures",
    title: "Stored Procedures concept",
    icon: "📜",
    category: "Database Objects",
    difficulty: "Advanced",
    description: "Store a named set of SQL instructions inside a database.",
    syntax: "CREATE PROCEDURE procedure_name AS query;",
    example: "CREATE PROCEDURE GetSales AS SELECT * FROM sales;",
    practiceTask: "Write the basic definition for GetSales that returns every sales row.",
    expectedAnswer: "CREATE PROCEDURE GetSales AS SELECT * FROM sales",
    hint: "The exact syntax varies by database; use the simple SQL Server-style concept shown.",
    relatedLessons: ["views", "indexes"],
  },
  {
    id: "indexes",
    title: "Indexes concept",
    icon: "📇",
    category: "Performance",
    difficulty: "Advanced",
    description: "Create a lookup structure that can make filters and joins faster.",
    syntax: "CREATE INDEX index_name ON table_name (column_name);",
    example: "CREATE INDEX idx_region ON sales (Region);",
    practiceTask: "Create idx_region on the Region column of sales.",
    expectedAnswer: "CREATE INDEX idx_region ON sales (Region)",
    acceptedAnswers: ["CREATE INDEX idx_region ON sales(Region)"],
    hint: "Name the index, table, and indexed column.",
    commonMistakes: [
      "Adding indexes to every column, which slows writes and uses space.",
      "Forgetting to index columns frequently used in joins or filters.",
    ],
    relatedLessons: ["query-optimization", "stored-procedures"],
  },
  {
    id: "query-optimization",
    title: "Query optimization basics",
    icon: "⚡",
    category: "Performance",
    difficulty: "Advanced",
    description: "Write queries that return only the necessary data with less work.",
    syntax: "SELECT needed_columns FROM table_name WHERE selective_condition;",
    example: "SELECT OrderID, Sales FROM sales WHERE Region = 'North';",
    practiceTask: "Return only OrderID and Sales for North rows instead of using SELECT star.",
    expectedAnswer: "SELECT OrderID, Sales FROM sales WHERE Region = 'North'",
    acceptedAnswers: ["SELECT Sales, OrderID FROM sales WHERE Region = 'North'"],
    hint: "Choose only two needed columns and filter early.",
    memoryTrick: "Less data scanned usually means less time waited.",
    commonMistakes: [
      "Selecting every column when only two are needed.",
      "Filtering transformed columns in ways that prevent index use.",
    ],
    relatedLessons: ["indexes", "where", "select"],
  },
];

export const sqlLessons: SQLLesson[] = seeds.map(makeLesson);

export const sqlCategories = Array.from(
  new Set(sqlLessons.map((lesson) => lesson.category)),
);

export const sqlDifficulties: SQLDifficulty[] = [
  "Beginner",
  "Intermediate",
  "Advanced",
];

export function getSQLLesson(id: string) {
  return sqlLessons.find((lesson) => lesson.id === id);
}

export function getNextSQLLesson(id: string) {
  const index = sqlLessons.findIndex((lesson) => lesson.id === id);
  return index >= 0 ? sqlLessons[index + 1] : undefined;
}
