import type { TableauLessonSeed } from "@/lib/tableauLessons";

export const tableauLessonExpansion: TableauLessonSeed[] = [
  {
    id: "workbook-structure",
    title: "Workbooks, sheets, and tabs",
    icon: "📘",
    category: "Tableau Foundations",
    difficulty: "Beginner",
    description: "Organize worksheets, dashboards, and stories inside a Tableau workbook.",
    example: "Build separate Sales Trend and Regional Profit worksheets, then combine them in an Executive Dashboard.",
    practiceQuestion: "Which Tableau sheet type combines multiple worksheets in one interactive canvas?",
    correctAnswer: "A dashboard",
    distractors: ["A data source", "A calculated field"],
    hint: "It is the sheet type designed to arrange several views together.",
    relatedLessons: ["tableau-workspace", "dashboard-layout", "stories"],
  },
  {
    id: "show-me",
    title: "Using Show Me",
    icon: "✨",
    category: "Tableau Foundations",
    difficulty: "Beginner",
    description: "Use Show Me to identify chart types supported by the fields currently selected.",
    example: "Select Region and Sales, open Show Me, and choose horizontal bars for a categorical comparison.",
    practiceQuestion: "What determines which chart types are available in Show Me?",
    correctAnswer: "The number and types of selected fields",
    distractors: ["The workbook filename", "The dashboard background color"],
    hint: "Show Me evaluates the dimensions, measures, and geographic fields you select.",
    relatedLessons: ["chart-selection", "bar-charts", "bullet-graphs"],
  },
  {
    id: "organize-fields",
    title: "Organizing fields",
    icon: "🗃️",
    category: "Tableau Foundations",
    difficulty: "Beginner",
    description: "Use folders, hierarchies, hidden fields, and field search to keep the Data pane manageable.",
    example: "Group Revenue, Profit, and Margin into a Measures folder and create a Geography hierarchy from Country to City.",
    practiceQuestion: "Which feature supports drill-down from Country to State to City?",
    correctAnswer: "A hierarchy",
    distractors: ["A union", "A story point"],
    hint: "It defines an ordered path between related dimensions.",
    relatedLessons: ["dimensions-and-measures", "groups-and-bins", "metadata-and-describe"],
  },
  {
    id: "sorting-and-formatting",
    title: "Sorting and formatting views",
    icon: "🎨",
    category: "Tableau Foundations",
    difficulty: "Beginner",
    description: "Sort marks deliberately and format numbers, axes, lines, shading, and labels for readability.",
    example: "Sort Sub-Category by descending SUM(Sales), format Sales as currency, and reduce unnecessary grid lines.",
    practiceQuestion: "What should determine the sort order of a comparison chart?",
    correctAnswer: "The analytical question and comparison priority",
    distractors: ["The order fields appear in the source", "The workbook creation date"],
    hint: "Sorting should make the intended ranking or sequence easier to see.",
    relatedLessons: ["bar-charts", "chart-selection", "validating-a-worksheet"],
  },
  {
    id: "aliases-and-default-properties",
    title: "Aliases and default properties",
    icon: "🏷️",
    category: "Tableau Foundations",
    difficulty: "Intermediate",
    description: "Create readable member aliases and reusable defaults for formats, colors, comments, and aggregation.",
    example: "Rename the member 'C' to 'Consumer' with an alias and set Profit Ratio to percentage formatting by default.",
    practiceQuestion: "What does an alias change?",
    correctAnswer: "The displayed label for a dimension member",
    distractors: ["The underlying source value", "The physical join type"],
    hint: "It improves presentation without rewriting source data.",
    relatedLessons: ["organize-fields", "sorting-and-formatting", "data-types-and-roles"],
  },
  {
    id: "metadata-and-describe",
    title: "Describe and inspect data",
    icon: "🔍",
    category: "Tableau Foundations",
    difficulty: "Intermediate",
    description: "Use Describe, View Data, summaries, and metadata details to understand a field or view.",
    example: "Describe a worksheet to review fields and filters, then open View Data to validate the rows behind a selected mark.",
    practiceQuestion: "Which command helps inspect the source rows behind a selected mark?",
    correctAnswer: "View Data",
    distractors: ["Show Caption", "Duplicate as Crosstab"],
    hint: "It exposes summarized and underlying data for the current selection.",
    relatedLessons: ["validating-a-worksheet", "tableau-workspace", "data-types-and-roles"],
  },
  {
    id: "tableau-file-types",
    title: "Tableau file types",
    icon: "📁",
    category: "Tableau Foundations",
    difficulty: "Intermediate",
    description: "Distinguish workbook, packaged workbook, data source, packaged data source, and extract files.",
    example: "Share a .twbx when recipients need the workbook plus local files, while using .twb for the workbook definition alone.",
    practiceQuestion: "Which file type packages a workbook with its local supporting files?",
    correctAnswer: ".twbx",
    distractors: [".twb", ".hyper"],
    hint: "The extra x indicates a packaged Tableau artifact.",
    relatedLessons: ["publishing-workbooks", "extracts-and-live-connections", "published-data-sources"],
  },
  {
    id: "validating-a-worksheet",
    title: "Validating a worksheet",
    icon: "✅",
    category: "Tableau Foundations",
    difficulty: "Intermediate",
    description: "Check grain, filters, aggregations, totals, nulls, and source reconciliation before sharing a view.",
    example: "Compare a regional Sales total with a trusted source query and inspect unexpected null marks before publishing.",
    practiceQuestion: "What is the strongest validation for a KPI total?",
    correctAnswer: "Reconcile it with a trusted source total at the same grain",
    distractors: ["Change the font until it looks correct", "Add more dashboard objects"],
    hint: "Validation requires an independent number with matching scope and filters.",
    relatedLessons: ["metadata-and-describe", "aggregate-calculations", "interview-validation-testing"],
  },
  {
    id: "data-interpreter",
    title: "Data Interpreter",
    icon: "🧹",
    category: "Data Connections and Modeling",
    difficulty: "Beginner",
    description: "Use Data Interpreter to identify tabular data inside human-formatted spreadsheets and supported files.",
    example: "Turn on Data Interpreter for a report with title rows and footnotes, then review the detected table before analysis.",
    practiceQuestion: "What should you do after Data Interpreter cleans a file?",
    correctAnswer: "Review the detected table and verify headers and rows",
    distractors: ["Assume every detected field is correct", "Publish immediately without inspection"],
    hint: "Automated cleanup still needs validation.",
    relatedLessons: ["connect-to-data", "pivoting-data", "validating-a-worksheet"],
  },
  {
    id: "pivoting-data",
    title: "Pivoting columns to rows",
    icon: "🔄",
    category: "Data Connections and Modeling",
    difficulty: "Intermediate",
    description: "Reshape wide crosstab columns into field-name and field-value rows for analysis.",
    example: "Pivot Jan Sales, Feb Sales, and Mar Sales into Month and Sales fields before building a monthly trend.",
    practiceQuestion: "Why pivot monthly columns into rows?",
    correctAnswer: "To create a tidy field for month and a field for values",
    distractors: ["To permanently aggregate every row", "To create a dashboard container"],
    hint: "Tableau works best when variables are fields and observations are rows.",
    relatedLessons: ["data-interpreter", "unions", "line-charts"],
  },
  {
    id: "splitting-fields",
    title: "Split and custom split",
    icon: "✂️",
    category: "Data Connections and Modeling",
    difficulty: "Beginner",
    description: "Separate delimited text into useful fields with automatic or custom split rules.",
    example: "Split 'Jaipur-Rajasthan' on the hyphen to create City and State fields.",
    practiceQuestion: "When is a custom split useful?",
    correctAnswer: "When you must choose the delimiter and which segment to return",
    distractors: ["When joining two numeric tables", "When synchronizing dual axes"],
    hint: "It gives more control than an automatic split.",
    relatedLessons: ["string-calculations", "data-interpreter", "pivoting-data"],
  },
  {
    id: "cross-database-joins",
    title: "Cross-database joins",
    icon: "🌐",
    category: "Data Connections and Modeling",
    difficulty: "Advanced",
    description: "Join tables from different supported connections inside one Tableau data source.",
    example: "Join cloud order data to a local Excel target table using a shared Product ID after validating data types.",
    practiceQuestion: "What must be checked before a cross-database join?",
    correctAnswer: "Join keys, data types, grain, and connector support",
    distractors: ["Only dashboard colors", "Only the worksheet title"],
    hint: "The fields must be compatible and the resulting grain must stay trustworthy.",
    relatedLessons: ["joins", "relationships", "interview-modeling-tradeoffs"],
  },
  {
    id: "relationship-performance-options",
    title: "Relationship performance options",
    icon: "⚙️",
    category: "Data Connections and Modeling",
    difficulty: "Advanced",
    description: "Configure cardinality and referential-integrity assumptions only when the data supports them.",
    example: "Set Orders-to-Customers as many-to-one only after confirming Customer ID is unique in Customers.",
    practiceQuestion: "When should you change relationship performance options from their safe defaults?",
    correctAnswer: "Only when cardinality and referential integrity are known and validated",
    distractors: ["Whenever a view has many marks", "Whenever the workbook uses blue pills"],
    hint: "Incorrect assumptions can produce unreliable results.",
    relatedLessons: ["relationships", "validating-a-worksheet", "interview-modeling-tradeoffs"],
  },
  {
    id: "data-blending",
    title: "Data blending",
    icon: "🫗",
    category: "Data Connections and Modeling",
    difficulty: "Advanced",
    description: "Combine aggregated results from a primary and secondary data source through linking fields.",
    example: "Blend monthly Sales from a database with monthly Targets from a spreadsheet using Month and Region links.",
    practiceQuestion: "At what level are blended secondary-source values combined?",
    correctAnswer: "At an aggregated level based on linking fields in the view",
    distractors: ["As a fixed row-level inner join", "As a union of every source row"],
    hint: "Blending happens after each source is queried separately.",
    relatedLessons: ["relationships", "cross-database-joins", "aggregate-calculations"],
  },
  {
    id: "custom-sql",
    title: "Custom SQL connections",
    icon: "💻",
    category: "Data Connections and Modeling",
    difficulty: "Advanced",
    description: "Use a focused SQL query when the source-side shape cannot be expressed cleanly with Tableau's data model.",
    example: "Return only approved fields and rows from a database view, then validate the query before adding Tableau logic.",
    practiceQuestion: "What is a key risk of unnecessary custom SQL?",
    correctAnswer: "It can add database complexity and make performance harder to diagnose",
    distractors: ["It automatically creates too few worksheets", "It disables every calculation"],
    hint: "Pushdown logic can be powerful, but it should remain understandable and testable.",
    relatedLessons: ["connect-to-data", "performance-recording", "interview-data-quality"],
  },
  {
    id: "extract-filters",
    title: "Extract filters",
    icon: "🧺",
    category: "Data Connections and Modeling",
    difficulty: "Intermediate",
    description: "Limit the rows materialized in an extract to reduce size and focus analysis.",
    example: "Keep only the last three fiscal years when older transactions are outside the workbook's purpose.",
    practiceQuestion: "When is an extract filter applied?",
    correctAnswer: "While defining which source rows are included in the extract",
    distractors: ["After a table calculation is displayed", "Only when a dashboard button is clicked"],
    hint: "It controls what data is stored in the extract itself.",
    relatedLessons: ["extracts-and-live-connections", "data-source-filters", "extract-optimization"],
  },
  {
    id: "text-tables",
    title: "Text tables and crosstabs",
    icon: "🔢",
    category: "Visual Analysis",
    difficulty: "Beginner",
    description: "Present precise values in a structured table when exact lookup matters more than visual pattern detection.",
    example: "Show Region and Category on headers with Sales and Profit values in Measure Values.",
    practiceQuestion: "When is a text table preferable to a chart?",
    correctAnswer: "When readers need to look up exact values across a small grid",
    distractors: ["When showing a geographic route", "When comparing thousands of marks visually"],
    hint: "Tables optimize precision rather than rapid pattern perception.",
    relatedLessons: ["highlight-tables", "chart-selection", "validating-a-worksheet"],
  },
  {
    id: "histograms",
    title: "Histograms",
    icon: "📶",
    category: "Visual Analysis",
    difficulty: "Intermediate",
    description: "Display the distribution of a continuous measure by grouping values into bins.",
    example: "Create Sales bins and count orders in each bin to identify skew and common order sizes.",
    practiceQuestion: "What does the horizontal axis of a histogram usually represent?",
    correctAnswer: "Bins covering ranges of a continuous measure",
    distractors: ["Unrelated geographic locations", "Dashboard navigation targets"],
    hint: "A histogram groups numeric observations into intervals.",
    relatedLessons: ["groups-and-bins", "box-plots", "chart-selection"],
  },
  {
    id: "box-plots",
    title: "Box-and-whisker plots",
    icon: "📦",
    category: "Visual Analysis",
    difficulty: "Intermediate",
    description: "Compare distributions through quartiles, medians, whiskers, and potential outliers.",
    example: "Compare order-level Profit distributions across customer segments instead of relying on averages alone.",
    practiceQuestion: "What does the box in a standard box plot represent?",
    correctAnswer: "The middle 50 percent of the distribution",
    distractors: ["Every value above the mean", "Only the maximum value"],
    hint: "The box spans the interquartile range.",
    relatedLessons: ["histograms", "reference-lines", "chart-selection"],
  },
  {
    id: "bullet-graphs",
    title: "Bullet graphs",
    icon: "🎯",
    category: "Visual Analysis",
    difficulty: "Intermediate",
    description: "Compare actual performance with a target and qualitative ranges in a compact view.",
    example: "Compare actual Sales with Target Sales for each region and use bands for weak, acceptable, and strong performance.",
    practiceQuestion: "What comparison is a bullet graph designed to show?",
    correctAnswer: "A primary measure against a target and performance ranges",
    distractors: ["Two geographic paths", "A list of raw text values only"],
    hint: "It is a compact alternative to gauges and meters.",
    relatedLessons: ["reference-lines", "bar-charts", "show-me"],
  },
  {
    id: "gantt-charts",
    title: "Gantt charts",
    icon: "🗓️",
    category: "Visual Analysis",
    difficulty: "Advanced",
    description: "Show task timing or duration with start positions and Gantt bar sizes.",
    example: "Place Task on Rows, Start Date on Columns, and Duration on Size to compare a project schedule.",
    practiceQuestion: "Which field typically controls the length of a Gantt mark?",
    correctAnswer: "A duration measure on Size",
    distractors: ["A category on Pages", "A target on Shape"],
    hint: "The mark begins at a position and extends by a measurable length.",
    relatedLessons: ["date-calculations", "shelves-and-marks", "chart-selection"],
  },
  {
    id: "numeric-calculations",
    title: "Number calculations",
    icon: "➗",
    category: "Calculations",
    difficulty: "Beginner",
    description: "Use arithmetic, ABS, ROUND, CEILING, FLOOR, and related numeric functions safely.",
    example: "ROUND(SUM([Sales]) / 1000, 1) creates a one-decimal sales value in thousands.",
    practiceQuestion: "Which function returns the absolute magnitude of Profit?",
    correctAnswer: "ABS([Profit])",
    distractors: ["UPPER([Profit])", "DATE([Profit])"],
    hint: "Absolute value removes the negative sign from a number.",
    relatedLessons: ["calculated-fields", "aggregate-calculations", "null-handling"],
  },
  {
    id: "type-conversion-calculations",
    title: "Type conversion calculations",
    icon: "🔁",
    category: "Calculations",
    difficulty: "Intermediate",
    description: "Convert values deliberately with DATE, DATETIME, FLOAT, INT, STR, and boolean expressions.",
    example: "INT([Customer ID Text]) converts a numeric text identifier only after nonnumeric values are handled.",
    practiceQuestion: "Which function converts a numeric value to text?",
    correctAnswer: "STR([Value])",
    distractors: ["SUM([Value])", "DATETRUNC('month', [Value])"],
    hint: "The function name abbreviates string.",
    relatedLessons: ["data-types-and-roles", "string-calculations", "null-handling"],
  },
  {
    id: "null-handling",
    title: "Handling null values",
    icon: "🕳️",
    category: "Calculations",
    difficulty: "Intermediate",
    description: "Detect, replace, or preserve nulls with ISNULL, IFNULL, ZN, and explicit business rules.",
    example: "IFNULL([Region], 'Unknown') labels missing regions without confusing null with a real category.",
    practiceQuestion: "What does ZN([Profit]) do when Profit is null?",
    correctAnswer: "Returns zero",
    distractors: ["Deletes the source row", "Returns the word Null"],
    hint: "ZN is a numeric null-replacement function.",
    relatedLessons: ["logical-calculations", "numeric-calculations", "interview-data-quality"],
  },
  {
    id: "regex-calculations",
    title: "Regular expression calculations",
    icon: "🧬",
    category: "Calculations",
    difficulty: "Advanced",
    description: "Match, extract, and replace structured text patterns with Tableau regular-expression functions.",
    example: "REGEXP_EXTRACT([Order Code], '[A-Z]{2}-[0-9]+') returns a standardized code pattern.",
    practiceQuestion: "Which function returns the substring matching a regular expression?",
    correctAnswer: "REGEXP_EXTRACT",
    distractors: ["DATETRUNC", "WINDOW_SUM"],
    hint: "Its name combines the pattern type with the extraction action.",
    relatedLessons: ["string-calculations", "splitting-fields", "efficient-calculations"],
  },
  {
    id: "quick-table-calculations",
    title: "Quick table calculations",
    icon: "⚡",
    category: "Calculations",
    difficulty: "Intermediate",
    description: "Apply running total, percent of total, rank, moving average, and other common table calculations quickly.",
    example: "Apply Percent of Total to SUM(Sales), then verify that the calculation addresses Category in the intended direction.",
    practiceQuestion: "Where is a quick table calculation computed?",
    correctAnswer: "Across aggregated marks already present in the view",
    distractors: ["Inside the source before the query", "Only in the workbook title"],
    hint: "It is a table calculation, so the view's structure matters.",
    relatedLessons: ["table-calculations", "table-calc-addressing-partitioning", "filter-order-of-operations"],
  },
  {
    id: "table-calc-addressing-partitioning",
    title: "Table calculation addressing and partitioning",
    icon: "🧭",
    category: "Calculations",
    difficulty: "Advanced",
    description: "Control the direction a table calculation moves and the groups where it restarts.",
    example: "Compute a running total across Month while restarting the calculation for each Region.",
    practiceQuestion: "What does partitioning control in a table calculation?",
    correctAnswer: "Where the calculation restarts for separate groups of marks",
    distractors: ["Which data source connector is installed", "The dashboard's fixed width"],
    hint: "Addressing is the direction; partitioning creates the panes or groups.",
    relatedLessons: ["table-calculations", "quick-table-calculations", "lod-vs-table-calc-interview"],
  },
  {
    id: "dimension-filters",
    title: "Dimension filters",
    icon: "🏷️",
    category: "Interactive Analytics",
    difficulty: "Beginner",
    description: "Include, exclude, search, wildcard-match, or conditionally filter categorical members.",
    example: "Keep Consumer and Corporate segments while exposing a compact multiple-values filter card.",
    practiceQuestion: "Which filter is appropriate for choosing specific Region members?",
    correctAnswer: "A dimension filter",
    distractors: ["A measure range filter", "A table-calculation filter"],
    hint: "Region is a categorical dimension.",
    relatedLessons: ["measure-filters", "context-filters", "filter-order-of-operations"],
  },
  {
    id: "measure-filters",
    title: "Measure filters",
    icon: "📏",
    category: "Interactive Analytics",
    difficulty: "Intermediate",
    description: "Filter aggregated measure values with ranges, thresholds, and aggregation-aware conditions.",
    example: "Filter SUM(Sales) to regions above 100,000 after confirming the intended aggregation.",
    practiceQuestion: "Why does aggregation matter in a measure filter?",
    correctAnswer: "The filter evaluates aggregated values such as SUM or AVG",
    distractors: ["Measures can never be filtered", "The filter always evaluates raw text"],
    hint: "The same field can produce different results under SUM and AVG.",
    relatedLessons: ["dimension-filters", "aggregate-calculations", "filter-order-of-operations"],
  },
  {
    id: "context-filters",
    title: "Context filters",
    icon: "🧅",
    category: "Interactive Analytics",
    difficulty: "Advanced",
    description: "Create a primary filter that dependent dimension and Top N filters evaluate against.",
    example: "Add Region to context so a Top 10 Customer filter returns the top customers within the selected region.",
    practiceQuestion: "Why add Region to context before a Top N customer filter?",
    correctAnswer: "So Top N is calculated within the rows that pass the Region filter",
    distractors: ["So Region becomes a measure", "So every filter runs after table calculations"],
    hint: "Dependent filters see only the context subset.",
    relatedLessons: ["filter-order-of-operations", "top-n-filters", "dimension-filters"],
  },
  {
    id: "top-n-filters",
    title: "Top N filters",
    icon: "🏆",
    category: "Interactive Analytics",
    difficulty: "Intermediate",
    description: "Limit a dimension to its highest or lowest members by an aggregated measure.",
    example: "Show the top 10 Customers by SUM(Sales) and parameterize N for controlled exploration.",
    practiceQuestion: "What determines membership in a Top N dimension filter?",
    correctAnswer: "A rank by an aggregated measure",
    distractors: ["Alphabetical order only", "The order worksheets were created"],
    hint: "The Top tab asks for a count and a measure aggregation.",
    relatedLessons: ["context-filters", "dynamic-parameters", "sets"],
  },
  {
    id: "dynamic-parameters",
    title: "Dynamic parameters",
    icon: "🔄",
    category: "Interactive Analytics",
    difficulty: "Advanced",
    description: "Refresh a parameter's current value or allowable-value list from a field when the workbook opens.",
    example: "Populate a Region parameter from the data source so newly added regions can appear after reopening the workbook.",
    practiceQuestion: "When do dynamic parameter values refresh from their configured field?",
    correctAnswer: "When the workbook opens",
    distractors: ["After every selected mark", "Only after deleting the data source"],
    hint: "The refresh behavior is tied to opening the workbook.",
    relatedLessons: ["parameters", "top-n-filters", "dashboard-actions"],
  },
  {
    id: "set-actions",
    title: "Set actions",
    icon: "🎬",
    category: "Interactive Analytics",
    difficulty: "Advanced",
    description: "Update set membership from user selections to support proportional brushing and comparative analysis.",
    example: "Let viewers select states on a map and compare the selected set with all remaining states in a bar chart.",
    practiceQuestion: "What does a set action change?",
    correctAnswer: "The membership of a target set based on interaction",
    distractors: ["The physical database schema", "The workbook file extension"],
    hint: "The interaction updates which members are In or Out.",
    relatedLessons: ["sets", "dashboard-actions", "dashboard-extensions"],
  },
  {
    id: "dashboard-sizing",
    title: "Dashboard sizing",
    icon: "📐",
    category: "Dashboards and Stories",
    difficulty: "Beginner",
    description: "Choose fixed, range, or automatic sizing based on the publishing surface and audience devices.",
    example: "Use a fixed desktop size for a controlled wall display and a phone layout for mobile viewers.",
    practiceQuestion: "When is a fixed dashboard size most appropriate?",
    correctAnswer: "When the display dimensions are known and controlled",
    distractors: ["When every viewer uses an unknown device", "When no worksheet exists"],
    hint: "Fixed sizing is predictable when the target canvas is predictable.",
    relatedLessons: ["dashboard-layout", "device-designer", "accessible-dashboards"],
  },
  {
    id: "tiled-vs-floating",
    title: "Tiled and floating objects",
    icon: "🧩",
    category: "Dashboards and Stories",
    difficulty: "Intermediate",
    description: "Choose tiled layout flow for structure and floating placement for controlled overlays.",
    example: "Keep core charts tiled inside containers and float a small help button over unused corner space.",
    practiceQuestion: "Which object mode participates in the dashboard's layout flow?",
    correctAnswer: "Tiled",
    distractors: ["Floating only", "Hidden only"],
    hint: "Tiled objects push and resize neighboring objects.",
    relatedLessons: ["dashboard-layout", "layout-containers", "show-hide-containers"],
  },
  {
    id: "layout-containers",
    title: "Horizontal and vertical containers",
    icon: "📚",
    category: "Dashboards and Stories",
    difficulty: "Intermediate",
    description: "Use nested containers to create stable rows, columns, spacing, and responsive object relationships.",
    example: "Place KPI cards in a horizontal container above two charts held by a vertical parent container.",
    practiceQuestion: "What is the main benefit of a layout container?",
    correctAnswer: "It manages the position and resizing of grouped dashboard objects",
    distractors: ["It changes source data types", "It creates a database index"],
    hint: "Containers organize objects as a coordinated layout group.",
    relatedLessons: ["dashboard-layout", "tiled-vs-floating", "show-hide-containers"],
  },
  {
    id: "show-hide-containers",
    title: "Show/Hide containers",
    icon: "👁️",
    category: "Dashboards and Stories",
    difficulty: "Intermediate",
    description: "Reveal or collapse filters, help panels, and supporting content with Show/Hide buttons.",
    example: "Place filters in a vertical container and add a button that collapses the panel to give charts more room.",
    practiceQuestion: "Why place tiled objects in a container before hiding them?",
    correctAnswer: "Other objects can fill the released space predictably",
    distractors: ["It converts filters into parameters", "It publishes the workbook automatically"],
    hint: "Container layout controls what happens when an object disappears.",
    relatedLessons: ["layout-containers", "dashboard-sizing", "navigation-objects"],
  },
  {
    id: "navigation-objects",
    title: "Navigation objects",
    icon: "🧭",
    category: "Dashboards and Stories",
    difficulty: "Beginner",
    description: "Create clear buttons that move viewers between dashboards, worksheets, and stories.",
    example: "Add a text navigation button from Executive Summary to Product Detail with a descriptive tooltip.",
    practiceQuestion: "What should a navigation object's label communicate?",
    correctAnswer: "The destination or action viewers should expect",
    distractors: ["The database password", "The number of source rows"],
    hint: "Clear navigation reduces surprise and supports accessibility.",
    relatedLessons: ["dashboard-actions", "stories", "accessible-dashboards"],
  },
  {
    id: "sheet-swapping",
    title: "Sheet swapping patterns",
    icon: "🔀",
    category: "Dashboards and Stories",
    difficulty: "Advanced",
    description: "Use parameters, dynamic zone visibility, or controlled layout patterns to switch analytical views.",
    example: "Let viewers switch between Sales Trend and Profit Trend while keeping filters and dashboard structure stable.",
    practiceQuestion: "What should remain consistent when swapping dashboard views?",
    correctAnswer: "The analytical context, filters, labels, and layout expectations",
    distractors: ["Only the workbook filename", "The source must change for every swap"],
    hint: "A swap should change the view without confusing the user.",
    relatedLessons: ["parameters", "show-hide-containers", "dashboard-actions"],
  },
  {
    id: "accessible-dashboards",
    title: "Accessible dashboards",
    icon: "♿",
    category: "Dashboards and Stories",
    difficulty: "Advanced",
    description: "Design keyboard-friendly, screen-reader-aware dashboards with clear structure and redundant encodings.",
    example: "Use descriptive titles and captions, sufficient contrast, color plus shape, and a logical object focus order.",
    practiceQuestion: "Why use shape or labels in addition to color?",
    correctAnswer: "To communicate meaning without relying on color perception alone",
    distractors: ["To increase query count", "To remove all legends"],
    hint: "Important meaning needs more than one visual cue.",
    relatedLessons: ["dashboard-sizing", "navigation-objects", "dashboard-performance-design"],
  },
  {
    id: "dashboard-performance-design",
    title: "Designing fast dashboards",
    icon: "🚀",
    category: "Dashboards and Stories",
    difficulty: "Advanced",
    description: "Limit view count, mark volume, filters, and expensive interactions while preserving the decision workflow.",
    example: "Replace six competing charts with three focused views and add drill-down navigation for detail on demand.",
    practiceQuestion: "Which dashboard change commonly improves performance?",
    correctAnswer: "Reduce unnecessary views and marks while guiding users to detail",
    distractors: ["Add every available field", "Duplicate each worksheet twice"],
    hint: "Rendering less, with a clearer path, often improves both speed and comprehension.",
    relatedLessons: ["performance-recording", "reducing-marks", "workbook-optimizer"],
  },
  {
    id: "dashboard-extensions",
    title: "Dashboard extensions",
    icon: "🧩",
    category: "Dashboards and Stories",
    difficulty: "Advanced",
    description: "Evaluate and add extension objects when a trusted integration provides necessary dashboard capability.",
    example: "Use an approved extension only after reviewing its permissions, hosting, support, and data-access requirements.",
    practiceQuestion: "What should be reviewed before adding a dashboard extension?",
    correctAnswer: "Trust, permissions, data access, hosting, and support",
    distractors: ["Only the extension's icon color", "Only the worksheet tab order"],
    hint: "Extensions can integrate external capabilities, so governance matters.",
    relatedLessons: ["dashboard-actions", "publishing-workbooks", "interview-publishing-governance"],
  },
  {
    id: "workbook-optimizer",
    title: "Workbook Optimizer",
    icon: "🩺",
    category: "Performance and Publishing",
    difficulty: "Intermediate",
    description: "Run Workbook Optimizer to identify metadata-based performance recommendations before publishing.",
    example: "Review Take action, Needs review, and Passed findings, then validate each recommendation against workbook intent.",
    practiceQuestion: "What is the correct way to use Workbook Optimizer recommendations?",
    correctAnswer: "Review them as guidance and validate whether each applies to the workbook",
    distractors: ["Apply every recommendation without review", "Use it as a replacement for performance measurement"],
    hint: "The rules engine cannot understand every analytical tradeoff.",
    relatedLessons: ["performance-recording", "efficient-calculations", "dashboard-performance-design"],
  },
  {
    id: "reducing-marks",
    title: "Reducing marks and view complexity",
    icon: "✂️",
    category: "Performance and Publishing",
    difficulty: "Intermediate",
    description: "Aggregate, filter, and guide exploration so Tableau renders only the marks required for the question.",
    example: "Start with regional summaries and let viewers navigate to customer detail instead of rendering every customer at once.",
    practiceQuestion: "Why can excessive marks slow a workbook?",
    correctAnswer: "They increase query results, rendering work, and browser interaction cost",
    distractors: ["They change every dimension to text", "They disable extracts"],
    hint: "More data returned and drawn requires more work.",
    relatedLessons: ["dashboard-performance-design", "efficient-filters", "performance-recording"],
  },
  {
    id: "efficient-calculations",
    title: "Efficient calculations",
    icon: "🧮",
    category: "Performance and Publishing",
    difficulty: "Advanced",
    description: "Simplify expensive calculations, aggregate appropriately, and avoid unnecessary high-cost operations.",
    example: "Use a boolean or numeric comparison instead of repeated string logic and calculate only at the grain required.",
    practiceQuestion: "What should guide calculation optimization?",
    correctAnswer: "Measured cost, required grain, and a validated equivalent result",
    distractors: ["Formula length alone", "The color of the calculated field icon"],
    hint: "Performance changes must preserve meaning and be supported by evidence.",
    relatedLessons: ["performance-recording", "workbook-optimizer", "aggregate-calculations"],
  },
  {
    id: "efficient-filters",
    title: "Efficient filter design",
    icon: "🧹",
    category: "Performance and Publishing",
    difficulty: "Advanced",
    description: "Choose selective, understandable filters and avoid expensive domains or redundant filter cards.",
    example: "Use a relative date filter for a rolling period and remove high-cardinality filter cards that add little analytical value.",
    practiceQuestion: "Which filter design is usually easier to compute and use?",
    correctAnswer: "A focused filter aligned with the analytical scope",
    distractors: ["Every field exposed as a filter", "An unbounded list of unique transaction IDs"],
    hint: "Filter only what users need to control.",
    relatedLessons: ["filter-order-of-operations", "reducing-marks", "workbook-optimizer"],
  },
  {
    id: "extract-optimization",
    title: "Optimizing extracts",
    icon: "💾",
    category: "Performance and Publishing",
    difficulty: "Advanced",
    description: "Reduce extract scope, hide unused fields, aggregate when appropriate, and plan refresh behavior.",
    example: "Extract only required fields and three years of rows, then test freshness and workbook speed against requirements.",
    practiceQuestion: "Which change can reduce extract size?",
    correctAnswer: "Filter unnecessary rows and remove unused fields",
    distractors: ["Add duplicate text columns", "Increase dashboard object count"],
    hint: "Store only the data the workbook needs.",
    relatedLessons: ["extract-filters", "incremental-refresh", "extracts-and-live-connections"],
  },
  {
    id: "incremental-refresh",
    title: "Incremental extract refreshes",
    icon: "➕",
    category: "Performance and Publishing",
    difficulty: "Advanced",
    description: "Append newly identified rows to an extract when a full refresh is unnecessarily expensive.",
    example: "Use an increasing Order ID as the incremental key, with scheduled full refreshes for corrected historical rows.",
    practiceQuestion: "What limitation must be planned for with incremental refreshes?",
    correctAnswer: "Changed historical rows may require a full refresh to be updated",
    distractors: ["They cannot add new rows", "They always delete the workbook"],
    hint: "Incremental refresh focuses on rows newer than the recorded key value.",
    relatedLessons: ["extract-optimization", "extracts-and-live-connections", "subscriptions-and-alerts"],
  },
  {
    id: "published-data-sources",
    title: "Published data sources",
    icon: "☁️",
    category: "Performance and Publishing",
    difficulty: "Intermediate",
    description: "Centralize reusable connection, metadata, calculation, and refresh definitions for governed analysis.",
    example: "Publish a certified Sales data source with business-friendly fields so several workbooks reuse the same definitions.",
    practiceQuestion: "What is a primary benefit of a published data source?",
    correctAnswer: "Shared governed definitions and connection management across workbooks",
    distractors: ["Every workbook gets a separate metric definition", "Permissions are no longer needed"],
    hint: "Centralization reduces duplicated data-source logic.",
    relatedLessons: ["publishing-workbooks", "projects-and-permissions", "row-level-security"],
  },
  {
    id: "projects-and-permissions",
    title: "Projects and permissions",
    icon: "🔐",
    category: "Performance and Publishing",
    difficulty: "Advanced",
    description: "Organize content in projects and manage capabilities with group-based, predictable permission rules.",
    example: "Lock project permissions and grant Viewer and Publisher groups only the capabilities required for their roles.",
    practiceQuestion: "Which permission pattern is generally easier to govern?",
    correctAnswer: "Project-level rules assigned to groups",
    distractors: ["Unique rules for every individual workbook and user", "No project structure"],
    hint: "Centralized group rules reduce exceptions and simplify review.",
    relatedLessons: ["publishing-workbooks", "published-data-sources", "interview-publishing-governance"],
  },
  {
    id: "subscriptions-and-alerts",
    title: "Subscriptions and data-driven alerts",
    icon: "🔔",
    category: "Performance and Publishing",
    difficulty: "Intermediate",
    description: "Deliver scheduled view snapshots and notify eligible users when monitored data crosses a threshold.",
    example: "Subscribe leaders to a weekly scorecard and create an alert when regional Profit falls below its threshold.",
    practiceQuestion: "What is the difference between a subscription and a data-driven alert?",
    correctAnswer: "A subscription is scheduled; an alert is triggered by a data condition",
    distractors: ["Subscriptions change row-level security", "Alerts always publish a new workbook"],
    hint: "One follows time, while the other follows a threshold.",
    relatedLessons: ["publishing-workbooks", "projects-and-permissions", "incremental-refresh"],
  },
  {
    id: "requirements-discovery",
    title: "Interview: requirements discovery",
    icon: "🗣️",
    category: "Interview Preparation",
    difficulty: "Intermediate",
    description: "Translate stakeholders, decisions, metrics, grain, freshness, and delivery constraints into Tableau requirements.",
    example: "Ask who decides what, which KPI definition they trust, how often data changes, and what action follows the dashboard.",
    practiceQuestion: "What should be clarified before choosing a chart?",
    correctAnswer: "The decision, audience, metric definition, grain, and constraints",
    distractors: ["Only the preferred color palette", "Only the workbook filename"],
    hint: "Visualization follows a well-defined analytical need.",
    relatedLessons: ["case-study-workflow", "interview-dashboard-design", "interview-storytelling"],
  },
  {
    id: "interview-data-quality",
    title: "Interview: data quality",
    icon: "🧪",
    category: "Interview Preparation",
    difficulty: "Advanced",
    description: "Explain how you profile completeness, uniqueness, validity, consistency, timeliness, and source reconciliation.",
    example: "Check duplicate order keys, missing regions, invalid dates, stale refreshes, and totals against a trusted source.",
    practiceQuestion: "What is a strong first response to a suspicious KPI?",
    correctAnswer: "Validate filters, grain, joins, nulls, refresh timing, and source totals",
    distractors: ["Format the KPI differently", "Publish it and wait for feedback"],
    hint: "Investigate data lineage and calculation scope before presentation.",
    relatedLessons: ["validating-a-worksheet", "null-handling", "interview-validation-testing"],
  },
  {
    id: "interview-modeling-tradeoffs",
    title: "Interview: modeling tradeoffs",
    icon: "⚖️",
    category: "Interview Preparation",
    difficulty: "Advanced",
    description: "Compare relationships, joins, blending, unions, and source-side transformations from grain and performance needs.",
    example: "Choose a relationship for separate fact grains, a join for a known row-level merge, and a union for compatible monthly tables.",
    practiceQuestion: "What should lead a Tableau modeling choice?",
    correctAnswer: "Table grain, required analysis, data quality, and measured performance",
    distractors: ["A preference for one canvas icon", "The number of dashboard colors"],
    hint: "Every modeling option changes how data combines and must be validated.",
    relatedLessons: ["relationships", "joins", "data-blending"],
  },
  {
    id: "interview-dashboard-design",
    title: "Interview: dashboard design",
    icon: "🖼️",
    category: "Interview Preparation",
    difficulty: "Intermediate",
    description: "Explain visual hierarchy, chart choice, interaction, accessibility, device needs, and performance as one design system.",
    example: "Lead with three decision KPIs, provide a trend and comparison, then offer detail through a purposeful action.",
    practiceQuestion: "What makes a dashboard design defensible in an interview?",
    correctAnswer: "Each element supports a user decision and has a validated reason to exist",
    distractors: ["It contains as many charts as possible", "It uses every available color"],
    hint: "Tie layout and interaction back to task, audience, and evidence.",
    relatedLessons: ["dashboard-layout", "accessible-dashboards", "dashboard-performance-design"],
  },
  {
    id: "interview-storytelling",
    title: "Interview: analytical storytelling",
    icon: "📖",
    category: "Interview Preparation",
    difficulty: "Intermediate",
    description: "Structure context, evidence, insight, implication, and action without overstating what the data proves.",
    example: "Explain that declining margin is concentrated in one category, quantify the impact, and propose a testable next action.",
    practiceQuestion: "What should follow an analytical insight?",
    correctAnswer: "Its business implication, uncertainty, and a practical next action",
    distractors: ["An unrelated chart", "A claim of causation without evidence"],
    hint: "A story connects evidence to responsible decision-making.",
    relatedLessons: ["stories", "requirements-discovery", "interview-chart-choice"],
  },
  {
    id: "interview-validation-testing",
    title: "Interview: validation and testing",
    icon: "✅",
    category: "Interview Preparation",
    difficulty: "Advanced",
    description: "Describe repeatable checks for calculations, filters, actions, permissions, refreshes, devices, and published behavior.",
    example: "Test known totals, boundary cases, empty selections, restricted users, phone layouts, and a post-publish refresh.",
    practiceQuestion: "What should a Tableau test plan include?",
    correctAnswer: "Data, calculations, interactions, security, refresh, devices, and published behavior",
    distractors: ["Only a screenshot review", "Only whether the workbook opens"],
    hint: "A production workbook is more than its static visual output.",
    relatedLessons: ["validating-a-worksheet", "row-level-security", "device-designer"],
  },
  {
    id: "interview-publishing-governance",
    title: "Interview: publishing and governance",
    icon: "🏛️",
    category: "Interview Preparation",
    difficulty: "Advanced",
    description: "Explain projects, ownership, permissions, certified sources, refreshes, naming, monitoring, and change control.",
    example: "Publish to a governed project, use groups for access, document ownership, and verify refresh and permission behavior.",
    practiceQuestion: "What should be confirmed immediately after publishing?",
    correctAnswer: "Content location, permissions, credentials, refreshes, and viewer behavior",
    distractors: ["Only the thumbnail color", "Only the authoring font"],
    hint: "Publishing is successful only when the intended audience can use correct, fresh content safely.",
    relatedLessons: ["projects-and-permissions", "published-data-sources", "publishing-workbooks"],
  },
  {
    id: "interview-calculation-troubleshooting",
    title: "Interview: calculation troubleshooting",
    icon: "🛠️",
    category: "Interview Preparation",
    difficulty: "Advanced",
    description: "Diagnose aggregation errors, null behavior, filter order, table-calculation direction, and LOD scope methodically.",
    example: "Reproduce the issue in a small worksheet, inspect grain and aggregation, then add filters one stage at a time.",
    practiceQuestion: "What is the best first step for a wrong Tableau calculation?",
    correctAnswer: "Reduce it to a small validated view and inspect grain, aggregation, and filters",
    distractors: ["Add more nested functions", "Hide the unexpected marks"],
    hint: "Simplify the context before changing the formula.",
    relatedLessons: ["aggregate-calculations", "filter-order-of-operations", "lod-vs-table-calc-interview"],
  },
  {
    id: "interview-portfolio-walkthrough",
    title: "Interview: portfolio walkthrough",
    icon: "💼",
    category: "Interview Preparation",
    difficulty: "Intermediate",
    description: "Present a Tableau project through problem, constraints, data, decisions, validation, impact, and reflection.",
    example: "Explain why the dashboard existed, what you personally built, how you validated it, and what changed after feedback.",
    practiceQuestion: "What should a strong portfolio walkthrough emphasize?",
    correctAnswer: "Your reasoning, ownership, validation, tradeoffs, and measurable outcome",
    distractors: ["Only the final screenshot", "Only the number of worksheets"],
    hint: "Interviewers need evidence of how you work, not only what the result looks like.",
    relatedLessons: ["case-study-workflow", "requirements-discovery", "interview-storytelling"],
  },
];
