export type TableauRoadmapStage = {
  id: string;
  title: string;
  icon: string;
  description: string;
  lessonIds: string[];
};

export const tableauRoadmap: TableauRoadmapStage[] = [
  {
    id: "foundations",
    title: "1. Tableau foundations",
    icon: "🌱",
    description: "Learn the workspace, field roles, visual grammar, and first connection workflow.",
    lessonIds: [
      "tableau-workspace",
      "connect-to-data",
      "dimensions-and-measures",
      "discrete-and-continuous",
      "shelves-and-marks",
      "workbook-structure",
      "show-me",
      "organize-fields",
      "sorting-and-formatting",
      "aliases-and-default-properties",
      "metadata-and-describe",
      "tableau-file-types",
      "validating-a-worksheet",
    ],
  },
  {
    id: "modeling",
    title: "2. Connect and model data",
    icon: "🔗",
    description: "Validate fields and combine tables with the correct logical or physical model.",
    lessonIds: [
      "data-types-and-roles",
      "relationships",
      "joins",
      "unions",
      "data-source-filters",
      "data-interpreter",
      "pivoting-data",
      "splitting-fields",
      "cross-database-joins",
      "relationship-performance-options",
      "data-blending",
      "custom-sql",
      "extract-filters",
    ],
  },
  {
    id: "visual-analysis",
    title: "3. Visual analysis",
    icon: "📊",
    description: "Match business questions to readable comparisons, trends, relationships, and maps.",
    lessonIds: [
      "bar-charts",
      "line-charts",
      "scatter-plots",
      "maps",
      "highlight-tables",
      "treemaps",
      "dual-axis-charts",
      "chart-selection",
      "text-tables",
      "histograms",
      "box-plots",
      "bullet-graphs",
      "gantt-charts",
    ],
  },
  {
    id: "calculations",
    title: "4. Calculations",
    icon: "🧮",
    description: "Build reliable business logic from row-level fields through LOD expressions.",
    lessonIds: [
      "calculated-fields",
      "string-calculations",
      "date-calculations",
      "logical-calculations",
      "aggregate-calculations",
      "table-calculations",
      "level-of-detail-expressions",
      "numeric-calculations",
      "type-conversion-calculations",
      "null-handling",
      "regex-calculations",
      "quick-table-calculations",
      "table-calc-addressing-partitioning",
    ],
  },
  {
    id: "interactive-analytics",
    title: "5. Interactive analytics",
    icon: "🎛️",
    description: "Control filters, parameters, sets, analytics objects, trends, and forecasts.",
    lessonIds: [
      "filter-order-of-operations",
      "parameters",
      "sets",
      "groups-and-bins",
      "reference-lines",
      "trend-lines",
      "forecasting",
      "dimension-filters",
      "measure-filters",
      "context-filters",
      "top-n-filters",
      "dynamic-parameters",
      "set-actions",
    ],
  },
  {
    id: "dashboards",
    title: "6. Dashboards and stories",
    icon: "🖼️",
    description: "Compose responsive layouts and purposeful interactions for guided decision-making.",
    lessonIds: [
      "dashboard-layout",
      "dashboard-actions",
      "device-designer",
      "stories",
      "dashboard-sizing",
      "tiled-vs-floating",
      "layout-containers",
      "show-hide-containers",
      "navigation-objects",
      "sheet-swapping",
      "accessible-dashboards",
      "dashboard-performance-design",
      "dashboard-extensions",
    ],
  },
  {
    id: "production",
    title: "7. Production delivery",
    icon: "☁️",
    description: "Balance freshness, performance, publishing, permissions, and row-level security.",
    lessonIds: [
      "extracts-and-live-connections",
      "performance-recording",
      "publishing-workbooks",
      "row-level-security",
      "workbook-optimizer",
      "reducing-marks",
      "efficient-calculations",
      "efficient-filters",
      "extract-optimization",
      "incremental-refresh",
      "published-data-sources",
      "projects-and-permissions",
      "subscriptions-and-alerts",
    ],
  },
  {
    id: "interview",
    title: "8. Interview ready",
    icon: "🎓",
    description: "Explain tradeoffs clearly and structure complete Tableau case-study answers.",
    lessonIds: [
      "interview-chart-choice",
      "performance-interview",
      "lod-vs-table-calc-interview",
      "case-study-workflow",
      "requirements-discovery",
      "interview-data-quality",
      "interview-modeling-tradeoffs",
      "interview-dashboard-design",
      "interview-storytelling",
      "interview-validation-testing",
      "interview-publishing-governance",
      "interview-calculation-troubleshooting",
      "interview-portfolio-walkthrough",
    ],
  },
];

export type TableauShortcut = {
  group: "Workbook" | "Authoring" | "Selection";
  action: string;
  windows: string;
  mac: string;
};

// Verified against Tableau's current Desktop and Web Authoring shortcut guide.
export const tableauShortcuts: TableauShortcut[] = [
  { group: "Workbook", action: "New workbook", windows: "Ctrl + N", mac: "⌘ + N" },
  { group: "Workbook", action: "New worksheet", windows: "Ctrl + M", mac: "⌘ + T" },
  { group: "Workbook", action: "Open workbook", windows: "Ctrl + O", mac: "⌘ + O" },
  { group: "Workbook", action: "Save workbook", windows: "Ctrl + S", mac: "⌘ + S" },
  { group: "Workbook", action: "Describe sheet", windows: "Ctrl + E", mac: "⌘ + E" },
  { group: "Authoring", action: "Undo", windows: "Ctrl + Z", mac: "⌘ + Z" },
  { group: "Authoring", action: "Redo", windows: "Ctrl + Y", mac: "⌘ + Shift + Z" },
  { group: "Authoring", action: "Copy a field while dragging", windows: "Ctrl + drag", mac: "⌘ + drag" },
  { group: "Authoring", action: "Clear current worksheet", windows: "Alt + Shift + Backspace", mac: "Option + Shift + Delete" },
  { group: "Authoring", action: "Toggle dashboard grid", windows: "G", mac: "G" },
  { group: "Authoring", action: "Toggle Dashboard and Layout tabs", windows: "T", mac: "T" },
  { group: "Selection", action: "Rectangular selection tool", windows: "A", mac: "A" },
  { group: "Selection", action: "Lasso selection tool", windows: "D", mac: "D" },
  { group: "Selection", action: "Radial selection tool", windows: "S", mac: "S" },
  { group: "Selection", action: "Select all data", windows: "Ctrl + A", mac: "⌘ + A" },
  { group: "Selection", action: "Clear mark selection", windows: "Esc", mac: "Esc" },
];
