import { tableauLessonExpansion } from "./tableauLessonExpansion";

const tableauDefinitions: Record<string, string> = {
  "tableau-workspace": "The Tableau workspace is the authoring area containing the Data pane, shelves, cards, toolbar, and view canvas.",
  "connect-to-data": "Connecting to data establishes a Tableau data source from a file, database, published source, or cloud application.",
  "dimensions-and-measures": "Dimensions describe and segment records, while measures are values Tableau can aggregate for analysis.",
  "discrete-and-continuous": "Discrete fields create headers or panes, while continuous fields create axes across a flowing range.",
  "shelves-and-marks": "Shelves and the Marks card assign fields to visual roles such as position, color, size, label, detail, and tooltip.",
  "data-types-and-roles": "Data types and field roles tell Tableau how values should be interpreted as text, numbers, dates, geography, dimensions, or measures.",
  relationships: "A Tableau relationship connects logical tables while allowing each table to retain its native level of detail.",
  joins: "A physical join combines table rows using matching keys and a selected join type at the data-source layer.",
  unions: "A union stacks rows from tables with compatible columns into one logical table.",
  "data-source-filters": "A data-source filter restricts records before worksheets query the shared Tableau data source.",
  "bar-charts": "A bar chart compares category values using lengths measured from a common baseline.",
  "line-charts": "A line chart connects ordered marks to show change and trend across a sequence such as time.",
  "scatter-plots": "A scatter plot places paired numeric values as marks to reveal association, clusters, and outliers.",
  maps: "A Tableau map encodes geographic fields as marks so spatial patterns and locations can be explored.",
  "highlight-tables": "A highlight table combines a text table with color encoding to emphasize magnitude across a grid.",
  treemaps: "A treemap represents hierarchical part-to-whole values with nested rectangles sized and colored by measures.",
  "dual-axis-charts": "A dual-axis chart overlays two measures on separate axes so their trends or scales can be compared.",
  "chart-selection": "Chart selection matches a visual form to the analytical task, audience, data structure, and decision.",
  "calculated-fields": "A calculated field is a reusable Tableau expression that derives values from fields, constants, and functions.",
  "string-calculations": "String calculations transform, search, extract, or combine text values in a Tableau expression.",
  "date-calculations": "Date calculations use Tableau date functions to create, compare, truncate, or shift calendar values.",
  "logical-calculations": "Logical calculations evaluate conditions and return values based on Boolean rules such as IF or CASE.",
  "aggregate-calculations": "An aggregate calculation summarizes records with functions such as SUM, AVG, MIN, MAX, or COUNT.",
  "table-calculations": "A table calculation computes over the marks already returned to a view using its displayed addressing and partitioning.",
  "level-of-detail-expressions": "A level-of-detail expression fixes, includes, or excludes the data grain used for a calculation independently of the view layout.",
  "filter-order-of-operations": "Filter order of operations is Tableau's sequence for applying extract, data-source, context, dimension, measure, and table filters.",
  parameters: "A parameter is a user-controlled value that can drive calculations, filters, reference lines, or other workbook behavior.",
  sets: "A set is a named subset of dimension members that can be used for comparison, filtering, or set actions.",
  "groups-and-bins": "Groups combine members into custom categories, while bins divide continuous numeric values into intervals.",
  "reference-lines": "Reference lines and bands add benchmark values or ranges to a view for comparison.",
  "trend-lines": "A trend line fits a statistical relationship to marks to summarize direction and support interpretation.",
  forecasting: "Tableau forecasting estimates future values from historical time-series patterns and displays uncertainty.",
  "dashboard-layout": "Dashboard layout arranges worksheets, filters, legends, text, and containers into an interactive canvas.",
  "dashboard-actions": "Dashboard actions connect user interactions to navigation, filtering, highlighting, or parameter changes.",
  "device-designer": "Device layouts adapt a dashboard's arrangement and sizing for desktop, tablet, or phone screens.",
  stories: "A Tableau story is a sequence of sheets or dashboards that presents an analytical narrative through points.",
  "extracts-and-live-connections": "Live connections query the source directly, while extracts store an optimized snapshot for analysis and refresh.",
  "performance-recording": "Performance recording captures workbook timing so slow queries, calculations, rendering, or layout can be diagnosed.",
  "publishing-workbooks": "Publishing a workbook deploys its views and settings to Tableau Server or Cloud for governed sharing.",
  "row-level-security": "Row-level security restricts records according to the signed-in viewer's entitlements or identity.",
  "interview-chart-choice": "Chart-choice reasoning explains how the business question and audience determine an effective visual encoding.",
  "performance-interview": "Workbook-performance diagnosis identifies measurable bottlenecks across data, calculations, filters, marks, and dashboards.",
  "lod-vs-table-calc-interview": "LOD versus table-calculation reasoning distinguishes data-query grain calculations from computations over displayed marks.",
  "case-study-workflow": "A Tableau case-study workflow moves from requirements and data validation through modeling, insight, delivery, and recommendation.",
  "workbook-structure": "Workbook structure organizes worksheets, dashboards, stories, and data sources inside one Tableau workbook.",
  "show-me": "Show Me recommends chart forms based on the number and types of fields currently selected.",
  "organize-fields": "Organizing fields uses folders, hierarchies, hidden fields, and search to make the Data pane manageable.",
  "sorting-and-formatting": "Sorting and formatting control mark order, number display, axes, labels, lines, and visual readability.",
  "aliases-and-default-properties": "Aliases change displayed member labels, while default properties provide reusable field formatting and behavior.",
  "metadata-and-describe": "Describe and View Data expose field metadata, filters, summaries, and source rows for inspection.",
  "tableau-file-types": "Tableau file types distinguish workbook definitions, packaged workbooks, data sources, and extracts.",
  "validating-a-worksheet": "Worksheet validation reconciles grain, filters, aggregations, totals, nulls, and marks against a trusted source.",
  "data-interpreter": "Data Interpreter identifies the useful tabular region in a human-formatted spreadsheet before analysis.",
  "pivoting-data": "Pivoting data reshapes repeated columns into field-name and field-value rows for tidy analysis.",
  "splitting-fields": "Splitting fields separates delimited text into useful values using automatic or custom rules.",
  "cross-database-joins": "A cross-database join combines tables from different supported connections using compatible keys.",
  "relationship-performance-options": "Relationship performance options declare cardinality and referential-integrity assumptions that Tableau can use safely when validated.",
  "data-blending": "Data blending combines aggregated results from a primary and secondary source through linking fields in a view.",
  "custom-sql": "Custom SQL supplies a focused source query when the required shape cannot be expressed cleanly through Tableau's model interface.",
  "extract-filters": "An extract filter limits which source rows are materialized in an extract.",
  "text-tables": "A text table or crosstab presents exact values in a structured grid for lookup and comparison.",
  histograms: "A histogram groups numeric observations into bins to show a distribution's shape and spread.",
  "box-plots": "A box-and-whisker plot summarizes a distribution with quartiles, median, whiskers, and potential outliers.",
  "bullet-graphs": "A bullet graph compares a primary measure with a target and qualitative performance ranges.",
  "gantt-charts": "A Gantt chart represents duration and timing with bars positioned along a time axis.",
  "numeric-calculations": "Numeric calculations apply arithmetic and number functions to derive quantitative values.",
  "type-conversion-calculations": "Type conversion calculations explicitly change a value's interpretation between Tableau data types.",
  "null-handling": "Null handling defines how missing values are detected, replaced, filtered, or displayed in calculations and views.",
  "regex-calculations": "Regular-expression calculations match, extract, or replace text patterns using regex functions.",
  "quick-table-calculations": "Quick table calculations apply common summaries such as running total, percent of total, rank, or moving average to a view.",
  "table-calc-addressing-partitioning": "Table-calculation addressing defines the direction of computation, while partitioning defines the independent groups it restarts within.",
  "dimension-filters": "A dimension filter keeps or excludes categorical members before the view is displayed.",
  "measure-filters": "A measure filter keeps aggregated results that meet a numeric condition after aggregation.",
  "context-filters": "A context filter creates a filtered subset that other dimension filters evaluate against.",
  "top-n-filters": "A Top N filter retains the highest or lowest members according to a selected measure or ranking rule.",
  "dynamic-parameters": "A dynamic parameter refreshes its allowed values from data or a field so controls stay current.",
  "set-actions": "A set action changes set membership when a viewer selects or interacts with marks.",
  "dashboard-sizing": "Dashboard sizing defines the canvas dimensions and scaling behavior for the target display.",
  "tiled-vs-floating": "Tiled objects participate in a layout grid, while floating objects can be positioned freely above it.",
  "layout-containers": "Layout containers group dashboard objects horizontally or vertically to control alignment and resizing.",
  "show-hide-containers": "Show/Hide containers reveal or collapse grouped dashboard content through an interaction.",
  "navigation-objects": "Navigation objects let viewers move between dashboards, sheets, stories, or external destinations.",
  "sheet-swapping": "Sheet swapping changes which worksheet occupies a dashboard region in response to a parameter or action.",
  "accessible-dashboards": "Accessible dashboards use readable contrast, labels, order, descriptions, and keyboard-friendly interactions.",
  "dashboard-performance-design": "Fast dashboard design limits unnecessary queries, marks, filters, and objects while preserving the analytical goal.",
  "dashboard-extensions": "Dashboard extensions embed supported external applications or custom functionality inside a Tableau dashboard.",
  "workbook-optimizer": "Workbook Optimizer reviews a workbook for design patterns that may reduce performance or maintainability.",
  "reducing-marks": "Reducing marks lowers view complexity by limiting unnecessary detail, granularity, or overplotted records.",
  "efficient-calculations": "Efficient calculations reduce repeated or expensive expression work while preserving the required result.",
  "efficient-filters": "Efficient filter design limits data early and avoids excessive high-cardinality controls or redundant conditions.",
  "extract-optimization": "Extract optimization improves snapshot size and query speed through appropriate filters, aggregation, and refresh choices.",
  "incremental-refresh": "Incremental extract refresh updates only new or changed partitions instead of rebuilding the full extract.",
  "published-data-sources": "A published data source centralizes a governed connection, metadata, and refreshable data for reuse.",
  "projects-and-permissions": "Projects and permissions organize published content and control who can view, edit, or administer it.",
  "subscriptions-and-alerts": "Subscriptions and data-driven alerts notify users when a view or monitored condition needs attention.",
  "requirements-discovery": "Requirements discovery clarifies the decision, audience, metrics, grain, filters, and delivery constraints before building.",
  "interview-data-quality": "Data-quality reasoning checks completeness, validity, duplicates, grain, definitions, and reconciliation before trusting a view.",
  "interview-modeling-tradeoffs": "Modeling tradeoffs compare relationships, joins, blends, extracts, and live sources against grain and performance needs.",
  "interview-dashboard-design": "Dashboard-design reasoning connects hierarchy, audience, interaction, accessibility, and visual choice to the decision.",
  "interview-storytelling": "Analytical storytelling turns validated findings into a sequence of context, evidence, insight, and recommended action.",
  "interview-validation-testing": "Validation and testing confirm calculations, filters, totals, edge cases, and rendering before publication.",
  "interview-publishing-governance": "Publishing governance covers permissions, certified sources, credentials, refresh schedules, ownership, and change control.",
  "interview-calculation-troubleshooting": "Calculation troubleshooting isolates type, scope, aggregation, null, and table-context causes before changing an expression.",
  "interview-portfolio-walkthrough": "A portfolio walkthrough explains the business question, data work, design decisions, validation, insight, and impact of a Tableau project.",
};

export const tableauCategories = [
  "Tableau Foundations",
  "Data Connections and Modeling",
  "Visual Analysis",
  "Calculations",
  "Interactive Analytics",
  "Dashboards and Stories",
  "Performance and Publishing",
  "Interview Preparation",
] as const;

export const tableauDifficulties = [
  "Beginner",
  "Intermediate",
  "Advanced",
] as const;

export type TableauCategory = (typeof tableauCategories)[number];
export type TableauDifficulty = (typeof tableauDifficulties)[number];

export type TableauLesson = {
  id: string;
  title: string;
  icon: string;
  category: TableauCategory;
  difficulty: TableauDifficulty;
  description: string;
  definition?: string;
  explanation: string;
  steps: string[];
  example: string;
  memoryTrick: string;
  whenToUse: string[];
  commonMistakes: string[];
  interviewQuestions: string[];
  practiceQuestion: string;
  practiceOptions: string[];
  correctAnswer: string;
  hint: string;
  xpReward: number;
  relatedLessons: string[];
};

export type TableauLessonSeed = Pick<
  TableauLesson,
  | "id"
  | "title"
  | "icon"
  | "category"
  | "difficulty"
  | "description"
  | "example"
  | "hint"
> & {
  practiceQuestion: string;
  correctAnswer: string;
  distractors: [string, string];
} & Partial<
    Pick<
      TableauLesson,
      | "explanation"
      | "steps"
      | "memoryTrick"
      | "whenToUse"
      | "commonMistakes"
      | "interviewQuestions"
      | "xpReward"
      | "relatedLessons"
    >
  >;

function arrangeOptions(
  id: string,
  correct: string,
  distractors: [string, string],
) {
  const values = [correct, ...distractors];
  const offset = Array.from(id).reduce((total, character) => total + character.charCodeAt(0), 0) % values.length;
  return [...values.slice(offset), ...values.slice(0, offset)];
}

function createLesson(seed: TableauLessonSeed): TableauLesson {
  const xpReward =
    seed.difficulty === "Beginner"
      ? 20
      : seed.difficulty === "Intermediate"
        ? 30
        : 40;

  return {
    ...seed,
    definition: tableauDefinitions[seed.id],
    explanation:
      seed.explanation ??
      `${seed.description} In Tableau, the goal is to keep the business question, the data grain, and the visual encoding aligned so the result stays trustworthy.`,
    steps: seed.steps ?? [
      "Start with a clear business question and confirm the fields needed to answer it.",
      "Apply the concept in a worksheet and inspect how Tableau represents the result.",
      "Validate filters, marks, totals, and labels before formatting or sharing the view.",
    ],
    memoryTrick:
      seed.memoryTrick ??
      `${seed.title}: question first, fields second, validation before decoration.`,
    whenToUse: seed.whenToUse ?? [
      `When ${seed.title.toLowerCase()} directly supports the analytical question.`,
      "When the result can be checked against the source data or a known total.",
    ],
    commonMistakes: seed.commonMistakes ?? [
      "Choosing fields before defining the business question.",
      "Formatting the view before validating its grain, filters, and totals.",
    ],
    interviewQuestions: seed.interviewQuestions ?? [
      `How would you explain ${seed.title.toLowerCase()} to a business stakeholder?`,
      `What would you validate before publishing a view that uses ${seed.title.toLowerCase()}?`,
    ],
    practiceOptions: arrangeOptions(seed.id, seed.correctAnswer, seed.distractors),
    xpReward: seed.xpReward ?? xpReward,
    relatedLessons: seed.relatedLessons ?? [],
  };
}

const seeds: TableauLessonSeed[] = [
  {
    id: "tableau-workspace",
    title: "The Tableau workspace",
    icon: "🧭",
    category: "Tableau Foundations",
    difficulty: "Beginner",
    description: "Navigate the Data pane, Analytics pane, shelves, cards, toolbar, and worksheet canvas.",
    example: "Use the Data pane to locate Region and Sales, then place them on Rows and Columns to begin a view.",
    practiceQuestion: "Where do you usually find dimensions and measures while authoring a worksheet?",
    correctAnswer: "The Data pane",
    distractors: ["The Story navigator", "The dashboard Layout pane"],
    hint: "It is the pane that lists fields from the active data source.",
    relatedLessons: ["shelves-and-marks", "dimensions-and-measures"],
  },
  {
    id: "connect-to-data",
    title: "Connecting to data",
    icon: "🔌",
    category: "Tableau Foundations",
    difficulty: "Beginner",
    description: "Connect Tableau to files, databases, published sources, and cloud applications.",
    example: "Connect to an Excel sales file, select the Orders sheet, and review the data grid before opening a worksheet.",
    practiceQuestion: "What should you inspect immediately after creating a new connection?",
    correctAnswer: "Field names, data types, and sample rows",
    distractors: ["Dashboard padding and fonts", "Only the workbook title"],
    hint: "Validate the structure before building a visualization.",
    relatedLessons: ["data-types-and-roles", "extracts-and-live-connections"],
  },
  {
    id: "dimensions-and-measures",
    title: "Dimensions and measures",
    icon: "⚖️",
    category: "Tableau Foundations",
    difficulty: "Beginner",
    description: "Understand how dimensions slice data and measures are aggregated for analysis.",
    example: "Region divides the view into categories while SUM(Sales) produces a value for each region.",
    practiceQuestion: "Which field is most likely a measure?",
    correctAnswer: "Sales amount",
    distractors: ["Customer segment", "Product category"],
    hint: "Measures are usually numeric values that can be aggregated.",
    relatedLessons: ["discrete-and-continuous", "aggregate-calculations"],
  },
  {
    id: "discrete-and-continuous",
    title: "Discrete and continuous fields",
    icon: "🟦",
    category: "Tableau Foundations",
    difficulty: "Beginner",
    description: "Recognize blue discrete headers and green continuous axes and choose the right role for a view.",
    example: "A discrete Month creates twelve headers; a continuous Month creates a time axis.",
    practiceQuestion: "What does a green pill normally create in the view?",
    correctAnswer: "A continuous axis",
    distractors: ["A discrete header only", "A new data connection"],
    hint: "Green represents a continuous range in Tableau.",
    relatedLessons: ["dimensions-and-measures", "line-charts"],
  },
  {
    id: "shelves-and-marks",
    title: "Shelves and the Marks card",
    icon: "🗂️",
    category: "Tableau Foundations",
    difficulty: "Beginner",
    description: "Use Rows, Columns, Filters, Pages, and Marks properties to define a visual encoding.",
    example: "Place Region on Rows, SUM(Sales) on Columns, and Profit on Color to reveal regional performance.",
    practiceQuestion: "Where would you place Profit to encode positive and negative performance with color?",
    correctAnswer: "Color on the Marks card",
    distractors: ["The Pages shelf", "The workbook title"],
    hint: "The Marks card controls color, size, label, detail, and tooltip.",
    relatedLessons: ["tableau-workspace", "bar-charts"],
  },
  {
    id: "data-types-and-roles",
    title: "Data types and field roles",
    icon: "🏷️",
    category: "Data Connections and Modeling",
    difficulty: "Beginner",
    description: "Validate text, number, date, geographic, dimension, and measure assignments.",
    example: "Change Order Date from text to Date and assign State a geographic role before mapping it.",
    practiceQuestion: "Why must Order Date have a date data type?",
    correctAnswer: "So Tableau can use date parts, date values, and time functions correctly",
    distractors: ["So every date becomes a measure", "So all rows are automatically filtered"],
    hint: "The data type determines which operations Tableau can perform.",
    relatedLessons: ["connect-to-data", "date-calculations"],
  },
  {
    id: "relationships",
    title: "Relationships",
    icon: "🔗",
    category: "Data Connections and Modeling",
    difficulty: "Intermediate",
    description: "Relate logical tables while preserving each table's native level of detail.",
    explanation: "Relationships connect logical tables without flattening them up front. Tableau determines the necessary joins at query time from the fields used in the view, which helps preserve each table's grain.",
    example: "Relate Orders to Returns by Order ID so measures remain at their original grains until a worksheet needs both tables.",
    practiceQuestion: "What is the main modeling benefit of a relationship?",
    correctAnswer: "It preserves table grain and resolves joins based on the fields used",
    distractors: ["It always performs a fixed inner join", "It permanently duplicates every matching row"],
    hint: "Relationships are logical and context-aware rather than fixed physical merges.",
    relatedLessons: ["joins", "level-of-detail-expressions"],
  },
  {
    id: "joins",
    title: "Physical joins",
    icon: "🧩",
    category: "Data Connections and Modeling",
    difficulty: "Intermediate",
    description: "Combine physical tables with fixed inner, left, right, or full join logic.",
    example: "Left join a customer lookup to Orders when every order must remain even if a customer attribute is missing.",
    practiceQuestion: "When is a left join appropriate?",
    correctAnswer: "When every row from the left table must remain",
    distractors: ["When only unmatched rows should remain", "When both tables must keep their separate grains"],
    hint: "Think about which table's rows are mandatory.",
    relatedLessons: ["relationships", "unions"],
  },
  {
    id: "unions",
    title: "Unions",
    icon: "📚",
    category: "Data Connections and Modeling",
    difficulty: "Beginner",
    description: "Append tables with matching structures to create one longer table.",
    example: "Union January, February, and March sales sheets that share the same columns.",
    practiceQuestion: "What operation combines tables by adding rows?",
    correctAnswer: "A union",
    distractors: ["A relationship", "A calculated field"],
    hint: "The tables should have compatible columns and are stacked vertically.",
    relatedLessons: ["joins", "data-source-filters"],
  },
  {
    id: "data-source-filters",
    title: "Data source filters",
    icon: "🛡️",
    category: "Data Connections and Modeling",
    difficulty: "Intermediate",
    description: "Restrict the records available to every worksheet that uses a data source.",
    example: "Limit a regional workbook to the current fiscal year before analysts create sheets.",
    practiceQuestion: "What is the scope of a data source filter?",
    correctAnswer: "All worksheets using that data source",
    distractors: ["Only one selected mark", "Only the active dashboard object"],
    hint: "It is applied before ordinary worksheet filters.",
    relatedLessons: ["filter-order-of-operations", "extracts-and-live-connections"],
  },
  {
    id: "bar-charts",
    title: "Bar charts",
    icon: "📊",
    category: "Visual Analysis",
    difficulty: "Beginner",
    description: "Compare categorical values accurately with a shared baseline and sorted bars.",
    example: "Compare SUM(Sales) by Sub-Category and sort descending to reveal the strongest products.",
    practiceQuestion: "Which task is best suited to a bar chart?",
    correctAnswer: "Comparing sales across product categories",
    distractors: ["Showing a precise geographic route", "Explaining a relationship between two continuous measures"],
    hint: "Bars excel at categorical comparison.",
    relatedLessons: ["shelves-and-marks", "highlight-tables"],
  },
  {
    id: "line-charts",
    title: "Line charts",
    icon: "📈",
    category: "Visual Analysis",
    difficulty: "Beginner",
    description: "Show change over an ordered time axis and compare trends without clutter.",
    example: "Plot monthly Sales as a continuous date and add Category to Color for trend comparison.",
    practiceQuestion: "Which field belongs on Columns for a monthly sales trend?",
    correctAnswer: "A continuous Month of Order Date",
    distractors: ["Customer Name as a discrete header", "Profit on Shape only"],
    hint: "A continuous date creates an axis suitable for a trend.",
    relatedLessons: ["discrete-and-continuous", "forecasting"],
  },
  {
    id: "scatter-plots",
    title: "Scatter plots",
    icon: "✨",
    category: "Visual Analysis",
    difficulty: "Intermediate",
    description: "Examine the relationship, clusters, and outliers between two quantitative measures.",
    example: "Place Sales on Columns and Profit on Rows, then add Customer to Detail for one mark per customer.",
    practiceQuestion: "What must be added to create one scatter-plot mark per customer?",
    correctAnswer: "Customer on Detail",
    distractors: ["Customer on Pages", "Customer in the workbook title"],
    hint: "Detail changes the level of detail without adding a visual encoding.",
    relatedLessons: ["trend-lines", "sets"],
  },
  {
    id: "maps",
    title: "Maps and geographic roles",
    icon: "🗺️",
    category: "Visual Analysis",
    difficulty: "Intermediate",
    description: "Build symbol and filled maps with valid geographic roles and appropriate measures.",
    example: "Assign State a geographic role, double-click it, and place Sales on Color and Profit on Tooltip.",
    practiceQuestion: "What should you check first when Tableau cannot map a location field?",
    correctAnswer: "Its geographic role and unmatched locations",
    distractors: ["The dashboard font", "The number of worksheet tabs"],
    hint: "Mapping depends on geographic interpretation.",
    relatedLessons: ["data-types-and-roles", "dashboard-actions"],
  },
  {
    id: "highlight-tables",
    title: "Highlight tables",
    icon: "🟪",
    category: "Visual Analysis",
    difficulty: "Beginner",
    description: "Use color in a text table to reveal high, low, and unusual values across two dimensions.",
    example: "Place Region on Rows, Category on Columns, and Profit on Color and Label.",
    practiceQuestion: "What does a highlight table add to a crosstab?",
    correctAnswer: "Color encoding that makes value patterns easier to scan",
    distractors: ["A second data source", "A fixed physical join"],
    hint: "It combines a table layout with encoded color.",
    relatedLessons: ["bar-charts", "treemaps"],
  },
  {
    id: "treemaps",
    title: "Treemaps",
    icon: "🧱",
    category: "Visual Analysis",
    difficulty: "Intermediate",
    description: "Show hierarchical part-to-whole patterns with nested rectangles sized by a measure.",
    example: "Size rectangles by Sales, color by Profit, and nest Sub-Category within Category.",
    practiceQuestion: "Which Marks property normally represents magnitude in a treemap?",
    correctAnswer: "Size",
    distractors: ["Pages", "Caption"],
    hint: "Larger rectangles represent larger values.",
    relatedLessons: ["highlight-tables", "dashboard-layout"],
  },
  {
    id: "dual-axis-charts",
    title: "Dual-axis charts",
    icon: "📉",
    category: "Visual Analysis",
    difficulty: "Advanced",
    description: "Layer two measures in the same pane while controlling mark types and axis synchronization.",
    example: "Layer Sales bars with Profit Ratio circles, then keep separate scales when the units differ.",
    practiceQuestion: "When should dual axes not be synchronized?",
    correctAnswer: "When the measures use different units or meanings",
    distractors: ["Whenever both measures are numeric", "Whenever the chart has a title"],
    hint: "Synchronization implies that equal positions represent comparable values.",
    relatedLessons: ["line-charts", "aggregate-calculations"],
  },
  {
    id: "chart-selection",
    title: "Choosing the right chart",
    icon: "🎯",
    category: "Visual Analysis",
    difficulty: "Intermediate",
    description: "Match comparison, trend, distribution, relationship, and spatial questions to suitable visuals.",
    example: "Use a line for time, bars for category comparison, and a scatter plot for measure relationships.",
    practiceQuestion: "Which chart best compares profit across eight categories?",
    correctAnswer: "A sorted bar chart",
    distractors: ["A crowded pie chart", "A geographic symbol map without location data"],
    hint: "Use a shared baseline for accurate category comparison.",
    relatedLessons: ["bar-charts", "line-charts", "scatter-plots"],
  },
  {
    id: "calculated-fields",
    title: "Calculated fields",
    icon: "🧮",
    category: "Calculations",
    difficulty: "Beginner",
    description: "Create reusable row-level or aggregate business logic inside the workbook.",
    example: "Create [Profit Ratio] as SUM([Profit]) / SUM([Sales]) for a view-level ratio.",
    practiceQuestion: "Which formula calculates an aggregate profit ratio?",
    correctAnswer: "SUM([Profit]) / SUM([Sales])",
    distractors: ["[Profit] + [Sales]", "COUNT([Profit]) / ATTR([Region])"],
    hint: "Aggregate the numerator and denominator consistently.",
    relatedLessons: ["aggregate-calculations", "logical-calculations"],
  },
  {
    id: "string-calculations",
    title: "String calculations",
    icon: "🔤",
    category: "Calculations",
    difficulty: "Intermediate",
    description: "Clean, combine, search, and classify text with Tableau string functions.",
    example: "Use UPPER([Region]) or SPLIT([Customer Name], ' ', 1) to standardize labels.",
    practiceQuestion: "Which function converts Region values to uppercase?",
    correctAnswer: "UPPER([Region])",
    distractors: ["DATE([Region])", "SUM([Region])"],
    hint: "Use the text function named for uppercase conversion.",
    relatedLessons: ["calculated-fields", "logical-calculations"],
  },
  {
    id: "date-calculations",
    title: "Date calculations",
    icon: "📅",
    category: "Calculations",
    difficulty: "Intermediate",
    description: "Use DATETRUNC, DATEPART, DATEDIFF, and date arithmetic for time-aware analysis.",
    example: "DATETRUNC('month', [Order Date]) creates a consistent month-start date for grouping.",
    practiceQuestion: "Which function returns the start of the month containing Order Date?",
    correctAnswer: "DATETRUNC('month', [Order Date])",
    distractors: ["DATEPART('day', [Order Date])", "DATEDIFF('month', [Order Date], [Order Date])"],
    hint: "The function truncates a date to a chosen level.",
    relatedLessons: ["data-types-and-roles", "line-charts"],
  },
  {
    id: "logical-calculations",
    title: "Logical calculations",
    icon: "🚦",
    category: "Calculations",
    difficulty: "Intermediate",
    description: "Use IF, IIF, CASE, AND, OR, and null checks to classify business outcomes.",
    example: "IF [Profit] > 0 THEN 'Profitable' ELSE 'Loss' END",
    practiceQuestion: "Which expression is best for mapping known Segment values to custom labels?",
    correctAnswer: "A CASE expression",
    distractors: ["A geographic role", "A union"],
    hint: "CASE is concise when comparing one expression to several known values.",
    relatedLessons: ["calculated-fields", "parameters"],
  },
  {
    id: "aggregate-calculations",
    title: "Aggregate calculations",
    icon: "Σ",
    category: "Calculations",
    difficulty: "Intermediate",
    description: "Keep aggregation levels consistent when combining SUM, AVG, COUNT, MIN, and MAX.",
    example: "SUM([Profit]) / SUM([Sales]) avoids mixing aggregate and row-level expressions.",
    practiceQuestion: "Why does SUM([Sales]) - [Cost] produce an error?",
    correctAnswer: "It mixes an aggregate with a row-level field",
    distractors: ["Sales cannot be summed", "Cost must always be a dimension"],
    hint: "Both sides of an expression need compatible aggregation levels.",
    relatedLessons: ["dimensions-and-measures", "calculated-fields"],
  },
  {
    id: "table-calculations",
    title: "Table calculations",
    icon: "↗️",
    category: "Calculations",
    difficulty: "Advanced",
    description: "Compute running totals, ranks, percent differences, and moving values over marks in a view.",
    example: "Apply RUNNING_SUM(SUM([Sales])) and set Compute Using to Month of Order Date.",
    practiceQuestion: "What controls the direction and partition of a table calculation?",
    correctAnswer: "Its addressing and partitioning settings",
    distractors: ["The data connection password", "The workbook file name"],
    hint: "Compute Using tells Tableau how to move across marks in the result table.",
    relatedLessons: ["level-of-detail-expressions", "filter-order-of-operations"],
  },
  {
    id: "level-of-detail-expressions",
    title: "Level of Detail expressions",
    icon: "🔬",
    category: "Calculations",
    difficulty: "Advanced",
    description: "Use FIXED, INCLUDE, and EXCLUDE expressions to calculate at an explicit data grain.",
    example: "{ FIXED [Customer ID] : SUM([Sales]) } returns customer sales independently of dimensions in the view.",
    practiceQuestion: "Which LOD type calculates independently of the view's dimensions?",
    correctAnswer: "FIXED",
    distractors: ["INCLUDE only", "A quick table calculation"],
    hint: "Its level is explicitly fixed by the dimensions inside the expression.",
    relatedLessons: ["table-calculations", "filter-order-of-operations"],
  },
  {
    id: "filter-order-of-operations",
    title: "Filter order of operations",
    icon: "🧅",
    category: "Interactive Analytics",
    difficulty: "Advanced",
    description: "Predict how extract, data source, context, dimension, measure, and table-calculation filters interact.",
    example: "Make Region a context filter before applying a Top 10 Customer filter within the selected region.",
    practiceQuestion: "Which filter should come before a dependent Top N dimension filter?",
    correctAnswer: "A context filter",
    distractors: ["A table-calculation filter", "A dashboard device layout"],
    hint: "Context creates the data subset used by later dimension filters.",
    relatedLessons: ["data-source-filters", "table-calculations"],
  },
  {
    id: "parameters",
    title: "Parameters",
    icon: "🎛️",
    category: "Interactive Analytics",
    difficulty: "Intermediate",
    description: "Let users supply a single value that can drive calculations, filters, reference lines, or field choices.",
    example: "Create a Sales Target parameter and compare SUM(Sales) against it in a calculated field.",
    practiceQuestion: "What makes a parameter different from a filter?",
    correctAnswer: "A parameter stores one independent value that can drive calculations",
    distractors: ["A parameter always removes data rows", "A parameter can only contain dates"],
    hint: "It is an input value, not automatically a data restriction.",
    relatedLessons: ["logical-calculations", "reference-lines"],
  },
  {
    id: "sets",
    title: "Sets",
    icon: "⭕",
    category: "Interactive Analytics",
    difficulty: "Intermediate",
    description: "Define dynamic in/out subsets for comparisons, cohort analysis, and user interaction.",
    example: "Create a Top 10 Customers set and compare IN versus OUT profit performance.",
    practiceQuestion: "What are the two membership states of a Tableau set?",
    correctAnswer: "IN and OUT",
    distractors: ["Rows and Columns", "Live and Extract"],
    hint: "A set divides members based on whether they belong to it.",
    relatedLessons: ["parameters", "dashboard-actions"],
  },
  {
    id: "groups-and-bins",
    title: "Groups and bins",
    icon: "🧺",
    category: "Interactive Analytics",
    difficulty: "Beginner",
    description: "Combine related dimension members with groups and bucket continuous measures with bins.",
    example: "Group small product categories as Other and bin Sales into 500-unit ranges for a histogram.",
    practiceQuestion: "Which feature creates equal-width ranges from a continuous measure?",
    correctAnswer: "Bins",
    distractors: ["Stories", "Relationships"],
    hint: "Bins turn a continuous value into ranges.",
    relatedLessons: ["dimensions-and-measures", "sets"],
  },
  {
    id: "reference-lines",
    title: "Reference lines and bands",
    icon: "📏",
    category: "Interactive Analytics",
    difficulty: "Intermediate",
    description: "Add analytical context such as averages, targets, distributions, and confidence bands.",
    example: "Add an average Sales reference line per pane to compare each category with its regional benchmark.",
    practiceQuestion: "Where are reference lines commonly added from?",
    correctAnswer: "The Analytics pane",
    distractors: ["The data connection dialog", "The Story navigator only"],
    hint: "It is the pane next to Data that contains analytical objects.",
    relatedLessons: ["parameters", "trend-lines"],
  },
  {
    id: "trend-lines",
    title: "Trend lines",
    icon: "📐",
    category: "Interactive Analytics",
    difficulty: "Advanced",
    description: "Add and interpret statistical trend models while checking assumptions and explanatory power.",
    example: "Add a linear trend line to Sales versus Profit and inspect the model description and R-squared.",
    practiceQuestion: "What does R-squared describe in a trend model?",
    correctAnswer: "The share of variation explained by the model",
    distractors: ["The number of dashboard objects", "The extract refresh frequency"],
    hint: "It is a goodness-of-fit measure.",
    relatedLessons: ["scatter-plots", "forecasting"],
  },
  {
    id: "forecasting",
    title: "Forecasting",
    icon: "🔮",
    category: "Interactive Analytics",
    difficulty: "Advanced",
    description: "Extend a time series with Tableau's forecasting model and communicate uncertainty responsibly.",
    example: "Forecast monthly Sales and display prediction intervals after checking seasonality and missing dates.",
    practiceQuestion: "What kind of view is required for Tableau forecasting?",
    correctAnswer: "A view with a date dimension and at least one measure",
    distractors: ["A text table with no date", "A dashboard with only images"],
    hint: "Forecasting needs an ordered time series.",
    relatedLessons: ["line-charts", "trend-lines"],
  },
  {
    id: "dashboard-layout",
    title: "Dashboard layout",
    icon: "🧱",
    category: "Dashboards and Stories",
    difficulty: "Intermediate",
    description: "Arrange tiled and floating objects with containers, hierarchy, spacing, and a clear visual path.",
    example: "Use vertical and horizontal containers to align a KPI row above a trend and comparison section.",
    practiceQuestion: "What is the main benefit of layout containers?",
    correctAnswer: "They keep related dashboard objects aligned and responsive",
    distractors: ["They change source data types", "They create physical joins"],
    hint: "Containers manage groups of dashboard objects.",
    relatedLessons: ["dashboard-actions", "device-designer"],
  },
  {
    id: "dashboard-actions",
    title: "Dashboard actions",
    icon: "⚡",
    category: "Dashboards and Stories",
    difficulty: "Intermediate",
    description: "Create filter, highlight, URL, parameter, set, and navigation interactions across views.",
    example: "Use a map as a filter so selecting a state updates the KPI and customer-detail sheets.",
    practiceQuestion: "Which action should update other sheets to show only a selected region?",
    correctAnswer: "A filter action",
    distractors: ["A URL action", "A story caption"],
    hint: "The interaction needs to restrict marks in target sheets.",
    relatedLessons: ["sets", "dashboard-layout"],
  },
  {
    id: "device-designer",
    title: "Device layouts",
    icon: "📱",
    category: "Dashboards and Stories",
    difficulty: "Intermediate",
    description: "Create dashboard layouts that remain usable on desktop, tablet, and phone screens.",
    example: "Build a phone layout with the KPI, primary trend, and essential filter in a single vertical flow.",
    practiceQuestion: "What should a phone layout prioritize?",
    correctAnswer: "The most important content and touch-friendly interactions",
    distractors: ["Every desktop object at the same size", "More floating decorations"],
    hint: "Small screens need clear priority and comfortable controls.",
    relatedLessons: ["dashboard-layout", "publishing-workbooks"],
  },
  {
    id: "stories",
    title: "Stories",
    icon: "📖",
    category: "Dashboards and Stories",
    difficulty: "Intermediate",
    description: "Sequence worksheets and dashboards into story points that support a guided analytical narrative.",
    example: "Move from national performance to regional drivers and finish with the recommended action.",
    practiceQuestion: "What is a Tableau story point?",
    correctAnswer: "A saved step in a sequence of sheets or dashboards",
    distractors: ["A physical table in a join", "A type of extract filter"],
    hint: "Stories guide an audience through analytical steps.",
    relatedLessons: ["dashboard-layout", "case-study-workflow"],
  },
  {
    id: "extracts-and-live-connections",
    title: "Live connections and extracts",
    icon: "⚙️",
    category: "Performance and Publishing",
    difficulty: "Intermediate",
    description: "Choose between querying the source live and using an optimized Tableau extract.",
    example: "Use an extract for a stable analytical dataset that needs scheduled refreshes and fast interaction.",
    practiceQuestion: "When is an extract often appropriate?",
    correctAnswer: "When optimized performance and scheduled snapshots are acceptable",
    distractors: ["When every query must reflect a source transaction instantly", "When no data should be stored outside the source under any circumstance"],
    hint: "Extracts trade immediate source queries for optimized stored data.",
    relatedLessons: ["performance-recording", "publishing-workbooks"],
  },
  {
    id: "performance-recording",
    title: "Performance recording",
    icon: "⏱️",
    category: "Performance and Publishing",
    difficulty: "Advanced",
    description: "Measure workbook events to find slow queries, rendering, calculations, and dashboard design choices.",
    example: "Record a slow dashboard interaction, then inspect query execution and layout events before optimizing.",
    practiceQuestion: "What should guide workbook performance optimization?",
    correctAnswer: "Measured evidence from queries, calculations, and rendering events",
    distractors: ["Changing every font first", "Removing random fields without measuring"],
    hint: "Diagnose the actual bottleneck before changing the workbook.",
    relatedLessons: ["extracts-and-live-connections", "performance-interview"],
  },
  {
    id: "publishing-workbooks",
    title: "Publishing workbooks",
    icon: "☁️",
    category: "Performance and Publishing",
    difficulty: "Intermediate",
    description: "Publish to Tableau Cloud or Server with correct projects, permissions, credentials, and refresh settings.",
    example: "Publish a certified sales dashboard to the Finance project and confirm its data credentials and schedule.",
    practiceQuestion: "What must be validated immediately after publishing?",
    correctAnswer: "Permissions, data access, refresh behavior, and the rendered views",
    distractors: ["Only the workbook color palette", "Only the local file path"],
    hint: "A successful upload does not guarantee users can access fresh data.",
    relatedLessons: ["row-level-security", "device-designer"],
  },
  {
    id: "row-level-security",
    title: "Row-level security",
    icon: "🔐",
    category: "Performance and Publishing",
    difficulty: "Advanced",
    description: "Restrict records by signed-in user through entitlement data and user-aware filtering patterns.",
    example: "Relate an entitlement table by Region and filter with USERNAME() so managers see authorized regions only.",
    practiceQuestion: "What should an entitlement table connect?",
    correctAnswer: "User identities to the data values they may access",
    distractors: ["Dashboard colors to font sizes", "Extract files to worksheet captions"],
    hint: "Security rules map a viewer to permitted data domains.",
    relatedLessons: ["relationships", "publishing-workbooks"],
  },
  {
    id: "interview-chart-choice",
    title: "Interview: chart selection",
    icon: "💬",
    category: "Interview Preparation",
    difficulty: "Intermediate",
    description: "Explain chart choices from the business question, audience, data types, and comparison task.",
    example: "Defend a sorted bar chart for category comparison and explain why a pie chart would be less precise.",
    practiceQuestion: "What is the strongest reason for choosing a chart in an interview?",
    correctAnswer: "It matches the analytical task and communicates clearly to the audience",
    distractors: ["It uses the most colors", "It is the newest chart type"],
    hint: "Start with the question and the decision the audience must make.",
    relatedLessons: ["chart-selection", "case-study-workflow"],
  },
  {
    id: "performance-interview",
    title: "Interview: workbook performance",
    icon: "🚀",
    category: "Interview Preparation",
    difficulty: "Advanced",
    description: "Diagnose slow workbooks systematically across data, calculations, filters, marks, and dashboard design.",
    example: "Explain how you would record performance, isolate slow queries, reduce expensive marks, and retest.",
    practiceQuestion: "What should be the first step when a dashboard is slow?",
    correctAnswer: "Measure the workbook and identify the actual bottleneck",
    distractors: ["Rebuild every worksheet immediately", "Add more quick filters"],
    hint: "Optimization should be evidence-driven.",
    relatedLessons: ["performance-recording", "extracts-and-live-connections"],
  },
  {
    id: "lod-vs-table-calc-interview",
    title: "Interview: LOD vs table calculations",
    icon: "🧠",
    category: "Interview Preparation",
    difficulty: "Advanced",
    description: "Distinguish calculations performed at the data-query grain from calculations performed over view results.",
    example: "Use FIXED for customer lifetime sales independent of the view; use running sum for cumulative marks across months.",
    practiceQuestion: "Which calculation is computed over marks already returned to the view?",
    correctAnswer: "A table calculation",
    distractors: ["A FIXED LOD expression", "A physical join clause"],
    hint: "Think about whether the calculation uses the result table or defines a query grain.",
    relatedLessons: ["table-calculations", "level-of-detail-expressions"],
  },
  {
    id: "case-study-workflow",
    title: "Interview: case study workflow",
    icon: "🗃️",
    category: "Interview Preparation",
    difficulty: "Advanced",
    description: "Structure an end-to-end Tableau case study from requirements and data validation through insight and delivery.",
    example: "Clarify the decision, profile data, model grain, sketch views, validate numbers, build interactions, and present recommendations.",
    practiceQuestion: "What should come before building charts in a Tableau case study?",
    correctAnswer: "Clarifying the business decision and validating the data",
    distractors: ["Choosing dashboard background colors", "Publishing an empty workbook"],
    hint: "A strong solution begins with purpose and trustworthy inputs.",
    relatedLessons: ["interview-chart-choice", "stories", "publishing-workbooks"],
  },
];

export const tableauLessons = [...seeds, ...tableauLessonExpansion].map(createLesson);

export function getTableauLesson(id: string) {
  return tableauLessons.find((lesson) => lesson.id === id);
}

export function getNextTableauLesson(id: string) {
  const index = tableauLessons.findIndex((lesson) => lesson.id === id);
  return index >= 0 ? tableauLessons[index + 1] : undefined;
}
